### ISSUE TITLE
Synchronization failed

### ISSUE THREAD

**Issue by wo4zhuzi** [terra-money/core#125]
The following error was reported when using version v2.2.0

"7:25PM ERR Stopping peer for error err=EOF module=p2p peer={"Data":{},"Logger":{}}
7:25PM INF service stop impl={"Data":{},"Logger":{}} module=p2p msg={} peer={"id":"51db3b0e09016c58d6e1ea0e7916e15138b015be","ip":"65.108.98.218","port":11095}"

4699660 is out of sync

The following error was reported when using version v2.3.0

"failed to load latest version: version of store alliance mismatch root store's version; expected 4699660 got 0"

May I know how to handle it?

**Comment by gregnuj** [comment]
What chain are you using pisco or phoenix?

**Comment by timurgum** [comment]
the same problem came out, well, when you upgrade to version 2.3.0, nothing has chang

**Comment by wo4zhuzi** [comment]
.
