### ISSUE TITLE
terrad tendermint show-validator does not return the public Consensus key

### ISSUE THREAD

**Issue by awsdataarchitect** [terra-money/core#24]
terravalconspub

it returns something like
{"@type":"/cosmos.crypto.ed25519.PubKey","key":"qsadasdasdsadasdasdsadasd"}
instead of 
Example: terravalconspub1zcjduc3qcyj09qc03elte23zwshdx92jm6ce88fgc90rtqhjx8v0608qh5ssp0w94c

**Comment by hanjukim** [comment]
No. Current output is correct for pubkey paramter for `tx staking create-validator`

**Comment by awsdataarchitect** [comment]
@hanjukim  any idea why this is failing
terrad  gentx validator 10uluna --chain-id phoenix-1
Error: failed to validate genesis state: genesis supply is incorrect, expected 1000000000000000uluna, got 1000000000000010uluna
Usage:

**Comment by awsdataarchitect** [comment]
terrad start also errors
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
Us

**Comment by xlalon** [comment]
3:19AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount
and after do terrad tendermint unsafe-reset-all
3:22AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount
