### ISSUE TITLE
terrad start not working

### ISSUE THREAD

**Issue by awsdataarchitect** [terra-money/core#26]
terrad start 
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**Comment by xlalon** [comment]
3:17AM INF claimed capability capability=2 module=icahost name=ports/icahost
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
and after i do /terrad tendermint unsafe-reset-all
3:22AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

**Comment by airstring** [comment]
> terrad init xxx wget -O ~/.terra/config/genesis.json https://cloudflare-ipfs.com/ipfs/QmZAMcdu85Qr8saFuNpL9VaxVqqLGWNAs72RVFhchL9jWs curl https://network.terra.dev/addrbook.json > ~/.terrad/config/addrbook.json terrad start ... 3:17AM INF claimed capability capability=2 module=icahost name=ports/icahost Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
> 
> and after i do /terrad tendermint unsafe-reset-all 3:22AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0 panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

Have you taken care of  this program?

**Comment by awsdataarchitect** [comment]
The ipfs file you are downloading is for classic luna (v.0.5) not this repo(v2)

**Comment by airstring** [comment]
> 
Where can I download the v2 file？Please give me an address, thanks!

**Comment by awsdataarchitect** [comment]
It will be available tomorrow on this page under the phoenix-1 chain

https://docs.terra.money/docs/full-node/run-a-full-terra-node/join-a-network.html

**Comment by airstring** [comment]
> It will be available tomorrow on this page under the phoenix-1 chain
> 
> https://docs.terra.money/docs/full-node/run-a-full-terra-node/join-a-network.html

I see. Thank you！

**Comment by Tab-ops** [comment]
I also have the same question, when can I download the genesis.json of v2.0 today?

**Comment by sascha1337** [comment]
# Genesis
https://terra-pub.s3.amazonaws.com/genesis.json

# Addrbook 
https://cdn.discordapp.com/attachments/591812948867940362/980003631388561448/addrbook.json

# Some seeds: 

406bcf90a7b29df6ae475a1f94abe04ebde805af@phoenix.seed.stakebin.io:16656,fc608a9a117d8d2302bcd181aec34eec6bb4fa96@terra2-seed.blockpane.com:26656,8efd8248e06aabd553b56766ec2a850999d0861f@exitnode.cereslabs.io:36656,a07cec8341f149ed49f751146728cf81f83764ff@84.244.95.239:26656,cffc34088450d1c33e0c67663386f803bd1359f6@94.130.33.117:26656,b4d3b21747539060b270457437ef1bf99a51c694@terra2.seed.synergynodes.com:26656,f28efad2d76857c2606f00bee014346481734ea0@116.203.29.116:46656,810d1628db9f1db56fa87a93fb6ef809c32d6325@phoenix.seed.terra.btcsecure.io:26656

**Comment by awsdataarchitect** [comment]
Thank you @sascha1337....Will it broadcast a validators transaction now ?

**Comment by awsdataarchitect** [comment]
I seem to be stuck at block 11

 terrad status
{"NodeInfo":{"protocol_version":{"p2p":"8","block":"11","app":"0"},"id":"a5d6873e308622558655d61ebe082cb56fa1401a","listen_addr":"18.234.30.166:26656","network":"phoenix-1","version":"v0.34.19-terra.2","channels":"402021222330386061","moniker":"waltsoft.money","other":{"tx_index":"on","rpc_address":"tcp://0.0.0.0:26657"}},"SyncInfo":{"latest_block_hash":"","latest_app_hash":"","latest_block_height":"0","latest_block_time":"1970-01-01T00:00:00Z","earliest_block_hash":"","earliest_app_hash":"","earliest_block_height":"0","earliest_block_time":"1970-01-01T00:00:00Z","catching_up":true},"ValidatorInfo":{"Address":"51132F7561C4F89266B6EECB6DC2FB703513565B","PubKey":{"type":"tendermint/PubKeyEd25519","value":"L1/47wjKrXHvgyAX2dhZXUOlXH7qswffRSNodrQxDZA="},"VotingPower":"0"}}

**Comment by awsdataarchitect** [comment]
2:23PM INF Starting Evidence service impl=Evidence module=evidence
2:23PM INF Saving AddrBook to file book=/root/.terra/config/addrbook.json module=p2p size=0
2:23PM INF starting API server... module=api-server
2:23PM INF Starting RPC HTTP server on [::]:1317 module=api-server

**Comment by awsdataarchitect** [comment]
ok, i fixed mine.. use these values if anyone needs assistance

**# Comma separated list of seed nodes to connect to**
seeds = "406bcf90a7b29df6ae475a1f94abe04ebde805af@phoenix.seed.stakebin.io:16656,fc608a9a117d8d2302bcd181aec34eec6bb4fa96@terra2-seed.blockpane.com:26656,8efd8248e06aabd553b56766ec2a850999d0861f@exitnode.cereslabs.io:36656,a07cec8341f149ed49f751146728cf81f83764ff@84.244.95.239:26656,cffc34088450d1c33e0c67663386f803bd1359f6@94.130.33.117:26656,b4d3b21747539060b270457437ef1bf99a51c694@terra2.seed.synergynodes.com:26656,f28efad2d76857c2606f00bee014346481734ea0@116.203.29.116:46656,810d1628db9f1db56fa87a93fb6ef809c32d6325@phoenix.seed.terra.btcsecure.io:26656"

**# Comma separated list of nodes to keep persistent connections to**
persistent_peers = "028b5c97ac5a01863d3f263df7a5814247094b18@23.19.122.193:26656,03636a257cd099c4f070166bfa09db1aef2645b8@23.88.73.18:26656,065fd6f49a4a424727433b3a8e3d5945e4935d9c@78.46.68.41:26656,0958d078065391716b30cfcb0c9abb3e86c590fb@0.0.0.0:26656,0b3b323185ce4b7b4fa3c9943ccc1213d64d65be@172.24.138.207:26656,0d7823edd87cb64490a5fcd234bf47864b457704@0.0.0.0:26656,0f1096278efafcf3f0d3bd5b6544e6b8dcc36a0e@206.189.129.195:26656,15d8ae2a5bc80485b5bde6056f98eaf9b0ba1cf4@142.132.147.125:26656,18a22858612e8cd03bf6030ebf9d196679bce286@0.0.0.0:26656,19470214d4c9ad8afce77d95c75c0e7ec1694222@0.0.0.0:26656,19bfe3befd4ce6c95e8559f9d9835253cac4fcfb@121.134.50.135:26656,1e339b9b079bad141bdb3e6cf6ec37a5fefca33a@15.235.54.38:26656,1e5e39efe018876c355cbb81a772668e5ce5e1ea@10.10.2.100:26656,21b040b77ac4d95b26111b22ae5153591cf28d70@37.120.245.45:26656,228eaee658dc4e376aad6f5d4934e5f0b37cf38f@34.250.13.25:26656,24db9dd1ea7ed07dd112fd367d112da8d9dc5240@65.21.127.162:26656,2a13fcdb77af7248f0799cd540a8c27c218586f4@38.242.192.114:26656,2a21138f2036e28ce205454cea919325940a9302@172.31.25.158:26656,2b921acfbaa8c12487766823c706d4c3866153a7@0.0.0.0:26656,2e3f552c41f937f53c6c8c7970d273e2322178e3@192.168.0.46:26656,32685ff3b4114cef3efbf30e541a97d528333dd4@172.24.138.207:26656,352deb885fed9a3901be348934cdb74e7c3e6b65@157.245.155.159:26656,364e9c6008f853dc5c95a14f18ebc7f1edafc269@37.143.129.216:26656,38677bd732f6816b8a293b352f17efb23d2a6c58@65.108.0.165:26656,4f13614ace7ec7d7dffdcf8eb52b8425cc5b9eec@172.31.23.209:26656,5558ee2f258883ffb66ef20b2f0bf20a39834847@88.99.25.180:26656,567d86e117c6b26b435d7fe5a32d91ea94e0e3f0@65.108.230.84:26656,5887b4ec8934a419224ab5d897272bcc53fa8ee9@3.121.197.95:26656,5bf51a2268370a90889574780036918523583096@65.21.204.185:26656,5ee811d2bed9d55c629920ec4269f72e60b8683b@0.0.0.0:26656,643af87bbcc79d40340c4d1e6039d7f0de3d86f1@172.24.138.207:26656,65de9e04f72197e37ee200e078d59339edf0002d@172.31.61.182:26656,69689a1f7f26bff21a4f146305239c6e7ac9b9a9@0.0.0.0:26656,6c5f2ce3bcc54f469dd28e19b8b285062395503d@172.31.3.142:26656,6c6964a217579f18aa38919d184de8ad2bb5a5be@135.181.216.54:26656,6cd405861df27c206c6db39830026b4880005ddb@172.31.34.163:26656,721d21a3566ffd3e198099b7c30d153a0b364bd7@172.31.33.115:26656,7373e44b7e7d768a863e5fdf58d8234c75a893d2@0.0.0.0:26656,75f6fecc2470f0ea31dc1227e62d8c7f35e43deb@172.31.31.148:26656,76f58340d68a11b2952615b86d8b26d697a71c34@192.168.2.125:26656,7ac1c9981bf1ec0830a6c86497039d3e92b0a55b@172.20.10.2:26656,7c694dd3fee3e994a630a6e27adbf9858c37836f@178.128.118.111:26656,7e046a03f9cbf589c1f7223a5e27a09f03f7ba56@172.24.138.207:26656,80f6dab802b25fe0c2f5d95ce88db0022e32a44d@172.31.7.229:26656,810d1628db9f1db56fa87a93fb6ef809c32d6325@195.201.106.133:26656"

**Comment by oneusdt** [comment]
@awsdataarchitect Please help me find out which file seeds is used in

**Comment by oneusdt** [comment]
@awsdataarchitect I am also in register a validator. I would like to ask you what to do next after the full node is successful? thank you！

**Comment by awsdataarchitect** [comment]
~/.terra/config/config.toml

**Comment by awsdataarchitect** [comment]
> @awsdataarchitect I am also in register a validator. I would like to ask you what to do next after the full node is successful? thank you！

Once node is fully sync , create validator tx

**Comment by oneusdt** [comment]
Is it here https://docs.terra.money/docs/full-node/manage-a-terra-validator/set-up-validator.html ？ thank u
