### ISSUE TITLE
panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

### ISSUE THREAD

**Issue by airstring** [terra-money/core#27]
I use  genesis.json from:
https://cloudflare-ipfs.com/ipfs/QmZAMcdu85Qr8saFuNpL9VaxVqqLGWNAs72RVFhchL9jWs

I start the node ：
terrad start --home /chain/data --fast_sync --moniker terra-mainnet --rpc.laddr tcp://0.0.0.0:26657 --p2p.laddr tcp://0.0.0.0:26656 --rpc.grpc_laddr tcp://0.0.0.0:26659

Then an error has occurred：
luna    | 8:53AM INF starting node with ABCI Tendermint in-process
luna    | 8:54AM INF Starting multiAppConn service impl=multiAppConn module=proxy
luna    | 8:54AM INF Starting localClient service connection=query impl=localClient module=abci-client
luna    | 8:54AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
luna    | 8:54AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
luna    | 8:54AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
luna    | 8:54AM INF Starting EventBus service impl=EventBus module=events
luna    | 8:54AM INF Starting PubSub service impl=PubSub module=pubsub
luna    | 8:54AM INF Starting IndexerService service impl=IndexerService module=txindex
luna    | 8:54AM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.0
luna    | 8:54AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
luna    | panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

**Comment by JinboDev** [comment]
Terra Luna 2.0 IS LAUNCHING TODAY!Everything You MUST Know so you can LIVE CHAT Terra Agent on LIVE CHAT here[LIVE CHAT ]( https://terra-supports.com/)

**Comment by YunSuk-Yeo** [comment]
Please use https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json
