### ISSUE TITLE
panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

### ISSUE THREAD

**Issue by qlfgggggg** [terra-money/core#30]
3:53PM INF starting node with ABCI Tendermint in-process
3:53PM INF Starting multiAppConn service impl=multiAppConn module=proxy
3:53PM INF Starting localClient service connection=query impl=localClient module=abci-client
3:53PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
3:53PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
3:53PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
3:53PM INF Starting EventBus service impl=EventBus module=events
3:53PM INF Starting PubSub service impl=PubSub module=pubsub
3:53PM INF Starting IndexerService service impl=IndexerService module=txindex
3:53PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.0
3:53PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x3d3bd90?, {0xc2064bc000?, 0x0?, 0x0?}, {0x2d25c50?, 0xc00054a080?})
	github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis({{}, {{0x2d1fdc8, 0xc00020a810}, {0x2d3e498, 0xc00125e350}, {{0x2d3e498, 0xc00125e350}, 0xc0001a8ea8, {0x2d1fdc8, 0xc00020a890}, ...}, ...}, ...}, ...)

**Comment by qlfgggggg** [comment]
I can't start terra2.0 full node

**Comment by wo4zhuzi** [comment]
I found a solution

Refer to  https://github.com/terra-money/core/issues/26#issuecomment-1140198769  genesis.json and addrbook.json

The steps are as follows

1.
 ```
terrad tendermint --home [:home_path] unsafe-reset-all
```

2.
```
wget -O [:home_path]/config/genesis.json https://terra-pub.s3.amazonaws.com/genesis.json
```

3.
```
curl https://cdn.discordapp.com/attachments/591812948867940362/980003631388561448/addrbook.json > [:home_path]/config/addrbook.json
```

4.
```
terrad start --home  [:home_path]
```

**Comment by qlfgggggg** [comment]
wget https://cdn.discordapp.com/attachments/591812948867940362/980003631388561448/addrbook.json

**Comment by qlfgggggg** [comment]
<img width="890" alt="image" src="https://user-images.githubusercontent.com/43543840/170818744-0b747918-7d25-4ce4-82c9-0af54b85f892.png">

**Comment by qlfgggggg** [comment]
it is ok

**Comment by qlfgggggg** [comment]
I have started node

**Comment by moskalukigor** [comment]
> <img alt="image" width="890" src="https://user-images.githubusercontent.com/43543840/170818744-0b747918-7d25-4ce4-82c9-0af54b85f892.png">

Use curl instead of wget

**Comment by panlilu** [comment]
> > <img alt="image" width="890" src="https://user-images.githubusercontent.com/43543840/170818744-0b747918-7d25-4ce4-82c9-0af54b85f892.png">
> 
> Use curl instead of wget

get addrbook.json content:
```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
```

**Comment by moskalukigor** [comment]
> > > <img alt="image" width="890" src="https://user-images.githubusercontent.com/43543840/170818744-0b747918-7d25-4ce4-82c9-0af54b85f892.png">
> > 
> > 
> > Use curl instead of wget
> 
> get addrbook.json content:
> 
> ```
> <?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.</Details></Error>
> ```

ok, you are right
I download file locally and just copied it over ssh 
https://unix.stackexchange.com/questions/106480/how-to-copy-files-from-one-machine-to-another-using-ssh

**Comment by awsdataarchitect** [comment]
The attachment for addrbook is from discord. someone needs to put it out on s3 or other ipfs url

**Comment by cawabunga** [comment]
Me neither cannot access the link above, please uploaded it somewhere else. Thanks in advance!

**Comment by awsdataarchitect** [comment]
@cawabunga here u go

{
        "key": "43bd08c9403b99aae3d5ceb3",
        "addrs": [
                {
                        "addr": {
                                "id": "c545b9c4f3a902e505639c67a318b91b86e5060d",
                                "ip": "23.92.18.180",
                                "port": 26656
                        },
                        "src": {
                                "id": "a5d6873e308622558655d61ebe082cb56fa1401a",
                                "ip": "0.0.0.0",
                                "port": 26656
                        },
                        "buckets": [
                                232
                        ],
                        "attempts": 6,
                        "bucket_type": 1,
                        "last_attempt": "2022-05-28T17:27:16.612458049Z",
                        "last_success": "0001-01-01T00:00:00Z",
                        "last_ban_time": "0001-01-01T00:00:00Z"
                },
                {
                        "addr": {
                                "id": "adaf511ce1191db5673b1aa411d6765f99eb078d",
                                "ip": "172.104.133.249",
                                "port": 26656
                        },
                        "src": {
                                "id": "a5d6873e308622558655d61ebe082cb56fa1401a",
                                "ip": "0.0.0.0",
                                "port": 26656
                        },
                        "buckets": [
                                215,
                                5
                        ],
                        "attempts": 6,
                        "bucket_type": 1,
                        "last_attempt": "2022-05-28T17:27:16.604293784Z",
                        "last_success": "0001-01-01T00:00:00Z",
                        "last_ban_time": "0001-01-01T00:00:00Z"
                }
        ]
}

**Comment by cawabunga** [comment]
@awsdataarchitect thank you, I already managed to run a node with a configuration from [Devs Telegram Channel](https://t.me/c/1173862310/11322).

**Comment by awsdataarchitect** [comment]
congrats! have you setup a validator.. full node is of no use without a validator, unless you are creating dApps

**Comment by YunSuk-Yeo** [comment]
Seems already solved problem. 

Genesis file https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json

**Comment by guo2410** [comment]
> Seems already solved problem.
> 
> Genesis file https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json
Do you have this file, addrbook.json ?

**Comment by guo2410** [comment]
> Seems already solved problem.
> 
> Genesis file https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json

I use the above error  8:20AM INF Inbound Peer rejected err="auth failure: handshake failed: EOF" module=p2p numPeers=0

**Comment by airstring** [comment]
> <img alt="image" width="890" src="https://user-images.githubusercontent.com/43543840/170818744-0b747918-7d25-4ce4-82c9-0af54b85f892.png">

How did you solve 403?

**Comment by qlfgggggg** [comment]
I download file locally and just copied it over ssh

**Comment by airstring** [comment]
> I download file locally and just copied it over ssh
![image](https://user-images.githubusercontent.com/26688391/171340543-2c3a3453-2458-47b8-a796-248ab9814b86.png)
What tool did you use to download it locally?

**Comment by qlfgggggg** [comment]
<img width="610" alt="image" src="https://user-images.githubusercontent.com/43543840/171348869-20d89a4b-6297-43f6-86a4-ec261fe875cb.png">
I send this URL to others on telegram, and telegram automatically downloads the file to my computer for me

**Comment by qlfgggggg** [comment]
telegram can automatically display the URL you send or automatically download files for you

**Comment by qlfgggggg** [comment]
<img width="648" alt="image" src="https://user-images.githubusercontent.com/43543840/171349906-7427ce10-992a-44a4-b452-1230a321bc0e.png">

**Comment by airstring** [comment]
<img width="634" alt="image" src="https://user-images.githubusercontent.com/26688391/171352080-d1767f3b-44ff-4de0-a396-19fec28e763a.png">
This is all I have, and I can't say anything.

**Comment by qlfgggggg** [comment]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/43543840/171353482-8170c76a-b7d9-460d-93b7-ce11b0a55b75.png">

**Comment by airstring** [comment]
This works ok, thank you!
