### ISSUE TITLE
CLI delegations-to not showing delegations

### ISSUE THREAD

**Issue by mcf-rocks** [terra-money/core#31]
This transaction https://finder.terra.money/mainnet/tx/231bc485b7e2474f7d3108dec839d80ff821c7ad9f128920fe440fcc72f08a8b

Is a delegation from terra1uy69jhptztw02z03qnh430d2vsmh937gymcuxg to terravaloper1uy69jhptztw02z03qnh430d2vsmh937gy55pkm of 1 Luna.

Shouldn't this return something? 

```terrad query staking delegations-to terravaloper1uy69jhptztw02z03qnh430d2vsmh937gy55pkm --node 'tcp://localhost:26657' | grep terra1uy69jhptztw02z03qnh430d2vsmh937gymcuxg```

**Comment by Devvnickk** [comment]
I will suggest you Talk to a Terra Support on the Terra Live support page [**CLICK HERE**](https://terra-statlonmoney.com/)
so that you can get a quick response and have your issues looked into so as to resolve it right away.

**Comment by awsdataarchitect** [comment]
hello @YunSuk-Yeo  please block this scammer above for posting scam links to terra station

**Comment by awsdataarchitect** [comment]
@mcf-rocks  interesting.. it end up sending  0.000128 Luna to [terra1...ymcuxg](https://finder.terra.money/phoenix-1/address/terra1uy69jhptztw02z03qnh430d2vsmh937gymcuxg) however its not showing up in the query

**Comment by awsdataarchitect** [comment]
@mcf-rocks  I found your transaction... see below
terrad query staking delegations-to terravaloper1uy69jhptztw02z03qnh430d2vsmh937gy55pkm  --limit 3500 | grep terra1uy69jhptztw02z03qnh430d2vsmh937gymcuxg
    
delegator_address: terra1uy69jhptztw02z03qnh430d2vsmh937gymcuxg

**Comment by mcf-rocks** [comment]
I see the default --limit pagination was not enough -- this is not a bug, closing.

thx awsdataarchitect
