### ISSUE TITLE
how can I get the terra version of v2.12.5

### ISSUE THREAD

**Issue by malingzhao** [terra-money/core#339]
<img width="1341" alt="image" src="https://github.com/user-attachments/assets/f53e1352-1bb7-4361-af90-e94d76a43f5f">

**Comment by miladvatankhah** [comment]
hi @malingzhao 
did you found a way to get it?

**Comment by malingzhao** [comment]
no

**Comment by malingzhao** [comment]
do you find a way to get it , or the block is ok?

**Comment by malingzhao** [comment]
https://github.com/phoenix-directive/core/releases/tag/v2.12.5

**Comment by malingzhao** [comment]
In the tg found it
