### ISSUE TITLE
Support our validator by stacking with us

### ISSUE THREAD

**Issue by Anonynode** [terra-money/core#36]
Support our validator!
 thank you
https://finder.terra.money/mainnet/validator/terravaloper1n8c73565zd4tme5hhasvtzz8ad4nwxyex0ge7e

**Comment by awsdataarchitect** [comment]
it show inactive

**Comment by Anonynode** [comment]
thats the issue... everything is working fine from our side but it shows inactive
does it simply mean we dont have enough voting power to be active?

**Comment by awsdataarchitect** [comment]
The validator is not in the [active validator set](https://docs.terra.money/docs/learn/glossary.html#active-set). Only the top 130 validators are in this set. To fix this problem, increase your total stake to be larger than the 130th validator.

**Comment by awsdataarchitect** [comment]
just a tip, u undelegated your vested luna from a random validator (assigned by genesis)- instead you can just use redelegate option (undelegate option takes 21 days)

**Comment by Anonynode** [comment]
Yes we saw that problem is we delegated all our tokens and forgot to keep some for gaz hehehe

**Comment by awsdataarchitect** [comment]
lol....any ideas how to send luna from classic to v2 ?

**Comment by Anonynode** [comment]
Without going through an exchange I dont think so... there are no bridges as of now
