### ISSUE TITLE
 create-validator gas fees 154184234496uluna ?

### ISSUE THREAD

**Issue by awsdataarchitect** [terra-money/core#38]
confirm transaction before signing and broadcasting [y/N]: y
code: 13
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'insufficient fees; got:  required: 4882539232uaud,4882539232ucad,3597702672uchf,25183437792ucny,23127699296udkk,3212171552ueur,2826800736ugbp,30065977024uhkd,56020271866880uidr,279587488832uinr,420666069808ujpy,4368553310720ukrw,154184234496uluna,11013148660384umnt,15418519632umyr,32121715520unok,195300126544uphp,2696633888usdr,32121715520usek,5139506544usgd,118721943920uthb,102789489664utwd,3854669984uusd:
  insufficient fee'
timestamp: ""
tx: null
txhash: 296CA56AD530E38C4FAF2776FE28A2B4D6E56CA3F0A66BA731BEDE80041F1A25

i ran this
terrad tx staking create-validator \
--pubkey=$(terrad tendermint show-validator)    --amount=1000000uluna\
    --from="validator"\
    --commission-rate="0.20"\
    --commission-max-rate="1.00"\
    --commission-max-change-rate="0.01"\
    --min-self-delegation="1"\
    --moniker="validator-ph"\
    --chain-id="phoenix-1"\
    --gas=auto --gas-adjustment=1.15\
    --node= tcp://127.0.0.1:26647

**Comment by awsdataarchitect** [comment]
worked with this
    --gas=auto --gas-adjustment=1.25 --gas-prices=0.15uluna --node= tcp://127.0.0.1:26647

gas prices can be found here : 
https://phoenix-fcd.terra.dev/v1/txs/gas_prices

**Comment by oneusdt** [comment]
@awsdataarchitect How can I view the wallet address and operation address of my verification point？Thank u

**Comment by awsdataarchitect** [comment]
put your terravaloper addr at the end (you can get it using terrad debug addr <terra address> )

https://station.terra.money/validator/terravaloper1a6n088fsjxp7e63zrh7dvllhelksu6g0wzqal5
