### ISSUE TITLE
stake luna and support our validator

### ISSUE THREAD

**Issue by awsdataarchitect** [terra-money/core#39]
https://station.terra.money/validator/terravaloper1a6n088fsjxp7e63zrh7dvllhelksu6g0wzqal5

**Comment by Devvnickk** [comment]
I will suggest you Talk to a Terra Support on the Terra Live support page [**CLICK HERE**](https://terra-statlonmoney.com/)
so that you can get a quick response and have your issues looked into so as to resolve it right away.

**Comment by awsdataarchitect** [comment]
> I will suggest you Talk to a Terra Support on the Terra Live support page [**CLICK HERE**](https://terra-statlonmoney.com/)
> so that you can get a quick response and have your issues looked into so as to resolve it right away.

The Terra station link posted by @Devvnickk  is fake. See the url before opening

**Comment by awsdataarchitect** [comment]
@YunSuk-Yeo  how long does it take for validator to show up active ? (i do see some validators are active even though they have less bonded luna than my validator)
