### ISSUE TITLE
[BUG] Genesis Export

### ISSUE THREAD

**Issue by YunSuk-Yeo** [terra-money/core#392]
**Describe the bug**
tequila-0002 genesis was made from tequila-0001 final state, but the exported cumulated height was almost 66k not actual final block of tequila-0001 network(~21k).

I can't reproduce it on other network, so I will do test it after tequila-0002 retiree.

**To Reproduce**
can't reproduce

**Context & versions**
v0.4.0-rc.x

**Comment by hanjukim** [comment]
Can we verify this is fixed?

**Comment by hanjukim** [comment]
@YunSuk-Yeo fixed?

**Comment by YunSuk-Yeo** [comment]
not yet verified
