### ISSUE TITLE
Help me, I can't create a validator

### ISSUE THREAD

**Issue by oneusdt** [terra-money/core#40]
terrad tx staking create-validator \
>     --amount=5000000uluna \
>     --pubkey=$(terrad tendermint show-validator) \
>     --moniker="validator" \
>     --chain-id="phoenix"-1 \
>     --from="validator" \
>     --commission-rate="0.10" \
>     --commission-max-rate="0.20" \
>     --commission-max-change-rate="0.01" \
>     --min-self-delegation="1"
Error: validator.info: key not found

**Comment by awsdataarchitect** [comment]
terrad keys add validator --recover

(recover existing wallet or create new then send 1-2 luna there but no bridge exist for v2 unless u got an airdrop)

**Comment by oneusdt** [comment]
@awsdataarchitect Thank you so much. Please leave your wallet address and I'll give you a tip.

**Comment by awsdataarchitect** [comment]
thank you, please stake some luna to my validator
https://station.terra.money/validator/terravaloper1a6n088fsjxp7e63zrh7dvllhelksu6g0wzqal5

**Comment by oneusdt** [comment]
@awsdataarchitect I only have lunc and three Lunas now. I will support you when I get the airdrop. Thank you. How do I create a new wallet?

**Comment by awsdataarchitect** [comment]
https://station.terra.money/

**Comment by oneusdt** [comment]
@awsdataarchitect Can I do lunc validator node?

**Comment by awsdataarchitect** [comment]
No, they have disabled it for Lunc

**Comment by awsdataarchitect** [comment]
Not sure but try stake it with any existing Lunc validator

**Comment by oneusdt** [comment]
@awsdataarchitect I'll just have to be patient.
