### ISSUE TITLE
Can't create a Terra 2.0 validator

### ISSUE THREAD

**Issue by carangel** [terra-money/core#41]
Hello,

I'm facing some difficulties for several hours setting up a validator.

After installing Go, Terra core, executing `terrad init` and downloading the genesis file I try to start terrad but get this error : 
> Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**Comment by Devvnickk** [comment]
I will suggest you Talk to a Terra Support on the Terra Live support page [**CLICK HERE**](https://terra-statlonmoney.com/)
so that you can get a quick response and have your issues looked into so as to resolve it right away.

**Comment by carangel** [comment]
BE CAREFUL, PREVIOUS ANSWER IS A SCAM !

**Comment by CooleRnax** [comment]
Same issue

**Comment by Devvnickk** [comment]
I will suggest you Talk to a Terra Support on the Terra Live support page [**CLICK HERE**](https://terra-statlonmoney.com/)
so that you can get a quick response and have your issues looked into so as to resolve it right away.

**Comment by CooleRnax** [comment]
Warning comment above is scam

**Comment by YunSuk-Yeo** [comment]
Try 

terrad tendermint unsafe-reset-all

**Comment by CooleRnax** [comment]
> Try
> 
> terrad tendermint unsafe-reset-all

```
I[2022-05-29|17:05:57.806] Removed existing address book                file=/root/.terra/config/addrbook.json
I[2022-05-29|17:05:57.820] Removed all blockchain history               dir=/root/.terra/data
I[2022-05-29|17:05:57.840] Reset private validator file to genesis state keyFile=/root/.terra/config/priv_validator_key.json stateFile=/root/.terra/data/priv_validator_state.json

5:05PM INF starting node with ABCI Tendermint in-process
5:06PM INF Starting multiAppConn service impl=multiAppConn module=proxy
5:06PM INF Starting localClient service connection=query impl=localClient module=abci-client
5:06PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
5:06PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
5:06PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
5:06PM INF Starting EventBus service impl=EventBus module=events
5:06PM INF Starting PubSub service impl=PubSub module=pubsub
5:06PM INF Starting IndexerService service impl=IndexerService module=txindex
5:06PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.1
5:06PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
5:06PM INF asserting crisis invariants inv=0/11 module=x/crisis name=distribution/nonnegative-outstanding
5:06PM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/can-withdraw
5:06PM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/reference-count
5:06PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/module-account
5:06PM INF asserting crisis invariants inv=4/11 module=x/crisis name=gov/module-account
5:06PM INF asserting crisis invariants inv=5/11 module=x/crisis name=bank/nonnegative-outstanding
5:06PM INF asserting crisis invariants inv=6/11 module=x/crisis name=bank/total-supply
5:06PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
5:06PM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
5:06PM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
5:06PM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
5:06PM INF asserted all invariants duration=1229.311337 height=0 module=x/crisis
5:06PM INF created new capability module=ibc name=ports/transfer
5:06PM INF port binded module=x/ibc/port port=transfer
5:06PM INF claimed capability capability=1 module=transfer name=ports/transfer
5:06PM INF created new capability module=ibc name=ports/icahost
5:06PM INF port binded module=x/ibc/port port=icahost
5:06PM INF claimed capability capability=2 module=icahost name=ports/icahost

Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
```

**Comment by CooleRnax** [comment]
Steps to reproduse:
```
RUN git clone https://github.com/terra-money/core \
&& cd core \
&& git checkout main \
&& make install
```
```
terrad init node_name
curl https://phoenix-genesis.s3.us-west-1.amazonaws.com/penultimate-genesis.json > ~/.terra/config/genesis.json
curl https://network.terra.dev/addrbook.json > ~/.terra/config/addrbook.json
terrad start
```

**Comment by awsdataarchitect** [comment]
#26  see steps here.. u need to update the seeds, persistent peers

**Comment by carangel** [comment]
I tried that :

> terrad tendermint unsafe-reset-all

and that :

> u need to update the seeds, persistent peers 

but still getting :

> 5:36PM INF starting node with ABCI Tendermint in-process
5:36PM INF Starting multiAppConn service impl=multiAppConn module=proxy
5:36PM INF Starting localClient service connection=query impl=localClient module=abci-client
5:36PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
5:36PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
5:36PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
5:36PM INF Starting EventBus service impl=EventBus module=events
5:36PM INF Starting PubSub service impl=PubSub module=pubsub
5:36PM INF Starting IndexerService service impl=IndexerService module=txindex
5:36PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.1
5:36PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
5:37PM INF asserting crisis invariants inv=0/11 module=x/crisis name=staking/module-accounts
5:37PM INF asserting crisis invariants inv=1/11 module=x/crisis name=staking/nonnegative-power
5:37PM INF asserting crisis invariants inv=2/11 module=x/crisis name=staking/positive-delegation
5:37PM INF asserting crisis invariants inv=3/11 module=x/crisis name=staking/delegator-shares
5:37PM INF asserting crisis invariants inv=4/11 module=x/crisis name=gov/module-account
5:37PM INF asserting crisis invariants inv=5/11 module=x/crisis name=bank/nonnegative-outstanding
5:37PM INF asserting crisis invariants inv=6/11 module=x/crisis name=bank/total-supply
5:37PM INF asserting crisis invariants inv=7/11 module=x/crisis name=distribution/nonnegative-outstanding
5:37PM INF asserting crisis invariants inv=8/11 module=x/crisis name=distribution/can-withdraw
5:37PM INF asserting crisis invariants inv=9/11 module=x/crisis name=distribution/reference-count
5:37PM INF asserting crisis invariants inv=10/11 module=x/crisis name=distribution/module-account
5:37PM INF asserted all invariants duration=1242.317341 height=0 module=x/crisis
5:37PM INF created new capability module=ibc name=ports/transfer
5:37PM INF port binded module=x/ibc/port port=transfer
5:37PM INF claimed capability capability=1 module=transfer name=ports/transfer
5:37PM INF created new capability module=ibc name=ports/icahost
5:37PM INF port binded module=x/ibc/port port=icahost
5:37PM INF claimed capability capability=2 module=icahost name=ports/icahost
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

**Comment by CooleRnax** [comment]
> I tried that :
> 
> > terrad tendermint unsafe-reset-all
> 
> and that :
> 
> > u need to update the seeds, persistent peers
> 
> but still getting :
> 
> > 5:36PM INF starting node with ABCI Tendermint in-process
> > 5:36PM INF Starting multiAppConn service impl=multiAppConn module=proxy
> > 5:36PM INF Starting localClient service connection=query impl=localClient module=abci-client
> > 5:36PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
> > 5:36PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
> > 5:36PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
> > 5:36PM INF Starting EventBus service impl=EventBus module=events
> > 5:36PM INF Starting PubSub service impl=PubSub module=pubsub
> > 5:36PM INF Starting IndexerService service impl=IndexerService module=txindex
> > 5:36PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.1
> > 5:36PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
> > 5:37PM INF asserting crisis invariants inv=0/11 module=x/crisis name=staking/module-accounts
> > 5:37PM INF asserting crisis invariants inv=1/11 module=x/crisis name=staking/nonnegative-power
> > 5:37PM INF asserting crisis invariants inv=2/11 module=x/crisis name=staking/positive-delegation
> > 5:37PM INF asserting crisis invariants inv=3/11 module=x/crisis name=staking/delegator-shares
> > 5:37PM INF asserting crisis invariants inv=4/11 module=x/crisis name=gov/module-account
> > 5:37PM INF asserting crisis invariants inv=5/11 module=x/crisis name=bank/nonnegative-outstanding
> > 5:37PM INF asserting crisis invariants inv=6/11 module=x/crisis name=bank/total-supply
> > 5:37PM INF asserting crisis invariants inv=7/11 module=x/crisis name=distribution/nonnegative-outstanding
> > 5:37PM INF asserting crisis invariants inv=8/11 module=x/crisis name=distribution/can-withdraw
> > 5:37PM INF asserting crisis invariants inv=9/11 module=x/crisis name=distribution/reference-count
> > 5:37PM INF asserting crisis invariants inv=10/11 module=x/crisis name=distribution/module-account
> > 5:37PM INF asserted all invariants duration=1242.317341 height=0 module=x/crisis
> > 5:37PM INF created new capability module=ibc name=ports/transfer
> > 5:37PM INF port binded module=x/ibc/port port=transfer
> > 5:37PM INF claimed capability capability=1 module=transfer name=ports/transfer
> > 5:37PM INF created new capability module=ibc name=ports/icahost
> > 5:37PM INF port binded module=x/ibc/port port=icahost
> > 5:37PM INF claimed capability capability=2 module=icahost name=ports/icahost
> > Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain

try this:
curl https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json > ~/.terra/config/genesis.json

**Comment by awsdataarchitect** [comment]
terrad collect-gentxs (copy the gentx files from the genesis-tools repo to ~/.terra/config/gentx)

**Comment by carangel** [comment]
> terrad collect-gentxs

Give that :

> Error: failed to get genesis app state from config: open /home/ubuntu/.terra/config/gentx: no such file or directory

**Comment by carangel** [comment]
> try this: `curl https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json > ~/.terra/config/genesis.json`

I tried also this but still not working

**Comment by CooleRnax** [comment]
I finally made it work

```
terrad init node_name
curl https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json > ~/.terra/config/genesis.json
curl https://network.terra.dev/addrbook.json > ~/.terra/config/addrbook.json
    sed -i -e 's/seeds = \"\"/seeds = "406bcf90a7b29df6ae475a1f94abe04ebde805af@phoenix.seed.stakebin.io:16656,fc608a9a117d8d2302bcd181aec34eec6bb4fa96@terra2-seed.blockpane.com:26656,8efd8248e06aabd553b56766ec2a850999d0861f@exitnode.cereslabs.io:36656,a07cec8341f149ed49f751146728cf81f83764ff@84.244.95.239:26656,cffc34088450d1c33e0c67663386f803bd1359f6@94.130.33.117:26656,b4d3b21747539060b270457437ef1bf99a51c694@terra2.seed.synergynodes.com:26656,f28efad2d76857c2606f00bee014346481734ea0@116.203.29.116:46656,810d1628db9f1db56fa87a93fb6ef809c32d6325@phoenix.seed.terra.btcsecure.io:26656"/g' ~/.terra/config/config.toml
    sed -i -e 's/persistent_peers = \"\"/persistent_peers = "028b5c97ac5a01863d3f263df7a5814247094b18@23.19.122.193:26656,03636a257cd099c4f070166bfa09db1aef2645b8@23.88.73.18:26656,065fd6f49a4a424727433b3a8e3d5945e4935d9c@78.46.68.41:26656,0958d078065391716b30cfcb0c9abb3e86c590fb@0.0.0.0:26656,0b3b323185ce4b7b4fa3c9943ccc1213d64d65be@172.24.138.207:26656,0d7823edd87cb64490a5fcd234bf47864b457704@0.0.0.0:26656,0f1096278efafcf3f0d3bd5b6544e6b8dcc36a0e@206.189.129.195:26656,15d8ae2a5bc80485b5bde6056f98eaf9b0ba1cf4@142.132.147.125:26656,18a22858612e8cd03bf6030ebf9d196679bce286@0.0.0.0:26656,19470214d4c9ad8afce77d95c75c0e7ec1694222@0.0.0.0:26656,19bfe3befd4ce6c95e8559f9d9835253cac4fcfb@121.134.50.135:26656,1e339b9b079bad141bdb3e6cf6ec37a5fefca33a@15.235.54.38:26656,1e5e39efe018876c355cbb81a772668e5ce5e1ea@10.10.2.100:26656,21b040b77ac4d95b26111b22ae5153591cf28d70@37.120.245.45:26656,228eaee658dc4e376aad6f5d4934e5f0b37cf38f@34.250.13.25:26656,24db9dd1ea7ed07dd112fd367d112da8d9dc5240@65.21.127.162:26656,2a13fcdb77af7248f0799cd540a8c27c218586f4@38.242.192.114:26656,2a21138f2036e28ce205454cea919325940a9302@172.31.25.158:26656,2b921acfbaa8c12487766823c706d4c3866153a7@0.0.0.0:26656,2e3f552c41f937f53c6c8c7970d273e2322178e3@192.168.0.46:26656,32685ff3b4114cef3efbf30e541a97d528333dd4@172.24.138.207:26656,352deb885fed9a3901be348934cdb74e7c3e6b65@157.245.155.159:26656,364e9c6008f853dc5c95a14f18ebc7f1edafc269@37.143.129.216:26656,38677bd732f6816b8a293b352f17efb23d2a6c58@65.108.0.165:26656,4f13614ace7ec7d7dffdcf8eb52b8425cc5b9eec@172.31.23.209:26656,5558ee2f258883ffb66ef20b2f0bf20a39834847@88.99.25.180:26656,567d86e117c6b26b435d7fe5a32d91ea94e0e3f0@65.108.230.84:26656,5887b4ec8934a419224ab5d897272bcc53fa8ee9@3.121.197.95:26656,5bf51a2268370a90889574780036918523583096@65.21.204.185:26656,5ee811d2bed9d55c629920ec4269f72e60b8683b@0.0.0.0:26656,643af87bbcc79d40340c4d1e6039d7f0de3d86f1@172.24.138.207:26656,65de9e04f72197e37ee200e078d59339edf0002d@172.31.61.182:26656,69689a1f7f26bff21a4f146305239c6e7ac9b9a9@0.0.0.0:26656,6c5f2ce3bcc54f469dd28e19b8b285062395503d@172.31.3.142:26656,6c6964a217579f18aa38919d184de8ad2bb5a5be@135.181.216.54:26656,6cd405861df27c206c6db39830026b4880005ddb@172.31.34.163:26656,721d21a3566ffd3e198099b7c30d153a0b364bd7@172.31.33.115:26656,7373e44b7e7d768a863e5fdf58d8234c75a893d2@0.0.0.0:26656,75f6fecc2470f0ea31dc1227e62d8c7f35e43deb@172.31.31.148:26656,76f58340d68a11b2952615b86d8b26d697a71c34@192.168.2.125:26656,7ac1c9981bf1ec0830a6c86497039d3e92b0a55b@172.20.10.2:26656,7c694dd3fee3e994a630a6e27adbf9858c37836f@178.128.118.111:26656,7e046a03f9cbf589c1f7223a5e27a09f03f7ba56@172.24.138.207:26656,80f6dab802b25fe0c2f5d95ce88db0022e32a44d@172.31.7.229:26656,810d1628db9f1db56fa87a93fb6ef809c32d6325@195.201.106.133:26656"/g' ~/.terra/config/config.toml
```

**Comment by sascha1337** [comment]
> I finally made it work
> 
> ```
> terrad init node_name
> curl https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json > ~/.terra/config/genesis.json
> curl https://network.terra.dev/addrbook.json > ~/.terra/config/addrbook.json
> sed -i -e 's/seeds = \"\"/seeds = "406bcf90a7b29df6ae475a1f94abe04ebde805af@phoenix.seed.stakebin.io:16656,fc608a9a117d8d2302bcd181aec34eec6bb4fa96@terra2-seed.blockpane.com:26656,8efd8248e06aabd553b56766ec2a850999d0861f@exitnode.cereslabs.io:36656,a07cec8341f149ed49f751146728cf81f83764ff@84.244.95.239:26656,cffc34088450d1c33e0c67663386f803bd1359f6@94.130.33.117:26656,b4d3b21747539060b270457437ef1bf99a51c694@terra2.seed.synergynodes.com:26656,f28efad2d76857c2606f00bee014346481734ea0@116.203.29.116:46656,810d1628db9f1db56fa87a93fb6ef809c32d6325@phoenix.seed.terra.btcsecure.io:26656"/g' ~/.terra/config/config.toml
> sed -i -e 's/persistent_peers = \"\"/persistent_peers = "028b5c97ac5a01863d3f263df7a5814247094b18@23.19.122.193:26656,03636a257cd099c4f070166bfa09db1aef2645b8@23.88.73.18:26656,065fd6f49a4a424727433b3a8e3d5945e4935d9c@78.46.68.41:26656,0958d078065391716b30cfcb0c9abb3e86c590fb@0.0.0.0:26656,0b3b323185ce4b7b4fa3c9943ccc1213d64d65be@172.24.138.207:26656,0d7823edd87cb64490a5fcd234bf47864b457704@0.0.0.0:26656,0f1096278efafcf3f0d3bd5b6544e6b8dcc36a0e@206.189.129.195:26656,15d8ae2a5bc80485b5bde6056f98eaf9b0ba1cf4@142.132.147.125:26656,18a22858612e8cd03bf6030ebf9d196679bce286@0.0.0.0:26656,19470214d4c9ad8afce77d95c75c0e7ec1694222@0.0.0.0:26656,19bfe3befd4ce6c95e8559f9d9835253cac4fcfb@121.134.50.135:26656,1e339b9b079bad141bdb3e6cf6ec37a5fefca33a@15.235.54.38:26656,1e5e39efe018876c355cbb81a772668e5ce5e1ea@10.10.2.100:26656,21b040b77ac4d95b26111b22ae5153591cf28d70@37.120.245.45:26656,228eaee658dc4e376aad6f5d4934e5f0b37cf38f@34.250.13.25:26656,24db9dd1ea7ed07dd112fd367d112da8d9dc5240@65.21.127.162:26656,2a13fcdb77af7248f0799cd540a8c27c218586f4@38.242.192.114:26656,2a21138f2036e28ce205454cea919325940a9302@172.31.25.158:26656,2b921acfbaa8c12487766823c706d4c3866153a7@0.0.0.0:26656,2e3f552c41f937f53c6c8c7970d273e2322178e3@192.168.0.46:26656,32685ff3b4114cef3efbf30e541a97d528333dd4@172.24.138.207:26656,352deb885fed9a3901be348934cdb74e7c3e6b65@157.245.155.159:26656,364e9c6008f853dc5c95a14f18ebc7f1edafc269@37.143.129.216:26656,38677bd732f6816b8a293b352f17efb23d2a6c58@65.108.0.165:26656,4f13614ace7ec7d7dffdcf8eb52b8425cc5b9eec@172.31.23.209:26656,5558ee2f258883ffb66ef20b2f0bf20a39834847@88.99.25.180:26656,567d86e117c6b26b435d7fe5a32d91ea94e0e3f0@65.108.230.84:26656,5887b4ec8934a419224ab5d897272bcc53fa8ee9@3.121.197.95:26656,5bf51a2268370a90889574780036918523583096@65.21.204.185:26656,5ee811d2bed9d55c629920ec4269f72e60b8683b@0.0.0.0:26656,643af87bbcc79d40340c4d1e6039d7f0de3d86f1@172.24.138.207:26656,65de9e04f72197e37ee200e078d59339edf0002d@172.31.61.182:26656,69689a1f7f26bff21a4f146305239c6e7ac9b9a9@0.0.0.0:26656,6c5f2ce3bcc54f469dd28e19b8b285062395503d@172.31.3.142:26656,6c6964a217579f18aa38919d184de8ad2bb5a5be@135.181.216.54:26656,6cd405861df27c206c6db39830026b4880005ddb@172.31.34.163:26656,721d21a3566ffd3e198099b7c30d153a0b364bd7@172.31.33.115:26656,7373e44b7e7d768a863e5fdf58d8234c75a893d2@0.0.0.0:26656,75f6fecc2470f0ea31dc1227e62d8c7f35e43deb@172.31.31.148:26656,76f58340d68a11b2952615b86d8b26d697a71c34@192.168.2.125:26656,7ac1c9981bf1ec0830a6c86497039d3e92b0a55b@172.20.10.2:26656,7c694dd3fee3e994a630a6e27adbf9858c37836f@178.128.118.111:26656,7e046a03f9cbf589c1f7223a5e27a09f03f7ba56@172.24.138.207:26656,80f6dab802b25fe0c2f5d95ce88db0022e32a44d@172.31.7.229:26656,810d1628db9f1db56fa87a93fb6ef809c32d6325@195.201.106.133:26656"/g' ~/.terra/config/config.toml
> ```

thx helped

**Comment by carangel** [comment]
> I finally made it work
> 
> ```
> terrad init node_name
> curl https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json > ~/.terra/config/genesis.json
> curl https://network.terra.dev/addrbook.json > ~/.terra/config/addrbook.json
> sed -i -e 's/seeds = \"\"/seeds = "406bcf90a7b29df6ae475a1f94abe04ebde805af@phoenix.seed.stakebin.io:16656,fc608a9a117d8d2302bcd181aec34eec6bb4fa96@terra2-seed.blockpane.com:26656,8efd8248e06aabd553b56766ec2a850999d0861f@exitnode.cereslabs.io:36656,a07cec8341f149ed49f751146728cf81f83764ff@84.244.95.239:26656,cffc34088450d1c33e0c67663386f803bd1359f6@94.130.33.117:26656,b4d3b21747539060b270457437ef1bf99a51c694@terra2.seed.synergynodes.com:26656,f28efad2d76857c2606f00bee014346481734ea0@116.203.29.116:46656,810d1628db9f1db56fa87a93fb6ef809c32d6325@phoenix.seed.terra.btcsecure.io:26656"/g' ~/.terra/config/config.toml
> sed -i -e 's/persistent_peers = \"\"/persistent_peers = "028b5c97ac5a01863d3f263df7a5814247094b18@23.19.122.193:26656,03636a257cd099c4f070166bfa09db1aef2645b8@23.88.73.18:26656,065fd6f49a4a424727433b3a8e3d5945e4935d9c@78.46.68.41:26656,0958d078065391716b30cfcb0c9abb3e86c590fb@0.0.0.0:26656,0b3b323185ce4b7b4fa3c9943ccc1213d64d65be@172.24.138.207:26656,0d7823edd87cb64490a5fcd234bf47864b457704@0.0.0.0:26656,0f1096278efafcf3f0d3bd5b6544e6b8dcc36a0e@206.189.129.195:26656,15d8ae2a5bc80485b5bde6056f98eaf9b0ba1cf4@142.132.147.125:26656,18a22858612e8cd03bf6030ebf9d196679bce286@0.0.0.0:26656,19470214d4c9ad8afce77d95c75c0e7ec1694222@0.0.0.0:26656,19bfe3befd4ce6c95e8559f9d9835253cac4fcfb@121.134.50.135:26656,1e339b9b079bad141bdb3e6cf6ec37a5fefca33a@15.235.54.38:26656,1e5e39efe018876c355cbb81a772668e5ce5e1ea@10.10.2.100:26656,21b040b77ac4d95b26111b22ae5153591cf28d70@37.120.245.45:26656,228eaee658dc4e376aad6f5d4934e5f0b37cf38f@34.250.13.25:26656,24db9dd1ea7ed07dd112fd367d112da8d9dc5240@65.21.127.162:26656,2a13fcdb77af7248f0799cd540a8c27c218586f4@38.242.192.114:26656,2a21138f2036e28ce205454cea919325940a9302@172.31.25.158:26656,2b921acfbaa8c12487766823c706d4c3866153a7@0.0.0.0:26656,2e3f552c41f937f53c6c8c7970d273e2322178e3@192.168.0.46:26656,32685ff3b4114cef3efbf30e541a97d528333dd4@172.24.138.207:26656,352deb885fed9a3901be348934cdb74e7c3e6b65@157.245.155.159:26656,364e9c6008f853dc5c95a14f18ebc7f1edafc269@37.143.129.216:26656,38677bd732f6816b8a293b352f17efb23d2a6c58@65.108.0.165:26656,4f13614ace7ec7d7dffdcf8eb52b8425cc5b9eec@172.31.23.209:26656,5558ee2f258883ffb66ef20b2f0bf20a39834847@88.99.25.180:26656,567d86e117c6b26b435d7fe5a32d91ea94e0e3f0@65.108.230.84:26656,5887b4ec8934a419224ab5d897272bcc53fa8ee9@3.121.197.95:26656,5bf51a2268370a90889574780036918523583096@65.21.204.185:26656,5ee811d2bed9d55c629920ec4269f72e60b8683b@0.0.0.0:26656,643af87bbcc79d40340c4d1e6039d7f0de3d86f1@172.24.138.207:26656,65de9e04f72197e37ee200e078d59339edf0002d@172.31.61.182:26656,69689a1f7f26bff21a4f146305239c6e7ac9b9a9@0.0.0.0:26656,6c5f2ce3bcc54f469dd28e19b8b285062395503d@172.31.3.142:26656,6c6964a217579f18aa38919d184de8ad2bb5a5be@135.181.216.54:26656,6cd405861df27c206c6db39830026b4880005ddb@172.31.34.163:26656,721d21a3566ffd3e198099b7c30d153a0b364bd7@172.31.33.115:26656,7373e44b7e7d768a863e5fdf58d8234c75a893d2@0.0.0.0:26656,75f6fecc2470f0ea31dc1227e62d8c7f35e43deb@172.31.31.148:26656,76f58340d68a11b2952615b86d8b26d697a71c34@192.168.2.125:26656,7ac1c9981bf1ec0830a6c86497039d3e92b0a55b@172.20.10.2:26656,7c694dd3fee3e994a630a6e27adbf9858c37836f@178.128.118.111:26656,7e046a03f9cbf589c1f7223a5e27a09f03f7ba56@172.24.138.207:26656,80f6dab802b25fe0c2f5d95ce88db0022e32a44d@172.31.7.229:26656,810d1628db9f1db56fa87a93fb6ef809c32d6325@195.201.106.133:26656"/g' ~/.terra/config/config.toml
> ```

You're my savior
