### ISSUE TITLE
Terra Classic IBC closed/suspended...

### ISSUE THREAD

**Issue by pteczar** [terra-money/core#44]
Hey There,

I tried to transfer my Osmo & Atom from Terra Classic to Osmosis and Cosmos, but IBC channels were suspended. Can someone solve this? Or is there another way of doing that? 

I did everything correctly, used the https://classic-bridge.terra.money/ address, selected the correct classic chain, and the transfer is not available.

Please let me know when this is solved.
Best,
PT

**Comment by awsdataarchitect** [comment]
This is wrong repo. Use classic core repo

**Comment by pteczar** [comment]
ok, will do
