### ISSUE TITLE
Create validator error.

### ISSUE THREAD

**Issue by oneusdt** [terra-money/core#45]
terrad tx staking create-validator \
> --pubkey=$(terrad tendermint show-validator) \
> --amount=1000000uluna \
> --from="abitration" \
> --commission-rate="0.20" \
> --commission-max-rate="1.00" \
> --commission-max-change-rate="0.01" \
> --min-self-delegation="1" \
> --moniker="Abitration" \
> --chain-id="phoenix-1" \
> --gas=auto \
> --gas-adjustment=1.25 \
> --gas-prices=0.15uluna \
> --node= tcp://127.0.0.1:26647 
Enter keyring passphrase:
Error: invalid character 'o' looking for beginning of value
Usage:

**Comment by awsdataarchitect** [comment]
Remove space in node parameter =

**Comment by oneusdt** [comment]
@awsdataarchitect Thank u
