### ISSUE TITLE
[BUG] REST API GET /txs with tx.minheight & tx.maxheight parameters raised 504 error

### ISSUE THREAD

**Issue by tokusyu** [terra-money/core#470]
**Describe the bug**
REST API "GET /txs" with tx.minheight & tx.maxheight parameters didn't return queried values but 504: Gateway time-out error on swagger.
_
**To Reproduce**
At https://lcd.terra.dev/swagger-ui/#/Transactions/get_txs
execute it with parameters like tx.minheight:10000 and tx.maxheight:10000

curl -X GET "https://myhost:1317/txs?tx.minheight=10000&tx.maxheight=10000" -H "accept: application/json"
above query on my node returned a result like below:
curl: (52) Empty reply from server

**Context & versions**
swagger: current version as of May. 2nd 2021.(ver.3.0)
my node: 0.4.6 (got from docker hub: terramoney/core:stable)

**Comment by YunSuk-Yeo** [comment]
Thanks for reporting the problem. Current version of Tendermint takes so long time to conduct `/txs` query with `minheight`/`maxheight`. 

We will keep focusing on this problem with CosmosSDK team.
