### ISSUE TITLE
Genesis supply is incorrect error

### ISSUE THREAD

**Issue by ZeusStaking** [terra-money/core#48]
Using v2.0.0 to spin up a validator node, gives following error - 

`genesis supply is incorrect, expected 1000000000000000uluna, got 1000000001000000uluna`

Sequence of commands followed - 

`terrad keys add zeus2_validator`
`terrad add-genesis-account $(terrad keys show zeus2_validator -a) 1000000uluna `
`terrad validate-genesis`

`Error: error validating genesis file /home/zeus2/.terra/config/genesis.json: genesis supply is incorrect, expected 1000000000000000uluna, got 1000000001000000uluna`

I believe something is wrong with either validate-genesis logic or something else. I'm using genesis file - https://terra-pub.s3.amazonaws.com/genesis.json (the latest one which was mentioned in discord, developer announcements).

**Comment by awsdataarchitect** [comment]
Follow steps in this

https://github.com/terra-money/core/issues/41#issuecomment-1140495581

**Comment by ZeusStaking** [comment]
Thanks, but that didn't work unfortunately, still got the same error. Do I need to run staking command `terrad tx staking create-validator` before I try to run add-genesis-account? Also I'm assuming I don't really need to have `terrad start` running in tmux or as a service at this point yet, correct? I would appreciate any help you can provide, been stuck on this error for 2 days now. Thank you!

**Comment by awsdataarchitect** [comment]
you dont do this step
terrad add-genesis-account $(terrad keys show zeus2_validator -a) 1000000uluna
just redownload the genesis file

**Comment by ZeusStaking** [comment]
Thanks. The issue I'm having is that I'm trying to create a validator and that's not working (error mentioned above). If I try to download fresh genesis file, then my node will run with `terrad start` just fine. But as soon as I stop the node to create a validator, I get the error mentioned. 
So, I don't add genesis accounts to create validator? I was following [this guide](http://docs.terra.money/docs/full-node/run-a-full-terra-node/join-a-network.html)
Thanks again for your help.

**Comment by awsdataarchitect** [comment]
adding genesis account is for testnet... you can create validator with you terra address once you have the latest block synced up to your local chain. most likely your account is not part of the blockchain when u are doing create validator..

you can verify this by querying
 terrad query bank balances terra1axxxxx

**Comment by ZeusStaking** [comment]
Aah ok, I didn't know that. My node is currently syncing. So once it's at the latest block, what do I do next? Follow [this guide](http://docs.terra.money/docs/full-node/manage-a-terra-validator/set-up-validator.html)? 

Also, please leave your wallet address, I want to send some tip for helping out. Actually I'm on my 3rd VM right now lol, scrapped last 2 VMs because couldn't move past this step. I even at one point got one of my node synced up to latest block, but when I would try to look up in Terra Station, my validator wasn't showing up. Thanks.

**Comment by ZeusStaking** [comment]
Thank you very much, tip sent. I'll run `terrad tx staking create-validator` after my node is at latest block and if all good, I'll close this issue. I appreciate your help, cannot thank you enough!

**Comment by ZeusStaking** [comment]
Sorry forgot to ask, at what point I generate `gentx` command for my account? Or I don't need to do that and `terrad tx staking create-validator` should do that? I'm just wondering how do I broadcast my validator details, like what is moniker, details, commission-rate and all? Thanks again.

**Comment by awsdataarchitect** [comment]
thanks for the generous tip....much appreciated... you can simply run the terrad tx staking create-validator without the gentx which is actually to create genesis transaction.. here is example.. you can specify the commission rate etc while creating your validator

terrad tx staking create-validator \
--pubkey=$(terrad tendermint show-validator)   --amount=3uluna\
    --from="validator"\
    --commission-rate="0.05"\
    --commission-max-rate="0.50"\
    --commission-max-change-rate="0.01"\
    --min-self-delegation="1"\
    --moniker="waltsoft.money"\
    --chain-id="phoenix-1"\  
     --gas=auto --gas-adjustment=1.25 --gas-prices=0.15uluna \
--node= tcp://127.0.0.1:26647

**Comment by ZeusStaking** [comment]
Ok, thank you very much. I'll give it a try and if all good, close this issue. Once again much appreciated your help 🙏

**Comment by ZeusStaking** [comment]
Hi, I'm sorry, it seems issues just don't want to go away. So my node is all caught up and balance is reflecting accurately too. Now when I run `create-validator` command, I'm getting `Error: zeus2_validator.info: key not found`. I had run keys add command with this name `terrad keys add zeus2_validator`, so I'm not sure what's wrong. Is this looking for some other name? Any insight would be helpful. Thank you.

**Comment by awsdataarchitect** [comment]
Yea maybe the keyhash file is not present. Just run keys add "validator key name" --recover and then it should work

**Comment by ZeusStaking** [comment]
OMG, can't believe that work, lol. Thank you very much once again. As appreciation, sent additional small tip. Much appreciated. I'll mark this issue closed now. Thanks.
