### ISSUE TITLE
Contract ownership

### ISSUE THREAD

**Issue by invis87** [terra-money/core#487]
I found that contract developers store `owner` in contract State. But why we need to store it manually? I think it is part of structure `Env.ContractInfo`
```rust
pub struct ContractInfo {
    pub address: Addr,
}
```
How about to add it there?
I post similar issue to cosmwasm, [here](https://github.com/CosmWasm/cosmwasm/issues/926)
But in Terra there is more:

---

Also, you can send `MsgUpdateContractOwner` to contract. And that message will be processed by blockchain node, not by wasm code! And there is no way to catch that event from within contract! I think that a big mistake - you can store `owner` in contract state, but you can't change it manually, and you can't be sure that it is actual owner... :(

Probably we can add some obligatory handler to contracts, that will be triggered when `MsgUpdateContractOwner` processed and call that trigger from handler:
```go
		case MsgUpdateContractOwner:
			return handleUpdateContractOwner(ctx, k, msg)
```

**Comment by MSNTCS** [comment]
@invis87 Thank you for reaching out. There are two concepts: one is contract `admin` and the other is contract `owner`. The contract `owner` can migrate the contract and the contract `admin` is a state variable that is allowed during contract instantiation or by some messages to handle some operations and state changes. They can be the same but their functionality is different. `admin` is a central point of authority for contracts that might not be applicable for all cases and `owner` is useful as long as the contract is `migratable`.

**Comment by invis87** [comment]
@MSNTCS okey, thanks. But now it is impossible to get `owner` from contract code, if it was changed through `MsgUpdateContractOwner`. I think in DeFi it is really important - who can change the contract code. So I am ask for adding obligatory handler to wasm contracts, something like `owner_changed`. Node will trigger that handler after:
```go
case MsgUpdateContractOwner:
    return handleUpdateContractOwner(ctx, k, msg)
```

**Comment by MSNTCS** [comment]
@invis87 `owner` is queriable by the address of a contract. You can check the owner using `lcd`. The following link can help you access the owner. It is linked to the contract address. https://lcd.terra.dev/wasm/contracts/${CONTRACT_ADDRESS}

**Comment by invis87** [comment]
@MSNTCS thanks for url. But you can't check the `owner` from within the contract!

**Comment by YunSuk-Yeo** [comment]
@invis87 I understand what you are saying. If the cosmwasm added the querier interface, then we can easily add that query interface.

I think that is good query endpoint for contract, they are also glad to implement that.
