### ISSUE TITLE
addrbook.json 404 not found

### ISSUE THREAD

**Issue by airstring** [terra-money/core#49]
https://network.terra.dev/addrbook.json ,  page cannot be accessed

**Comment by airstring** [comment]
ok!

**Comment by airstring** [comment]
> you can skip this step.. once your node is running it will automatically download the addresses to the address book

By the way, what is the address of the block browser, something like this address ： https://terra.stake.id/#/

**Comment by awsdataarchitect** [comment]
I use LCD API for now
https://phoenix-lcd.terra.dev
