### ISSUE TITLE
[BUG] Documentation bug in market module spec

### ISSUE THREAD

**Issue by KushGoyal** [terra-money/core#495]
In the market module [docs](https://github.com/terra-money/core/blob/master/x/market/spec/01_concepts.md#Virtual-Liquidity-Pools) the formula for `LunaPool` is incorrect in context of the `CP` formula.

```
CP = TerraPool * LunaPool * LunaPice / SDRPrice
```
In the above formula the `LunaPool` variable means amount of `Luna` in the Pool.

Now in the formula for Virtual Liquidity Pools `LunaPool` variable is used again. But it means something different here.

```
TerraPool = BasePool + delta
LunaPool = (BasePool * BasePool) / TerraPool
```

Here `LunaPool` means the total value of pool in Terra terms. So formula should be updated for `LunaPool` variable to have the same meaning as before. The correct formula is:

```
TerraPool = BasePool + delta
LunaPool * LunaPice / SDRPrice = (BasePool * BasePool) / TerraPool
LunaPool = (SDRPrice / LunaPrice) * (BasePool * BasePool) / TerraPool
```

**Comment by hanjukim** [comment]
Thank you for addressing this. The documentation has been updated.
