### ISSUE TITLE
[BUG] unknown field "proofOps" in types.ResponseQuery with localterra bombay

### ISSUE THREAD

**Issue by movaldivia** [terra-money/core#515]
**Describe the bug**

Same problem as described here: https://github.com/terra-money/core/issues/514

`~/my-first-contract/artifacts$ terracli tx wasm store my_first_contract.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block
Enter keyring passphrase:
ERROR: ABCIQuery: error unmarshalling result: unknown field "proofOps" in types.ResponseQuery
`

**Given Solution**
The given solution was to run `git clone --branch v0.4.1 --depth 1 https://github.com/terra-money/localterra.git` but I want to use it with localterra last version with bombay

Don't know if this is a localterra or core issue

Any solution?

**Comment by YunSuk-Yeo** [comment]
there is no terracli anymore, please use terrad 

all terracli subcommands are merged into terrad

```
$ terrad tx wasm ~~~
```

**Comment by ilovejs** [comment]
tx not exists for terrad... 

source:
```
https://docs.terra.money/contracts/tutorial/implementation.html#optimizing-your-build
```

**Comment by hanjukim** [comment]
checkout v0.5.0-rc0 and re-compile the binary
