### ISSUE TITLE
 Wasm contract doesn't have required export

### ISSUE THREAD

**Issue by bond-igor** [terra-money/core#521]
**Describe the bug**

I'm prepare a simple contract for uploading using command:
`cargo wasm`
`docker run --rm -v "$(pwd)":/code   --mount type=volume,source="$(basename "$(pwd)")_cache",target=/code/target   --mount type=volume,source=registry_cache,target=/usr/local/cargo/registry   cosmwasm/rust-optimizer:0.10.9`

Using uploading command:
`terrad tx wasm store contract_five.wasm --from test1 --chain-id=localterra --gas=auto --fees=100000uluna --broadcast-mode=block`

And getting an error on it: 
`Error: rpc error: code = InvalidArgument desc = failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract doesn't have required export: "instantiate". Exports required by VM: ["interface_version_6", "instantiate", "allocate", "deallocate"]. Contract version too old for this VM?: store wasm contract failed: invalid request`

**Context & versions**
Contract dependencies:
`cosmwasm-std = { version = "0.15.2" }
cosmwasm-storage = { version = "0.15.2" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = { version = "1.0.24" }`

Environment:
'rustc --version
rustc 1.53.0 (53cb7b09b 2021-06-17)
cargo --version
cargo 1.53.0 (4369396ce 2021-04-27)
rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)

LocalTerra main branch
'
I will be glad for any suggestions to resolve this issue

**Comment by YunSuk-Yeo** [comment]
Did you define and export `instantiate` function?

**Comment by bond-igor** [comment]
Thank you. It was a problem with my contract instantiate function name.
