### ISSUE TITLE
latest terracli with terrad returns  ABCIQuery : error unmarshalling result : unknown field "proofOps" in types.ResponseQuery

### ISSUE THREAD

**Issue by ssenathi** [terra-money/core#522]
**Describe the bug**
Latest build of terracli , 

Version  0.4.6-5-g5860232

**To Reproduce**
Build latest version of terrad and terracli .  Start localterrra and do a query / upload contract using terracli

terracli query account <address>

or
terracli tx wasm stroe test_contract.wasm -from test1 --chain-id=localterra --fees=1000000uluna --broadcast-mod=block

i get the following error

ABCIQuery : error unmarshalling result : unknown field "proofOps" in types.ResponseQuery

**Context & versions**

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by YunSuk-Yeo** [comment]
hmm latest version of LocalTerra use v0.5.0-rc0 release of core and terracli is not used anymore.

please try with `terrad` like 
```
$ terrad query account
$ terrad tx wasm store
```

**Comment by ssenathi** [comment]
Hi

I tried terrad and it doesnt even have command called "query" .

**Comment by ssenathi** [comment]
When i ran terrad --help it gave the following, There is no query or tx command for terrad

Terra Daemon (server)

Usage:
  terrad [command]

Available Commands:
  init                Initialize private validator, p2p, genesis, and application configuration files
  collect-gentxs      Collect genesis txs and output a genesis.json file
  gentx               Generate a genesis tx carrying a self delegation
  validate-genesis    validates the genesis file at the default location or at the location passed as an arg
  add-genesis-account Add genesis account to genesis.json
  testnet             Initialize files for a Terrad testnet
  replay              Replay terra transactions
  debug               Tool for helping with debugging your application
  start               Run the full node
  unsafe-reset-all    Resets the blockchain database, removes address book files, and resets priv_validator.json to the genesis state

  tendermint          Tendermint subcommands
  export              Export state to JSON

  version             Print the app version
  help                Help about any command

Flags:
  -h, --help                     help for terrad
      --home string              directory for config and data (default "/home/ssenathi/.terrad")
      --inv-check-period uint    Assert registered invariants every N blocks
      --log_level string         Log level (default "main:info,state:info,*:error")
      --trace                    print out full stack trace on errors
      --tx-gas-hard-limit uint   Transaction hard cap to prevent spamming attack (default 30000000)

Use "terrad [command] --help" for more information about a command.

**Comment by ru-chiang** [comment]
hey @ssenathi 
If you're running the latest `LocalTerra`, you will need to rebuild your `terrad` and `terracli` to v5.
You can do something like
```
git clone https://github.com/terra-money/core
cd core
git checkout v0.5.0-rc0
make install
```
Then your `terrad` should not give you error anymore :)
