### ISSUE TITLE
[BUG] (v0.5.x) nil pointer dereference on smart contract custom wasm event

### ISSUE THREAD

**Issue by nzaharov** [terra-money/core#528]
**Describe the bug**
Executing a contract which creates a custom wasm event (introduced in Cosmwasm 0.15.0) causes a runtime panic.
Exception seems to originate from x/wasm/types/connector.go.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/45366595/128846637-175612ad-ee6f-41be-a1a8-9faa1964f41b.png)

**To Reproduce**
Create and execute a smart contract whose handler returns a `Response` with one `Event`, no attributes, no messages and no data.

**Context & versions**
Reproduced on LocalTerra bombay (Cosmwasm 0.15.0, cosmos-sdk 0.43.0-rc0) and bombay-next branches  (Cosmwasm 0.16.0, cosmos-sdk 0.43.0-rc3).

**Comment by YunSuk-Yeo** [comment]
Thanks a lot for reporting. 

let me fix this @nzaharov
