### ISSUE TITLE
Unexpected LCD response when querying propoals proposer

### ISSUE THREAD

**Issue by etienne-napoleone** [terra-money/core#53]
Unexpected LCD response when querying proposals proposers.
On pisco there are no proposals at the moment:

doesn't exist `https://pisco-lcd.terra.dev/gov/proposals/1`
doesn't exist `https://pisco-lcd.terra.dev/gov/proposals/8`
doesn't exist `https://pisco-lcd.terra.dev/gov/proposals/9`

but yet, up to proposal id 8, the `/gov/proposals/{proposal_id}/proposer` endpoint returns a proposer:

has proposer `https://pisco-lcd.terra.dev/gov/proposals/1/proposer`
has proposer `https://pisco-lcd.terra.dev/gov/proposals/8/proposer`
doesn't have a proposer `https://pisco-lcd.terra.dev/gov/proposals/9/proposer`

**Comment by etienne-napoleone** [comment]
Some more weird stuff

checked the proposer for proposal 1, `terra1mzhc9gvfyh9swxed7eaxn2d6zzc3msgftk4w9e`, and he did submit a tx for a proposal: https://finder.terra.money/testnet/tx/F61A5D8836D9DC3F2FB43E429EFE4B9508011380033452D42864F2AEE4DC4CF6 which should have gotten id 1
so the problem might be the other way around, why does the gov module doesn't return anything for this proposal?

I checked with the non deprecated endpoints and same result

**Comment by YunSuk-Yeo** [comment]
The gov module delete finished proposals, but I can still return query proposal with deprecated endpoint because it use tx index query https://github.com/cosmos/cosmos-sdk/blob/f2d94445c0f5f52cf5ed999b81048b575de94964/x/gov/client/rest/query.go#L151.
