### ISSUE TITLE
Columbus-5 upgrade time

### ISSUE THREAD

**Issue by vae520283995** [terra-money/core#532]
Can you tell me the estimated upgrade time?

**Comment by vae520283995** [comment]
@hanjukim hi

**Comment by hanjukim** [comment]
There will be an official announcement

**Comment by vae520283995** [comment]
> There will be an official announcement

@hanjukim 
I am an exchange developer, our exchange will integrate luna token, upgrade to Columbus-5 rest api will be deprecated. Is the transaction structure like cosmos will deprecate amino and use Protobuf?

**Comment by vae520283995** [comment]
We have integrated atom (cosmos), if terra will be upgraded in the future, I will consider waiting for terra to upgrade first, and then integrate

**Comment by hanjukim** [comment]
We won't deprecate existing rest api from columbus-4, but estimate fee endpoint has been changed.

**Comment by vae520283995** [comment]
> We won't deprecate existing rest api from columbus-4, but estimate fee endpoint has been changed.
> See: https://github.com/terra-money/mainnet/wiki/Columbus-5-Wallet-Migration-Guide

Understand, thank you, will the encoding of rawtransaction change? https://docs.cosmos.network/v0.43/core/encoding.html

**Comment by YunSuk-Yeo** [comment]
Yes, we are also following their updates. you can still use /txs/encode /txs/decode endpoints of rest-server for raw transaction encoding and decoding.
