### ISSUE TITLE
[FEATURE] Cosmos FeeGrant for upcoming release

### ISSUE THREAD

**Issue by 0xkyro** [terra-money/core#534]
**Problem definition**

Cosmos SDK 0.43 includes a FeeGrant module which might be useful for applications. In particular, `x/feegrant` allows one account, the "granter" to grant another account, the "grantee" an allowance to spend the granter's account balance for fees within certain well-defined limits. It solves the problem of signing accounts needing to possess a sufficient balance in order to pay fees.

Will this module be made available in the upcoming upgrade?

https://docs.cosmos.network/master/modules/feegrant/
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.43.0

**Comment by YunSuk-Yeo** [comment]
@0xkyro thanks for reaching out, we also supports feegrant feature :)
