### ISSUE TITLE
AddrBook.json for Terra Classic (Columbus-5)

### ISSUE THREAD

**Issue by JSilvermanCohen** [terra-money/core#54]
Is there somewhere to get the `addrbook.json` file for columbus-5?  I would like to download the entire columbus-5 (and maybe collumbus-4) chains because reasons.  I have found a `genesis.json` file to use but cannot find an addrbook.  Anyone have a workaround?  (Or have a copy of the file they could share that I can copy?)

Thanks

**Comment by emidev98** [comment]
Hello, please fin the following addressbook for columbus https://networks.mcontrol.ml/columbus/addrbook.json

**Comment by pronvis** [comment]
May I ask for the same?
https://networks.mcontrol.ml/columbus/addrbook.json isnt working anymore
