### ISSUE TITLE
Launching a new node on my Ubuntu 20.04 LTS home server results in a Go panic

### ISSUE THREAD

**Issue by obnoxiousish** [terra-money/core#541]
I have setup go many different ways and used many different tutorials to setup a terrad node for Columbus-4 and I am consistently being hit with the error: 

"panic: Any JSON doesn't have '@type'"

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc001134c40, 0xc06fe58000, 0x151f91eb, 0x151fa000, 0x26ee600, 0xc000cbbe00)
        github.com/cosmos/cosmos-sdk@v0.43.0/codec/proto_codec.go:176 +0x98
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x26e46d8, 0xc0013efc90, 0x271ad58, 0xc001134c40, 0x271ad58, 0xc001134c40, 0xc0001e17b0, 0x26e46d8, 0xc0013efd00, 0x26e4728, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/x/auth/module.go:143 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000c8a2a0, 0x2703268, 0xc0000520d0, 0x271d940, 0xc000cbbd80, 0x0, 0x0, 0xc00051a1c0, 0xa, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/types/module/module.go:306 +0x2b5
github.com/terra-money/core/app.(*TerraApp).InitChainer(0xc0010a1b00, 0x2703268, 0xc0000520d0, 0x271d940, 0xc000cbbd80, 0x0, 0x0, 0xc00051a1c0, 0xa, 0x0, ...)
        github.com/terra-money/core/app/app.go:607 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00016ed00, 0x0, 0xed70a961a, 0x0, 0xc00051a1c0, 0xa, 0xc0014aa240, 0xc0001ae580, 0x37, 0x37, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/baseapp/abci.go:62 +0x315
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0014b2ba0, 0x0, 0xed70a961a, 0x0, 0xc00051a1c0, 0xa, 0xc0014aa240, 0xc0001ae580, 0x37, 0x37, ...)
        github.com/tendermint/tendermint@v0.34.12/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc00140e980, 0x0, 0xed70a961a, 0x0, 0xc00051a1c0, 0xa, 0xc0014aa240, 0xc0001ae580, 0x37, 0x37, ...)
        github.com/tendermint/tendermint@v0.34.12/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc000ee5c18, 0xb, 0x0, 0x1faa8a2, 0x7, 0xc00051a1c0, 0xa, 0x1, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.12/consensus/replay.go:319 +0x655
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000ee5c18, 0x271eba8, 0xc000df0000, 0x1f4, 0xc00137a820)
        github.com/tendermint/tendermint@v0.34.12/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x271a818, 0xc00140e6e0, 0xb, 0x0, 0x1faa8a2, 0x7, 0xc00051a1c0, 0xa, 0x1, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.12/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0000f0b40, 0x26f82c0, 0xc000247680, 0xc001403e80, 0x26c0360, 0xc00000ede0, 0xc001403ef0, 0x2494328, 0xc001403fe0, 0x2703f18, ...)
        github.com/tendermint/tendermint@v0.34.12/node/node.go:715 +0x20e5
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc0011d2e60, 0x0, 0x0, 0x0, 0x2728278, 0xc000156270, 0x0, 0x0, 0x270d610, 0xc001134c40, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:263 +0x685
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00119b180, 0xc0011d2fa0, 0x0, 0x2, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:129 +0x209
github.com/spf13/cobra.(*Command).execute(0xc00119b180, 0xc0011d2f80, 0x2, 0x2, 0xc00119b180, 0xc0011d2f80)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x472
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e1fb80, 0x0, 0x0, 0xc0010abe20)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc000e1fb80, 0xc0010abe20, 0xe, 0x2720958, 0xc001134c40)
        github.com/cosmos/cosmos-sdk@v0.43.0/server/cmd/execute.go:36 +0x285
main.main()
        github.com/terra-money/core/cmd/terrad/main.go:15 +0x45

**Comment by janojan** [comment]
I'm running into the same issue, ubuntu 20.04, v0.5.2, new installation, same error.

**Comment by obnoxiousish** [comment]
I was able to get a old version running on a old version of go the very
first time I set it up I got fed up troubleshooting for hours with the new
stuff and gave up to make this issue but you might have some luck using
like Go 1.14 or 1.15 or whatever it is i think 1.16 is the newest? If it
still doesn’t work I imagine it’s gotta be some simple bug somewhere in the
terra core

**Comment by janojan** [comment]
I was able to get it working, it looks like the I was running v0.5.2 which is not meant to be used for Columbus-4, but Columbus-5. 
When I tried with v0.4.6 it works fine.

**Comment by obnoxiousish** [comment]
Ohhhhhhh I was wondering this at one point and didnt bother trying. Thanks.

**Comment by obnoxiousish** [comment]
Closing as 0.5.2 was being used for Colombus-4 but it is for Colombus-5, switch to v0.4.6
