### ISSUE TITLE
[BUG] Startup node error

### ISSUE THREAD

**Issue by wangwen1024** [terra-money/core#547]
**Describe the bug**
Startup node error and Error message:

4:34PM INF starting ABCI with Tendermint
4:35PM INF Starting multiAppConn service impl=multiAppConn module=proxy
4:35PM INF Starting localClient service connection=query impl=localClient module=abci-client
4:35PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
4:35PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
4:35PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
4:35PM INF Starting EventBus service impl=EventBus module=events
4:35PM INF Starting PubSub service impl=PubSub module=pubsub
4:35PM INF Starting IndexerService service impl=IndexerService module=txindex
4:35PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.5.2-1-g4541aa1
4:35PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0

panic: Any JSON doesn't have '@type'

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0xc0011a4b40, 0xc070958000, 0x151f91eb, 0x151fa000, 0x2703880, 0xc00020c900)
        github.com/cosmos/cosmos-sdk@v0.43.0/codec/proto_codec.go:176 +0x8a
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis(0x26f7000, 0xc000f65800, 0x2735e60, 0xc0011a4b40, 0x2735e60, 0xc0011a4b40, 0xc000143928, 0x26f7000, 0xc000f65870, 0x26f7080, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/x/auth/module.go:143 +0xa4
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(0xc000e782a0, 0x271d200, 0xc000050088, 0x2738b60, 0xc00020c880, 0x0, 0x0, 0xc001320110, 0xa, 0x0, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/types/module/module.go:306 +0x2b5
github.com/terra-money/core/app.(*TerraApp).InitChainer(0xc001101b00, 0x271d200, 0xc000050088, 0x2738b60, 0xc00020c880, 0x0, 0x0, 0xc001320110, 0xa, 0x0, ...)
        github.com/terra-money/core/app/app.go:607 +0x170
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000deeb60, 0x0, 0xed70a961a, 0x0, 0xc001320110, 0xa, 0xc0000e0a00, 0xc0001a2000, 0x37, 0x37, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/baseapp/abci.go:62 +0x358
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000e595c0, 0x0, 0xed70a961a, 0x0, 0xc001320110, 0xa, 0xc0000e0a00, 0xc0001a2000, 0x37, 0x37, ...)
        github.com/tendermint/tendermint@v0.34.12/abci/client/local_client.go:266 +0x115
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xc001362c50, 0x0, 0xed70a961a, 0x0, 0xc001320110, 0xa, 0xc0000e0a00, 0xc0001a2000, 0x37, 0x37, ...)
        github.com/tendermint/tendermint@v0.34.12/proxy/app_conn.go:77 +0x78
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc0013bfe30, 0xb, 0x0, 0x1fc820b, 0x7, 0xc001320110, 0xa, 0x1, 0x0, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.12/consensus/replay.go:319 +0x695
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0013bfe30, 0x2739e60, 0xc0001b40d0, 0x1, 0x1)
        github.com/tendermint/tendermint@v0.34.12/consensus/replay.go:268 +0x478
github.com/tendermint/tendermint/node.doHandshake(0x2735960, 0xc001362300, 0xb, 0x0, 0x1fc820b, 0x7, 0xc001320110, 0xa, 0x1, 0x0, ...)
        github.com/tendermint/tendermint@v0.34.12/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc0011fca00, 0x2710980, 0xc000e76c80, 0xc000e63a90, 0x26d3c60, 0xc00057ffe0, 0xc000e63b00, 0x24b32e8, 0xc000e63bf0, 0x271e040, ...)
        github.com/tendermint/tendermint@v0.34.12/node/node.go:715 +0x2025
github.com/cosmos/cosmos-sdk/server.startInProcess(0xc001278920, 0x0, 0x0, 0x0, 0x2745760, 0xc0012cd7d0, 0x0, 0x0, 0x2727880, 0xc0011a4b40, ...)
        github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:263 +0x665
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00121c780, 0xc0012cc990, 0x0, 0x3, 0x0, 0x0)
        github.com/cosmos/cosmos-sdk@v0.43.0/server/start.go:129 +0x189
github.com/spf13/cobra.(*Command).execute(0xc00121c780, 0xc0012cc930, 0x3, 0x3, 0xc00121c780, 0xc0012cc930)
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc00056f680, 0x0, 0x0, 0xc001115870)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.1.3/command.go:890
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc00056f680, 0xc001115870, 0xc, 0x273c020, 0xc0011a4b40)
        github.com/cosmos/cosmos-sdk@v0.43.0/server/cmd/execute.go:36 +0x285
main.main()
        github.com/terra-money/core/cmd/terrad/main.go:15 +0x45

**Who can help me answer this question? Thank you very much！**

**Comment by YunSuk-Yeo** [comment]
Which network are you trying to connect??

if you want to connect columbus-4 or tequila-0004, please use v0.4.6
