### ISSUE TITLE
[BUG] M1 gets an error when deploying/initializing contracts

### ISSUE THREAD

**Issue by richance** [terra-money/core#548]
**Describe the bug**
LocalTerra v0.5.0 seems not working on m1 mac. When I run docker compose up, blocks are produced as expected, but when I upload a contract binary, I see the following error:
terrad_1         | qemu: uncaught target signal 11 (Segmentation fault) - core dumped

**To Reproduce**
Start LocalTerra and then try uploading a contract code (which works fine)
but the command
terrad tx wasm instantiate 1 '{"count":0}' --from test1 --chain-id=localterra --fees=10000uluna --gas=auto --broadcast-mode=block
produces the error

**Comment by YunSuk-Yeo** [comment]
Sorry for inconvenient :(

CosmWasm is not supporting M1 yet.

Please check https://github.com/cosmwasm/wasmvm#overview

Temporary close this issue, and will reopen this when cosmwasm support M1 architecture.
