### ISSUE TITLE
The IBC channel between Terra and Osmosis is not open

### ISSUE THREAD

**Issue by ozingi** [terra-money/core#55]
The IBC channel between Terra and Osmosis is not open

**Comment by emidev98** [comment]
Hello, 
Please use this channel for code-related issues. If you need info about relayers or validators on Terra 2.0 you can join the validators Discord https://discord.gg/NJj4HmEr or IBC Gang https://discord.gg/e3VVuMFz.

Seems like the relayer Osmosis <-> Terra2 is up and running https://www.mintscan.io/osmosis/relayers/channel-251
