### ISSUE TITLE
Node cannot connect to a mainnet seed 

### ISSUE THREAD

**Issue by vlads123** [terra-money/core#553]
Hello 

Im trying to run a full node
Following this docs https://docs.terra.money/node/join-network.html#run-your-node
and https://docs.terra.money/node/join-network.html#setup to connect to columbus-4 (aka mainnet)

terrad version v0.4.6

I have downloaded and extracted the snapshot (columbus-4-default.20210902.0610.tar.lz4) from https://terra.quicksync.io/

when I run `terrad start`
continuously see these errors

```
E[2021-09-05|23:56:05.363] Error dialing seed                           module=p2p err="auth failure: secret conn failed: read tcp 10.26.0.39:49034->13.124.78.245:26656: i/o timeout" seed=87048bf71526fb92d73733ba3ddb79b7a83ca11e@13.124.78.245:26656
E[2021-09-05|23:56:06.364] Error dialing seed                           module=p2p err="dial tcp 52.231.69.191:26656: i/o timeout" seed=5fa582d7c9931e5be8c02069d7b7b243c79d25bf@52.231.69.191:26656
E[2021-09-05|23:56:06.364] Couldn't connect to any seeds                module=p2p 
```

List of seeds set with regards to https://docs.terra.money/node/join-network.html#define-seed-nodes

I was not able to download addrbook.json seems the URL is broken (using this instructions https://docs.terra.money/node/join-network.html#download-address-book-recommended-for-the-mainnet)

Any help is much appreciated

**Comment by flynnji** [comment]
i was trying to set up a full node just following the docs, and got the same connect error too,
and same version v0.4.6

**Comment by drbh** [comment]
@vlads123 

Regarding `addrbook.json` this link is working for me: https://network.terra.dev/addrbook.json

command used to test:
```bash
curl https://network.terra.dev/addrbook.json | jq . > addrbook.json
```

**Comment by vlads123** [comment]
Seems service providing addrbook.json is fixed now
So this is is closed
