### ISSUE TITLE
[question] tools and integration summary

### ISSUE THREAD

**Issue by paulvi** [terra-money/core#555]
(This maybe more suitable for https://github.com/terra-money/awesome-terra, but issues are closed there)

I am trying to grasp all integration options for terra

1) This `core` repos gives `terrad` terra blockchain node with some RPC interface, but I cannot really see it yet https://docs.terra.money/node/installation.html
2) FCD provides REST interface, used with Terra Finder - Official block explorer
3) mantle provides GraphQL interface. 
Is it actually 100% blockchain info, just like FCD but in GraphQL way?
4) and there was some subgraph for terraswap using node.js

I hope I have not missed anything, but there should be some universal Cosmos tools as well applicable/customizable.
And even without them, there is already dilemma FCD vs mantle, REST vs GraphQL
And wether to use Python, as the only client API is `terra-sdk-python`

What was history behind, ideas and future plans for these tools?
Which one is recommended?

**Comment by YunSuk-Yeo** [comment]
@ouiliame Please keep follow this issue

**Comment by silvermind** [comment]
@YunSuk-Yeo any update on this?

**Comment by hanjukim** [comment]
I will close this issue. Developer docs are here: https://docs.terra.money/docs/develop/README.html
