### ISSUE TITLE
get terracli binary

### ISSUE THREAD

**Issue by roccomuso** [terra-money/core#558]
Is the terracli binary available somewhere, ready to download?
without having to deal with manual building?

**Comment by YunSuk-Yeo** [comment]
@roccomuso terracli has been removed from v0.5.x. instead you can use terrad for all client command lines.

**Comment by roccomuso** [comment]
still is there an already built binary file of `terrad`?

**Comment by hanjukim** [comment]
> still is there an already built binary file of `terrad`?

For several reasons, we recommend you to compile it on the machine you are going to use.

**Comment by roccomuso** [comment]
if you publish a checksum as well it would be totally safe to have one already built and downloadable.
