### ISSUE TITLE
unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

### ISSUE THREAD

**Issue by JSilvermanCohen** [terra-money/core#56]
Trying to run a terra node and when I try to run `terrad start` I get the panic in the title.

**Comment by YunSuk-Yeo** [comment]
I think you used wrong genesis file.

can you try with https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json

and you also need to clear local storage with `terrad tendermint unsafe-reset-all`
