### ISSUE TITLE
[FEATURE] Remove runtime dependency on /build

### ISSUE THREAD

**Issue by JonathanLorimer** [terra-money/core#563]
**Problem definition**
I am trying to package `terrad` via nix in this [repo](https://github.com/informalsystems/cosmos.nix), see this [issue](https://github.com/informalsystems/cosmos.nix/issues/19). Nix provides completely deterministic and reproducible builds, so it does not allow you to make any assumptions about the runtime environment (i.e. the presence of a `/build` directory).

**Feature specification**
I would like to be able to provide whatever dependencies are stored in `/build` at build time.

**Additional context**
From what I can tell (I have no experience with go) the dependencies that are stored in `/build` are:
- `libwasmvm.so`
- `terrad`

I am not sure why `terrad` needs to be available in `/build`. I would assume that `terrad` is the generated executable from running something like `go build` (but again, my go specific experience is lacking here). For `libwasmvm.so` I wonder if its path could be provided via an environment variable? That would make things work in my case, and would be more flexible for users who want to provide their own version.

Anyways, I hope I haven't underestimated the complexity of the problem. I also hope the path to a solution will be simple enough that I can submit a PR to enact it!

Thanks for taking the time to look at this!

**Comment by JonathanLorimer** [comment]
Would help resolve https://github.com/informalsystems/cosmos.nix/pull/37

**Comment by JonathanLorimer** [comment]
@YunSuk-Yeo I am still working through this lol, I was wondering if libswamvm.so is called via `exec` or through the cgo `ffi`? Also can you point me to where it is called in the codebase? I really appreciate the help!

**Comment by YunSuk-Yeo** [comment]
The libwasmvm.so is called via `ffi` and you can find the map in [here](https://github.com/cosmwasm/wasmvm)

**Comment by JonathanLorimer** [comment]
Hey @YunSuk-Yeo I actually managed to get it all working! Feel free to test it out!

You should just be able to [install nix](https://nixos.org/download.html) and then run `nix run github:informalsystems/cosmos.nix#terra`

**Comment by hanjukim** [comment]
@JonathanLorimer We never tried nix but we are using `make build-linux` for building static runtime.
