### ISSUE TITLE
[BUG] terrad tx sign multisig arg only accepts the name of a multisig, not its address

### ISSUE THREAD

**Issue by harryscholes** [terra-money/core#570]
With `terracli` v0.4.x, I used to be able to provide the `multisig` argument as the multisig address, but this no longer works with `terrad` v0.5.x:
```
❯ terrad tx sign unsigned_tx.json --multisig terra1mrp9zew60avy83vn8mhg0h8z44928r0axrfagf --chain-id bombay-12
Error: error getting account from keybase: key with addressD8C25165DA7F5843C5933EEE87DCE2AD4AA38DFDnot found: key not found [cosmos/cosmos-sdk@v0.44.1/crypto/keyring/keyring.go:465]
```

The docs suggest this should work:
```
--multisig string          Address or key name of the multisig account on behalf of which the transaction shall be signed
```

But signing only works if the name of the multisig is provided:
```
❯ terrad keys show test1_test2
- name: test1_test2
  type: multi
  address: terra1mrp9zew60avy83vn8mhg0h8z44928r0axrfagf
  pubkey: '{"@type":"/cosmos.crypto.multisig.LegacyAminoPubKey","threshold":2,"public_keys":[{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"AjszqFJDRAYbEjZMuiD+ChqzbUSGq/RRu3zr0R6iJB5b"},{"@type":"/cosmos.crypto.secp256k1.PubKey","key":"A1xYF6iW3VSia08ItqjeBfpai+xj8tmuy/Ij3YquR6mX"}]}'
  mnemonic: ""
❯ terrad tx sign unsigned_tx.json --multisig test1_test2 --chain-id bombay-12
```

terrad v0.5.6

**Comment by YunSuk-Yeo** [comment]
Thanks for reporting, we also know this problem. and it is from cosmos-sdk, so I will report this to cosmos team

**Comment by likhita-809** [comment]
> Hey! Is this issue still present?
> 
> I just tried to debug this a bit, and it seems to work for me. The script I used is this one: https://gist.github.com/amaurym/86abd606fe381af572cf812a7493ba4d.
> 
> It uses the SDK's minimal `simapp`, but you should be able to replace simd with terrad
> 
> I tried on SDK 0.44.6, 0.45.1 and master.

Yes! Everything works well. It's just that we need to pass the `--from` flag along with `--multisig` flag.
@harryscholes could you try this and respond, so that we can close this issue ?

**Comment by YunSuk-Yeo** [comment]
Will consider this issue resolved due to inactivity - let us know if otherwise
