### ISSUE TITLE
[FEATURE] A1/ARM64 & windows binary releases

### ISSUE THREAD

**Issue by sascha1337** [terra-money/core#581]
**Problem definition**
People frustrated because there are no arm64 / darwin-arm64 / windows binaries 

**Feature specification**
Add github workflows to lint, build, test and build terrad binaries for specified architectures

Cheers!

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)

**Comment by hanjukim** [comment]
It's working in main branch now.

**Comment by sascha1337** [comment]
groundbreaking news, to the perfect time. thanks @hanjukim 🙏🏻
