### ISSUE TITLE
new app.toml. Is this modification correct?

### ISSUE THREAD

**Issue by masayil** [terra-money/core#602]
new app.toml. Is this modification correct?
[wasm]
contract-query-gas-limit = "3000000"
contract-memory-cache-size = "100"
contract-debug-mode = "false"
write-vm-memory-cache-size = "500"
read-vm-memory-cache-size = "300"
num-read-vms = "1

**Comment by YunSuk-Yeo** [comment]
You can remove last 3 lines

**Comment by masayil** [comment]
thx
