### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by sams2211** [terra-money/core#609]
while executing `make install` in sudo , getting this
`contrib/devtools/Makefile:15: *** could not find go. Is it in PATH? .  Stop.
`
i have installed go version 
`go version go1.17.3 linux/amd64
`
where to put go path in script to run ?

**Comment by YunSuk-Yeo** [comment]
Did you set `GO_PATH` and add `GO_BIN` to our env PATH??

**Comment by sams2211** [comment]
I'm a beginner , I don't know where to set , where can I check sir?

**Comment by sams2211** [comment]
im getting this issue only running go files in sudo , remaining all is fine
please help where to set path ??

**Comment by YunSuk-Yeo** [comment]
you don't need to run make install in sudo.

can you just try `make install`?

**Comment by sams2211** [comment]
i tried normally but got these errors
`go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=terra -X github.com/cosmos/cosmos-sdk/version.AppName=terrad -X github.com/cosmos/cosmos-sdk/version.Version=0.5.6-oracle -X github.com/cosmos/cosmos-sdk/version.Commit=cb4b91199ff0d7c8260d102c6a595ca09d9079f6 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath ./cmd/terrad
/bin/sh: 1: go: not found
Makefile:123: recipe for target 'install' failed
make: *** [install] Error 127
`
so tried with sudo and encountered that ....

**Comment by YunSuk-Yeo** [comment]
Can you add this to `~/.bashrc `
```shell
export GOROOT=/usr/local/go
export GOPATH=/home/ubuntu/go
export GOBIN=$GOPATH/bin
export PATH=$PATH:$GOROOT/bin:$GOBIN
```

and run 
`$ source ~/.bashrc`

**Comment by sams2211** [comment]
added above lines to ~/.bashrc and ran `source ~/.bashrc`

But in sudo still getting this after ran `go version` and got this
`Command 'go' not found, but can be installed with:

snap install go         # version 1.17.2, or
apt  install golang-go
apt  install gccgo-go 

See 'snap info go' for additional versions.`

**Comment by YunSuk-Yeo** [comment]
Please install go with https://golang.org/doc/install steps

**Comment by sams2211** [comment]
yep , i followed those steps and ended up here

**Comment by YunSuk-Yeo** [comment]
can you show your command history? 

just `make install` or `sudo make install`?
please don't use sudo anyway

**Comment by sams2211** [comment]
`student@vamsis-arcade:~/core$ make install
`

and getting this issue 
`go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=terra -X github.com/cosmos/cosmos-sdk/version.AppName=terrad -X github.com/cosmos/cosmos-sdk/version.Version=0.5.6-oracle -X github.com/cosmos/cosmos-sdk/version.Commit=cb4b91199ff0d7c8260d102c6a595ca09d9079f6 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath ./cmd/terrad
/bin/sh: 1: go: not found
Makefile:123: recipe for target 'install' failed
make: *** [install] Error 127`

**Comment by YunSuk-Yeo** [comment]
I'm not sure what is your problem.
Actually hard to understand how `go version` show result, but `go install` is saying go not found. 

I don't think this is our repository problem, so please clean your environment and try again.

**Comment by YunSuk-Yeo** [comment]
can you try `$ which go` and `history | tail -n 20`

**Comment by YunSuk-Yeo** [comment]
okay seems the problem is `sudo su`.

Please out of the sudo area. just run the command in user level. 

`sudo su` makes your shell in root permission area. so press ctrl+D

**Comment by sams2211** [comment]
im trying it normal profile , not in sudo su but still getting this`go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=terra -X github.com/cosmos/cosmos-sdk/version.AppName=terrad -X github.com/cosmos/cosmos-sdk/version.Version=0.5.6-oracle -X github.com/cosmos/cosmos-sdk/version.Commit=cb4b91199ff0d7c8260d102c6a595ca09d9079f6 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s' -trimpath ./cmd/terrad
/bin/sh: 1: go: not found
Makefile:123: recipe for target 'install' failed
make: *** [install] Error 127`

other go install commands and all are working , only with this one happening this

**Comment by GoGetterMeme** [comment]
@sams2211 run `go env` in your shell, what's your `GOROOT`, `GOPATH`, `GOTOOLDIR`?

your Go may just have trouble compiling, run `which go` to verify `GOTOOLDIR` matches your Go env

try opening Core on VS Code, download all VS Code's recommended Go extensions (including `Gopls`  on VS Code, then retry it in the terminal on VS Code

worked for me, had the same issue

**Comment by sams2211** [comment]
i tried `go env` on terminal, go these for `GOROOT="/usr/local/go"` `GOPATH="/home/student/go"` `GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"`

and tried `which go` and got this `/usr/local/go/bin/go`

so when i tried in vs code terminal , `go version` got this `Command 'go' not found, but can be installed with:

sudo snap install go         # version 1.17.3, or
sudo apt  install golang-go
sudo apt  install gccgo-go 

See 'snap info go' for additional versions.`
so vs code terminal isnt recognising

**Comment by GoGetterMeme** [comment]
Just download all the Go extensions one man can download into VS Code and try running those commands.

**Comment by sams2211** [comment]
installed vs code recommended and all go extensions , no use, still getting above error

**Comment by sams2211** [comment]
tried in go github for solution , they are saying its makefile issue , not a go issue

https://github.com/golang/go/issues/49714
seems its my system error.....

**Comment by YunSuk-Yeo** [comment]
yea the Makefile is just simple `go install` command. 

Clear all your env and follow from the scratch to install go.

**Comment by crabust** [comment]
https://github.com/terra-money/core/issues/614

**Comment by sams2211** [comment]
this issue is my laptop i think,  so i tried with other laptops , its working fine
