### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ColtraneNadler** [terra-money/core#613]
**Describe the bug**

I'm installing on my m1 mac, using rosetta terminal
when I run make install / arch -x86_64 make install I get-

`
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=terra -X github.com/cosmos/cosmos-sdk/version.AppName=terrad -X github.com/cosmos/cosmos-sdk/version.Version=0.5.6-oracle -X github.com/cosmos/cosmos-sdk/version.Commit=cb4b91199ff0d7c8260d102c6a595ca09d9079f6 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo,ledger" -w -s -trimpath ./cmd/terrad'
`

and then nothing happens after.

**To Reproduce**
Describe the steps to reproduce the behavior.

running make install
or arch -x86_64 make install

**Context & versions**
Delineate the correct versions of all the components involved in reproducing the bug. 

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by crabust** [comment]
https://github.com/terra-money/core/issues/614

**Comment by YunSuk-Yeo** [comment]
yea you can find terrad in $GOPATH/bin/terrad

try 
which terrad

also @crabust thanks for your suggestion, maybe we can add some message to indicate generated terrad path.
