### ISSUE TITLE
[BUG] Docker image killed without any messages when start up.

### ISSUE THREAD

**Issue by MegaSolar** [terra-money/core#617]
**Describe the bug**
pull the docker images from docker hub, set up the environment and run it. 
But terrad process killed without any messages. 

**To Reproduce**
1. docker pull terramoney/core:v0.5.11
2. run docker image `docker run -it --rm terramoney/core:v0.5.11 /bin/sh`
3. terrad init --chain-id columbus-5 moniker
4. download genesis file from here : https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/columbus-5-genesis.json
5. change existed genesis file to downloaded genesis file  
6. download https://network.terra.dev/addrbook.json in .terra/config
7. Run it 'terrad start --x-crisis-skip-assert-invariants'
8. 7:03AM INF starting ABCI with Tendermint message came out. 
9. Killed

**Context & versions**
`Terrad version :  terramoney/core:v0.5.11`
`macOS : 10.14.6 (18G9323)`
`2.9 GHz Intel Core i9`
`32 GB 2400 MHz DDR4`
`Client:
 Cloud integration: v1.0.20
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:43:15 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:30 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

``

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by hanjukim** [comment]
Did you allocate enough memory to Docker VM?

**Comment by MegaSolar** [comment]
@hanjukim Nope. 
it's OOM issue. 
Thank you. 
I close this issue.
