### ISSUE TITLE
[BUG] `cosmos/base/tendermint/v1beta1/validatorsets/latest` doesn't return `next_key`

### ISSUE THREAD

**Issue by 0xChanwoo** [terra-money/core#618]
**Describe the bug**

Querying `/cosmos/base/tendermint/v1beta1/validatorsets/latest` returns `pagination.next_key` as null while showing 100 validators from 130 validatorsets

Also it doesn't respect `pagination.limit` more than 100 while <= 100 works.

**To Reproduce**

https://fcd.terra.dev/cosmos/base/tendermint/v1beta1/validatorsets/latest returns 100 validators with `pagination.next_key` as null when it is expected to return the next_key for the next 30 validators
https://fcd.terra.dev/cosmos/base/tendermint/v1beta1/validatorsets/latest?pagination.limit=200 returns only 100
https://fcd.terra.dev/cosmos/base/tendermint/v1beta1/validatorsets/latest?pagination.limit=10 returns 10

**(if applicable) suggested solution**

https://fcd.terra.dev/cosmos/base/tendermint/v1beta1/validatorsets/latest should return the `next_key` when `pagination.limit=100` and the total number of validators in the set is 130 and when `pagination.limit=130` is provided,  it should return 130 validators.

**Comment by hanjukim** [comment]
Confirmed. If you need full validatorset now, try legacy endpoint `https://lcd.terra.dev/validatorsets/latest?page=2`

**Comment by YunSuk-Yeo** [comment]
public end points blocked all queries including `pagination.offset`, but if you have your own node, you can do this query

https://fcd.terra.dev/cosmos/base/tendermint/v1beta1/validatorsets/latest?pagination.offset=100

or, @hanjukim can we exclude this endpoint?

**Comment by hanjukim** [comment]
Yes, I will exclude the rule for that endpoint.

**Comment by 0xChanwoo** [comment]
Thanks!
