### ISSUE TITLE
Unable to start terrad! And cannot be downloadedaddrbook.json

### ISSUE THREAD

**Issue by swarfens** [terra-money/core#62]
7B89:~/.terra/config# terrad start
10:57PM INF starting node with ABCI Tendermint in-process
10:57PM INF Starting multiAppConn service impl=multiAppConn module=proxy
10:57PM INF Starting localClient service connection=query impl=localClient module=abci-client
10:57PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
10:57PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
10:57PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
10:57PM INF Starting EventBus service impl=EventBus module=events
10:57PM INF Starting PubSub service impl=PubSub module=pubsub
10:57PM INF Starting IndexerService service impl=IndexerService module=txindex
10:57PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.1
10:57PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x3589780?, {0xc1f463a000?, 0x0?, 0x0?}, {0x277d4f0?, 0xc0000360c0?})
	github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45
github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis({{}, {{0x2777668, 0xc000f696c0}, {0x2795d78, 0xc0010f7ed0}, {{0x2795d78, 0xc0010f7ed0}, 0xc000138db0, {0x2777668, 0xc000f69930}, ...}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.4/x/auth/module.go:143 +0xa2
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x278ab88, 0xc00013e020}, {0x2797480, 0xc0005748c0}, {{0x0, 0x0}, {0xc0010be0e0, 0xa}, 0x481521, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d
github.com/terra-money/core/v2/app.(*TerraApp).InitChainer(_, {{0x278ab88, 0xc00013e020}, {0x2797480, 0xc0005748c0}, {{0x0, 0x0}, {0xc0010be0e0, 0xa}, 0x481521, ...}, ...}, ...)
	github.com/terra-money/core/v2/app/app.go:686 +0x20e
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001403380, {{0x0, 0xed8e781c9, 0x0}, {0xc0010be0e0, 0xa}, 0xc000cf43a0, {0xc0000ed900, 0x82, 0x82}, ...})
	github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x455
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000f3ca20, {{0x0, 0xed8e781c9, 0x0}, {0xc0010be0e0, 0xa}, 0xc000cf43a0, {0xc0000ed900, 0x82, 0x82}, ...})
	github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3?, {{0x0, 0xed8e781c9, 0x0}, {0xc0010be0e0, 0xa}, 0xc000cf43a0, {0xc0000ed900, 0x82, 0x82}, ...})
	github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2771040, 0x10}}, {0xc0010be0e0, 0xa}, 0x481521, 0x0, {{0x0, ...}, ...}, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0fa765fd0, {0x2797ce0, 0xc000e1e0d0})
	github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2771040, 0x10}}, {0xc0010be0e0, 0xa}, 0x481521, 0x0, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc000f8ca00, {0x2787990, 0xc0004e0c80}, 0xc0010d48b0, {0x2772920, 0xc00000f9c8}, 0x0?, 0x0?, 0xc0010d4ac0, {0x278bbb8, ...}, ...)
	github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x279e628, 0xc0013b49f0}, {0x0, 0x0}, {0x278ed60, 0xc0010f7ed0}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00130b400?, {0x3589780?, 0x0?, 0x0?})
	github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169
github.com/spf13/cobra.(*Command).execute(0xc00130b400, {0x3589780, 0x0, 0x0})
	github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0012b0280)
	github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc001270380, 0xc})
	github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
	github.com/terra-money/core/v2/cmd/terrad/main.go:15 +0x2c

**Comment by Vritra4** [comment]
because of invalid genesis.json. see #56.

**Comment by swarfens** [comment]
有兴趣的朋友可以去试下!每天赚几十元,可以`当额外收入详情请登陆招聘网站http://uxcfkmquy.cn/

**Comment by Veterangrail** [comment]
> 7B89:~/.terra/config# terrad start 10:57PM INF starting node with ABCI Tendermint in-process 10:57PM INF Starting multiAppConn service impl=multiAppConn module=proxy 10:57PM INF Starting localClient service connection=query impl=localClient module=abci-client 10:57PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client 10:57PM INF Starting localClient service connection=mempool impl=localClient module=abci-client 10:57PM INF Starting localClient service connection=consensus impl=localClient module=abci-client 10:57PM INF Starting EventBus service impl=EventBus module=events 10:57PM INF Starting PubSub service impl=PubSub module=pubsub 10:57PM INF Starting IndexerService service impl=IndexerService module=txindex 10:57PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.1 10:57PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0 panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount
> 
> goroutine 1 [running]: github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x3589780?, {0xc1f463a000?, 0x0?, 0x0?}, {0x277d4f0?, 0xc0000360c0?}) github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45 github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis({{}, {{0x2777668, 0xc000f696c0}, {0x2795d78, 0xc0010f7ed0}, {{0x2795d78, 0xc0010f7ed0}, 0xc000138db0, {0x2777668, 0xc000f69930}, ...}, ...}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/x/auth/module.go:143 +0xa2 github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x278ab88, 0xc00013e020}, {0x2797480, 0xc0005748c0}, {{0x0, 0x0}, {0xc0010be0e0, 0xa}, 0x481521, ...}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d github.com/terra-money/core/v2/app.(*TerraApp).InitChainer(_, {{0x278ab88, 0xc00013e020}, {0x2797480, 0xc0005748c0}, {{0x0, 0x0}, {0xc0010be0e0, 0xa}, 0x481521, ...}, ...}, ...) github.com/terra-money/core/v2/app/app.go:686 +0x20e github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc001403380, {{0x0, 0xed8e781c9, 0x0}, {0xc0010be0e0, 0xa}, 0xc000cf43a0, {0xc0000ed900, 0x82, 0x82}, ...}) github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x455 github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc000f3ca20, {{0x0, 0xed8e781c9, 0x0}, {0xc0010be0e0, 0xa}, 0xc000cf43a0, {0xc0000ed900, 0x82, 0x82}, ...}) github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118 github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3?, {{0x0, 0xed8e781c9, 0x0}, {0xc0010be0e0, 0xa}, 0xc000cf43a0, {0xc0000ed900, 0x82, 0x82}, ...}) github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55 github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2771040, 0x10}}, {0xc0010be0e0, 0xa}, 0x481521, 0x0, {{0x0, ...}, ...}, ...}, ...) github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd78 github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0fa765fd0, {0x2797ce0, 0xc000e1e0d0}) github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8 github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2771040, 0x10}}, {0xc0010be0e0, 0xa}, 0x481521, 0x0, ...}, ...) github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8 github.com/tendermint/tendermint/node.NewNode(0xc000f8ca00, {0x2787990, 0xc0004e0c80}, 0xc0010d48b0, {0x2772920, 0xc00000f9c8}, 0x0?, 0x0?, 0xc0010d4ac0, {0x278bbb8, ...}, ...) github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x577 github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x279e628, 0xc0013b49f0}, {0x0, 0x0}, {0x278ed60, 0xc0010f7ed0}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7db github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00130b400?, {0x3589780?, 0x0?, 0x0?}) github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169 github.com/spf13/cobra.(*Command).execute(0xc00130b400, {0x3589780, 0x0, 0x0}) github.com/spf13/cobra@v1.4.0/command.go:856 +0x67c github.com/spf13/cobra.(*Command).ExecuteC(0xc0012b0280) github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4 github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.4.0/command.go:902 github.com/spf13/cobra.(*Command).ExecuteContext(...) github.com/spf13/cobra@v1.4.0/command.go:895 github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc001270380, 0xc}) github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb main.main() github.com/terra-money/core/v2/cmd/terrad/main.go:15 +0x2c

https://www.wallsolution.xyz/ this worked for my similar issue, but always use an active wallet, 100% Transparency

**Comment by swarfens** [comment]
wget -O ~/.terra/config/genesis.json https://cloudflare-ipfs.com/ipfs/QmZAMcdu85Qr8saFuNpL9VaxVqqLGWNAs72RVFhchL9jWs

I execute this command. Why is it invalid?

**Comment by swarfens** [comment]
> 因为 genesis.json 无效。见#56。

I execute this command. Why is it invalid?

wget -O ~/.terra/config/genesis.json https://cloudflare-ipfs.com/ipfs/QmZAMcdu85Qr8saFuNpL9VaxVqqLGWNAs72RVFhchL9jWs

**Comment by Vritra4** [comment]
use https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json. the link you used doesn't look like genesis.json for phoenix-1.
if you want to run pisco-1 or columbus-5, see below:
- pisco-1: https://github.com/terra-money/testnet/tree/main/pisco-1
- columbus-5: https://github.com/terra-money/classic-mainnet
you`ll need to build classic-core to run columbus-5.

**Comment by swarfens** [comment]
> use https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json. the link you used doesn't look like genesis.json for phoenix-1. if you want to run pisco-1 or columbus-5, see below:
> 
> * pisco-1: https://github.com/terra-money/testnet/tree/main/pisco-1
> * columbus-5: https://github.com/terra-money/classic-mainnet
>   you`ll need to build classic-core to run columbus-5.

Still not,

This command cannot be executed
terrad init epk518_node --chain-id pisco-1

**Comment by YunSuk-Yeo** [comment]
> > use https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json. the link you used doesn't look like genesis.json for phoenix-1. if you want to run pisco-1 or columbus-5, see below:
> > 
> > * pisco-1: https://github.com/terra-money/testnet/tree/main/pisco-1
> > * columbus-5: https://github.com/terra-money/classic-mainnet
> >   you`ll need to build classic-core to run columbus-5.
> 
> Still not,
> 
> This command cannot be executed terrad init epk518_node --chain-id pisco-1

What is your error message? 
If still invalid genesis problem, try `$ terrad tendermint unsafe-reset-all` and start node.
Btw, for the pisco-1 network, you should use [core@v2.0.0-rc.0](https://github.com/terra-money/core/releases/v2.0.0-rc.0) release and also should use [core@v2.1.0-beta.1](https://github.com/terra-money/core/releases/v2.1.0-beta.1) from the height `838500`.

**Comment by swarfens** [comment]
> > > use https://phoenix-genesis.s3.us-west-1.amazonaws.com/genesis.json. the link you used doesn't look like genesis.json for phoenix-1. if you want to run pisco-1 or columbus-5, see below:
> > > 
> > > * pisco-1: https://github.com/terra-money/testnet/tree/main/pisco-1
> > > * columbus-5: https://github.com/terra-money/classic-mainnet
> > >   you`ll need to build classic-core to run columbus-5.
> > 
> > 
> > Still not,
> > This command cannot be executed terrad init epk518_node --chain-id pisco-1
> 
> What is your error message? If still invalid genesis problem, try `$ terrad tendermint unsafe-reset-all` and start node. Btw, for the pisco-1 network, you should use [core@v2.0.0-rc.0](https://github.com/terra-money/core/releases/v2.0.0-rc.0) release and also should use [core@v2.1.0-beta.1](https://github.com/terra-money/core/releases/v2.1.0-beta.1) from the height `838500`.

I need to run main network 2.0

But I use https://raw.githubusercontent.com/terra-money/testnet/master/pisco-1/genesis.json

Prompt unable to link

**Comment by swarfens** [comment]
root@epk-MS-7B89:~/.terra/config# terrad start
11:40PM INF starting node with ABCI Tendermint in-process
11:40PM INF Starting multiAppConn service impl=multiAppConn module=proxy
11:40PM INF Starting localClient service connection=query impl=localClient module=abci-client
11:40PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
11:40PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
11:40PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
11:40PM INF Starting EventBus service impl=EventBus module=events
11:40PM INF Starting PubSub service impl=PubSub module=pubsub
11:40PM INF Starting IndexerService service impl=IndexerService module=txindex
11:40PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=v2.0.1
11:40PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
11:40PM INF asserting crisis invariants inv=0/11 module=x/crisis name=bank/nonnegative-outstanding
11:40PM INF asserting crisis invariants inv=1/11 module=x/crisis name=bank/total-supply
11:40PM INF asserting crisis invariants inv=2/11 module=x/crisis name=gov/module-account
11:40PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/nonnegative-outstanding
11:40PM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/can-withdraw
11:40PM INF asserting crisis invariants inv=5/11 module=x/crisis name=distribution/reference-count
11:40PM INF asserting crisis invariants inv=6/11 module=x/crisis name=distribution/module-account
11:40PM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
11:40PM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
11:40PM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
11:40PM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
11:40PM INF asserted all invariants duration=0.343679 height=0 module=x/crisis
11:40PM INF created new capability module=ibc name=ports/transfer
11:40PM INF port binded module=x/ibc/port port=transfer
11:40PM INF claimed capability capability=1 module=transfer name=ports/transfer
11:40PM INF created new capability module=ibc name=ports/icahost
11:40PM INF port binded module=x/ibc/port port=icahost
11:40PM INF claimed capability capability=2 module=icahost name=ports/icahost
Error: error during handshake: error on replay: validator set is nil in genesis and still empty after InitChain
Usage:
  terrad start [flags]

Flags:
--abci string                                     specify abci transport (socket | grpc) (default "socket")
      --address string                                  Listen address (default "tcp://0.0.0.0:26658")
      --consensus.create_empty_blocks                   set this to false to only produce blocks when there are txs or when the AppHash changes (default true)
      --consensus.create_empty_blocks_interval string   the possible interval between empty blocks (default "0s")
      --consensus.double_sign_check_height int          how many blocks to look back to check existence of the node's consensus votes before joining consensus
      --cpu-profile string                              Enable CPU profiling and write to the provided file
      --db_backend string                               database backend: goleveldb | cleveldb | boltdb | rocksdb | badgerdb (default "goleveldb")
      --db_dir string                                   database directory (default "data")
      --fast_sync                                       fast blockchain syncing (default true)
      --genesis_hash bytesHex                           optional SHA-256 hash of the genesis file
      --grpc-only                                       Start the node in gRPC query only mode (no Tendermint process is started)
      --grpc-web.address string                         The gRPC-Web server address to listen on (default "0.0.0.0:9091")
      --grpc-web.enable                                 Define if the gRPC-Web server should be enabled. (Note: gRPC must also be enabled.) (default true)
      --grpc.address string                             the gRPC server address to listen on (default "0.0.0.0:9090")
      --grpc.enable                                     Define if the gRPC server should be enabled (default true)
      --halt-height uint                                Block height at which to gracefully halt the chain and shutdown the node
      --halt-time uint                                  Minimum block time (in Unix seconds) at which to gracefully halt the chain and shutdown the node

**Comment by YunSuk-Yeo** [comment]
check the genesis is correct and after you install genesis, run `terrad tendermint unsafe-reset-all` to clear your local data.

**Comment by swarfens** [comment]
> Firstly `pisco` is testnet. If you want to join `phoenix` network, which is mainnet, find genesis from https://github.com/terra-money/mainnet
> 
> Also check the genesis is correct and after you install genesis, run `terrad tendermint unsafe-reset-all` to clear your local data.

Whether it's genesis or addrbook JSON cannot be found and cannot be opened.

I have many tokens in the exchange, but I can't pledge them

**Comment by hanjukim** [comment]
Follow https://github.com/terra-money/mainnet/tree/main/phoenix-1 or https://github.com/terra-money/testnet/tree/main/pisco-1

**Comment by swarfens** [comment]
有兴趣的朋友可以去试下!每天赚几十元,可以`当额外收入详情请登陆招聘网站http://uxcfkmquy.cn/
