### ISSUE TITLE
[BUG] security update

### ISSUE THREAD

**Issue by YunSuk-Yeo** [terra-money/core#627]
**Describe the bug**
details will be shared after patch alive

**Target versions**

All versions before v0.5.13

**Solution**
Please update your node to below binaries.

The target soft fork height is `5,701,000` for `columbus-5` and `7,000,000` for `bombay-12`

ETA (`columbus-5`): 
```
Thu Dec 16 2021 06:50:00 GMT-0800 (PST)
Thu Dec 16 2021 14:50:00 GMT+0000 (UTC)
Thu Dec 16 2021 23:50:00 GMT+0900 (KST)
```

[terra_0.5.13_Linux_x86_64.tar.gz](https://github.com/terra-money/core/files/7689754/terra_0.5.13_Linux_x86_64.tar.gz)
[terra_0.5.13-oracle_Linux_x86_64.tar.gz](https://github.com/terra-money/core/files/7689759/terra_0.5.13-oracle_Linux_x86_64.tar.gz)
[terra_0.5.13_Darwin_x86_64.tar.gz](https://github.com/terra-money/core/files/7689762/terra_0.5.13_Darwin_x86_64.tar.gz)
[terra_0.5.13-public_Linux_x86_64.tar.gz](https://github.com/terra-money/core/files/7689778/terra_0.5.13-public_Linux_x86_64.tar.gz)

```sh
b44b78273096e1c37c499b52fcfd9dc746b5be12a5149dd014b33e86b6913bda  ./terra_0.5.13_Linux_x86_64.tar.gz
73a847a1bbae54579c74c07a5ae41ba79540811b72d60c00cf158dca7e9816f3  ./terra_0.5.13-oracle_Linux_x86_64.tar.gz
05c9e0990f244ec3d7ffcd701f12ed78104ba1e0f09ec3eb4902ccb4f4873ea7  ./terra_0.5.13_Darwin_x86_64.tar.gz
82e4a1417cc3588c30582745dcc8e85e047b27a175a126b33c72a63fe58291ff  ./terra_0.5.13-public_Linux_x86_64.tar.gz
```

**Comment by don-mao** [comment]
Hello,

Any news regarding the softfork? Regarding Bombay-12, my transactions aren't executed (no errors though)  but yet the queries work fine.

Thank you,

Cheers

**Comment by YunSuk-Yeo** [comment]
The problem was gone now.

https://github.com/terra-money/core/releases/tag/v0.5.13

**Comment by YunSuk-Yeo** [comment]
> Hello,
> 
> Any news regarding the softfork? Regarding Bombay-12, my transactions aren't executed (no errors though) but yet the queries work fine.
> 
> Thank you,
> 
> Cheers

I think we can do this in other channel like discord.

The bombay public nodes may works tmw :)
