### ISSUE TITLE
[BUG] mainnet consensus issue at block 5684022 (v0.5.11 & v0.5.12)

### ISSUE THREAD

**Issue by jun0tpyrc** [terra-money/core#629]
**Describe the bug**
```
9:47AM INF Starting EventBus service impl=EventBus module=events
9:47AM INF Starting PubSub service impl=PubSub module=pubsub
9:47AM INF Starting IndexerService service impl=IndexerService module=txindex
9:47AM INF ABCI Handshake App Info hash="��\x11�B����?�̞2�\x18\\e\x02��{����d1e��:" height=5684022 module=consensus protocol-version=0 software-version=0.5.11
9:47AM INF ABCI Replay Blocks appHeight=5684022 module=consensus stateHeight=5684022 storeHeight=5684023
9:47AM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected C2743948675AB3AAF1709585B5DE7425EC978660F209276E0A46ABB8A53C9DED, got 4368B26106D5B1171A324A42021D73DA2C814A87BDB39BCC68863E7418
F29325 
```

another report from discord channel , latest v0.5.12 also affected
<img width="1246" alt="Screenshot 2021-12-15 at 5 59 56 PM" src="https://user-images.githubusercontent.com/68580727/146166137-d5898c40-a12e-4e49-ab99-e30561927d3a.png">

**Comment by hanjukim** [comment]
We are investigating this issue. A discovered symptom is that not all nodes have the same issue.

**Comment by vae520283995** [comment]
> We are investigating this issue. A discovered symptom is that not all nodes have the same issue. To fix this, you will need to get snapshot and re-sync.

@hanjukim  Can only resync to solve the problem?

**Comment by jer-lim** [comment]
@vae520283995 https://quicksync.io/networks/terra.html

**Comment by hanjukim** [comment]
Make sure to have terrad node v0.5.13 as well.

**Comment by zlace0x** [comment]
Is there an official release for v0.5.13?

**Comment by ryanhextech** [comment]
@vae520283995 I have same problem with you. I tried to use v0.5.13 at https://github.com/terra-money/core/issues/627 and imported snapshot. My node working well now

**Comment by vae520283995** [comment]
> @vae520283995 I have same problem with you. I tried to use v0.5.13 at #627 and imported snapshot. My node working well now

@ryanhextech Which snapshot do you use?

**Comment by ryanhextech** [comment]
@vae520283995 https://quicksync.io/networks/terra.html, I used `columbus-5-default` from Singapore region

**Comment by YunSuk-Yeo** [comment]
I did several test, and grab shared library one make different result from static one.

```

We found the problem last night LastResultsHash difference panic.
When we use terrad with shared library libwasmvm.so, it can make different used_gas result from terrad with static library one (tested with v0.5.12). 

Due to security patch, many validators already moved their node version to v0.5.13 which is using static library. 
so from now, we have to keep static library version as our main software for mainnet and testnet. 

Here is the point. 
until we find and solve the problem please use terrad with  static library

static library version can be built with make build-linux, which requires docker for build not for runtime.

make install => shared
make build-linux => static

+ We just notify this to CosmWasm team to figure out this problem. 
```

**Comment by YunSuk-Yeo** [comment]
We found the problem is that libwasmvm static library and shared library making different error messages.
If a contract allow query error, then that error message will be a part of state and increase gas amount.

so two have different error message, which makes the consumed gas different.

from shared library
```
QUERY ERROR Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable
    at <unnamed> (<module>[681]:0x4eaee): contract query failed
```

from static library
```
QUERY ERROR Error calling the VM: Error executing Wasm: Wasmer runtime error: RuntimeError: unreachable: contract query failed
```

so until we apply the fixed version cosmwasm, we have to stick with static library version.
