### ISSUE TITLE
wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by masayil** [terra-money/core#630]
![image](https://user-images.githubusercontent.com/65291464/146478968-ab3c249f-d729-45b7-96f4-6f08afa8f523.png)

version: 0.5.12
When I updated to 0.5.13 [2021-12-17 10:00am UTC+8],I got the error. 
Is there any other solution besides downloading a new snapshot?

**Comment by YunSuk-Yeo** [comment]
There was softfork #627 .

You can use https://terra.quicksync.io/ to recover
