### ISSUE TITLE
terrad keys: org.freedesktop.DBus.Properties  does not exist

### ISSUE THREAD

**Issue by barbem** [terra-money/core#633]
# My env:
$ cat /etc/redhat-release
Fedora release 34 (Thirty Four)
$ uname -r
5.15.10-100.fc34.x86_64
$ terrad version
0.5.13
golang installed from dnf install golang
$ rpm -qa  | grep -i "golang"
golang-src-1.16.11-1.fc34.noarch
golang-bin-1.16.11-1.fc34.x86_64
golang-1.16.11-1.fc34.x86_64
f

# My issue
$ git clone git@github.com/terra-money/core
$ cd core
$ make install
$ terrad init --chain-id=pluton rosa
terrad init --chain-id=pluton rosa
{"app_message":{"auth":{"accounts":[],"params":{"max_memo_characters":"256","sig_verify_cost_ed25519":"590","sig_verify_cost_secp256k1":"1000","tx_sig_limit":"7","tx_size_cost_per_byte":"10"}},"authz":{"authorization":[]},"bank":{"balanc
es":[],"denom_metadata":[],"params":{"default_send_enabled":true,"send_enabled":[]},"supply":[]},"capability":{"index":"1","owners":[]},"crisis":{"constant_fee":{"amount":"1000","denom":"uluna"}},"distribution":{"delegator_starting_infos
":[],"delegator_withdraw_infos":[],"fee_pool":{"community_pool":[]},"outstanding_rewards":[],"params":{"base_proposer_reward":"0.010000000000000000","bonus_proposer_reward":"0.040000000000000000","community_tax":"0.020000000000000000","w
ithdraw_addr_enabled":true},"previous_proposer":"","validator_accumulated_commissions":[],"validator_current_rewards":[],"validator_historical_rewards":[],"validator_slash_events":[]},"evidence":{"evidence":[]},"feegrant":{"allowances":[
]},"genutil":{"gen_txs":[]},"gov":{"deposit_params":{"max_deposit_period":"172800s","min_deposit":[{"amount":"10000000","denom":"uluna"}]},"deposits":[],"proposals":[],"starting_proposal_id":"1","tally_params":{"quorum":"0.33400000000000
0000","threshold":"0.500000000000000000","veto_threshold":"0.334000000000000000"},"votes":[],"voting_params":{"voting_period":"172800s"}},"ibc":{"channel_genesis":{"ack_sequences":[],"acknowledgements":[],"channels":[],"commitments":[],"
next_channel_sequence":"0","receipts":[],"recv_sequences":[],"send_sequences":[]},"client_genesis":{"clients":[],"clients_consensus":[],"clients_metadata":[],"create_localhost":false,"next_client_sequence":"0","params":{"allowed_clients"
:["06-solomachine","07-tendermint"]}},"connection_genesis":{"client_connection_paths":[],"connections":[],"next_connection_sequence":"0","params":{"max_expected_time_per_block":"30000000000"}}},"market":{"params":{"base_pool":"1000000000
000.000000000000000000","min_stability_spread":"0.020000000000000000","pool_recovery_period":"14400"},"terra_pool_delta":"0.000000000000000000"},"mint":{"minter":{"annual_provisions":"0.000000000000000000","inflation":"0.1300000000000000
00"},"params":{"blocks_per_year":"6311520","goal_bonded":"0.670000000000000000","inflation_max":"0.200000000000000000","inflation_min":"0.070000000000000000","inflation_rate_change":"0.130000000000000000","mint_denom":"uluna"}},"oracle":
{"aggregate_exchange_rate_prevotes":[],"aggregate_exchange_rate_votes":[],"exchange_rates":[],"feeder_delegations":[],"miss_counters":[],"params":{"min_valid_per_window":"0.050000000000000000","reward_band":"0.020000000000000000","reward
_distribution_window":"5256000","slash_fraction":"0.000100000000000000","slash_window":"100800","vote_period":"5","vote_threshold":"0.500000000000000000","whitelist":[{"name":"ukrw","tobin_tax":"0.002500000000000000"},{"name":"usdr","tob
in_tax":"0.002500000000000000"},{"name":"uusd","tobin_tax":"0.002500000000000000"},{"name":"umnt","tobin_tax":"0.020000000000000000"}]},"tobin_taxes":[]},"params":null,"slashing":{"missed_blocks":[],"params":{"downtime_jail_duration":"60
0s","min_signed_per_window":"0.500000000000000000","signed_blocks_window":"100","slash_fraction_double_sign":"0.050000000000000000","slash_fraction_downtime":"0.010000000000000000"},"signing_infos":[]},"staking":{"delegations":[],"export
ed":false,"last_total_power":"0","last_validator_powers":[],"params":{"bond_denom":"uluna","historical_entries":10000,"max_entries":7,"max_validators":100,"unbonding_time":"1814400s"},"redelegations":[],"unbonding_delegations":[],"valida
tors":[]},"transfer":{"denom_traces":[],"params":{"receive_enabled":true,"send_enabled":true},"port_id":"transfer"},"treasury":{"epoch_initial_issuance":[],"epoch_states":[],"params":{"mining_increment":"1.070000000000000000","reward_pol
icy":{"cap":{"amount":"0","denom":"unused"},"change_rate_max":"0.025000000000000000","rate_max":"0.500000000000000000","rate_min":"0.050000000000000000"},"seigniorage_burden_target":"0.670000000000000000","tax_policy":{"cap":{"amount":"1
000000","denom":"usdr"},"change_rate_max":"0.000250000000000000","rate_max":"0.010000000000000000","rate_min":"0.000500000000000000"},"window_long":"52","window_probation":"12","window_short":"4"},"reward_weight":"0.050000000000000000","
tax_caps":[],"tax_proceeds":[],"tax_rate":"0.001000000000000000"},"upgrade":{},"vesting":null,"wasm":{"codes":[],"contracts":[],"last_code_id":"0","last_instance_id":"0","params":{"max_contract_gas":"20000000","max_contract_msg_size":"40
96","max_contract_size":"614400"}}},"chain_id":"pluton","gentxs_dir":"","moniker":"rosa","node_id":"5099fcc73fa14a092f935aedacb51f3b83f59ca6"}
f
$ terra keys add dev
terrad keys add dev
Error: L’interface « org.freedesktop.DBus.Properties » n’existe pas pour l’objet à l’emplacement /
Usage:
  terrad keys add <name> [flags]

Flags:
      --account uint32           Account number for HD derivation
      --algo string              Key signing algorithm to generate keys for (default "secp256k1")
      --coin-type uint32         coin type number for HD derivation (default 330)
      --dry-run                  Perform action, but don't add key to local keystore
      --hd-path string           Manual HD Path derivation (overrides BIP44 config)
  -h, --help                     help for add
      --index uint32             Address index number for HD derivation
  -i, --interactive              Interactively prompt user for BIP39 passphrase and mnemonic
      --ledger                   Store a local reference to a private key on a Ledger device
      --multisig strings         List of key names stored in keyring to construct a public legacy multisig key
      --multisig-threshold int   K out of N required signatures. For use in conjunction with --multisig (default 1)
      --no-backup                Don't print out seed phrase (if others are watching the terminal)
      --nosort                   Keys passed to --multisig are taken in the order they're supplied
      --pubkey string            Parse a public key in JSON format and saves key info to <name> file.
      --recover                  Provide seed phrase to recover existing key instead of creating

Global Flags:
      --home string              The application home directory (default "/home/raifer/.terra")
      --keyring-backend string   Select keyring's backend (os|file|test) (default "os")
      --keyring-dir string       The client Keyring directory; if omitted, the default 'home' directory will be used
      --log_format string        The logging format (json|plain) (default "plain")
      --log_level string         The logging level (trace|debug|info|warn|error|fatal|panic) (default "info")
      --output string            Output format (text|json) (default "text")
      --trace                    print out full stack trace on errors

**Comment by barbem** [comment]
$ terrad version --lon
name: terra
server_name: terrad
version: 0.5.13
commit: 0909bd43523fe9a77009fc4526e093b5bb0fecd8
build_tags: netgo ledger,
go: go version go1.16.11 linux/amd64
build_deps:
- filippo.io/edwards25519@v1.0.0-beta.2
- github.com/99designs/keyring@v1.1.6 => github.com/cosmos/keyring@v1.1.7-0.20210622111912-ef00f8ac3d76
- github.com/ChainSafe/go-schnorrkel@v0.0.0-20200405005733-88cbf1b4c40d
- github.com/CosmWasm/wasmvm@v0.16.2
- github.com/Workiva/go-datastructures@v1.0.52
- github.com/armon/go-metrics@v0.3.9
- github.com/beorn7/perks@v1.0.1
- github.com/bgentry/speakeasy@v0.1.0
- github.com/btcsuite/btcd@v0.22.0-beta
- github.com/cespare/xxhash/v2@v2.1.1
- github.com/coinbase/rosetta-sdk-go@v0.6.10
- github.com/confio/ics23/go@v0.6.6
- github.com/cosmos/btcutil@v1.0.4
- github.com/cosmos/cosmos-sdk@v0.44.5
- github.com/cosmos/go-bip39@v1.0.0
- github.com/cosmos/iavl@v0.17.3
- github.com/cosmos/ibc-go@v1.1.3
- github.com/cosmos/ledger-cosmos-go@v0.11.1 => github.com/terra-money/ledger-terra-go@v0.11.2
- github.com/cosmos/ledger-go@v0.9.2
- github.com/davecgh/go-spew@v1.1.1
- github.com/desertbit/timer@v0.0.0-20180107155436-c41aec40b27f
- github.com/dvsekhvalnov/jose2go@v0.0.0-20200901110807-248326c1351b
- github.com/felixge/httpsnoop@v1.0.1
- github.com/fsnotify/fsnotify@v1.5.1
- github.com/go-kit/kit@v0.10.0
- github.com/go-logfmt/logfmt@v0.5.0
- github.com/godbus/dbus@v0.0.0-20190726142602-4481cbc300e2
- github.com/gogo/gateway@v1.1.0
- github.com/gogo/protobuf@v1.3.3 => github.com/regen-network/protobuf@v1.3.3-alpha.regen.1
- github.com/golang/protobuf@v1.5.2
- github.com/golang/snappy@v0.0.3
- github.com/google/btree@v1.0.0
- github.com/google/orderedcode@v0.0.1
- github.com/gorilla/handlers@v1.5.1
- github.com/gorilla/mux@v1.8.0
- github.com/gorilla/websocket@v1.4.2
- github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0
- github.com/grpc-ecosystem/grpc-gateway@v1.16.0
- github.com/gsterjov/go-libsecret@v0.0.0-20161001094733-a6f4afe4910c
- github.com/gtank/merlin@v0.1.1
- github.com/gtank/ristretto255@v0.1.2
- github.com/hashicorp/go-immutable-radix@v1.0.0
- github.com/hashicorp/golang-lru@v0.5.4
- github.com/hashicorp/hcl@v1.0.0
- github.com/hdevalence/ed25519consensus@v0.0.0-20210204194344-59a8610d2b87
- github.com/improbable-eng/grpc-web@v0.14.1
- github.com/klauspost/compress@v1.11.7
- github.com/lib/pq@v1.10.2
- github.com/libp2p/go-buffer-pool@v0.0.2
- github.com/magiconair/properties@v1.8.5
- github.com/mattn/go-isatty@v0.0.14
- github.com/matttproud/golang_protobuf_extensions@v1.0.1
- github.com/mimoo/StrobeGo@v0.0.0-20181016162300-f8f6d4d2b643
- github.com/minio/highwayhash@v1.0.1
- github.com/mitchellh/mapstructure@v1.4.2
- github.com/mtibben/percent@v0.2.1
- github.com/pelletier/go-toml@v1.9.4
- github.com/pkg/errors@v0.9.1
- github.com/pmezard/go-difflib@v1.0.0
- github.com/prometheus/client_golang@v1.11.0
- github.com/prometheus/client_model@v0.2.0
- github.com/prometheus/common@v0.29.0
- github.com/prometheus/procfs@v0.6.0
- github.com/rakyll/statik@v0.1.7
- github.com/rcrowley/go-metrics@v0.0.0-20200313005456-10cdbea86bc0
- github.com/regen-network/cosmos-proto@v0.3.1
- github.com/rs/cors@v1.7.0
- github.com/rs/zerolog@v1.23.0
- github.com/spf13/afero@v1.6.0
- github.com/spf13/cast@v1.3.1
- github.com/spf13/cobra@v1.2.1
- github.com/spf13/jwalterweatherman@v1.1.0
- github.com/spf13/pflag@v1.0.5
- github.com/spf13/viper@v1.8.1
- github.com/stretchr/testify@v1.7.0
- github.com/subosito/gotenv@v1.2.0
- github.com/syndtr/goleveldb@v1.0.1-0.20200815110645-5c35d600f0ca
- github.com/tendermint/btcd@v0.1.1
- github.com/tendermint/crypto@v0.0.0-20191022145703-50d29ede1e15
- github.com/tendermint/go-amino@v0.16.0
- github.com/tendermint/tendermint@v0.34.14
- github.com/tendermint/tm-db@v0.6.4
- github.com/zondax/hid@v0.9.0
- golang.org/x/crypto@v0.0.0-20210817164053-32db794688a5
- golang.org/x/net@v0.0.0-20210903162142-ad29c8ab022f
- golang.org/x/sys@v0.0.0-20210903071746-97244b99971b
- golang.org/x/term@v0.0.0-20201126162022-7de9c90e9dd1
- golang.org/x/text@v0.3.6
- google.golang.org/genproto@v0.0.0-20210828152312-66f60bf46e71
- google.golang.org/grpc@v1.42.0 => google.golang.org/grpc@v1.33.2
- google.golang.org/protobuf@v1.27.1
- gopkg.in/ini.v1@v1.63.2
- gopkg.in/yaml.v2@v2.4.0
- gopkg.in/yaml.v3@v3.0.0-20210107192922-496545a6307b
- nhooyr.io/websocket@v1.8.6
cosmos_sdk_version: v0.44.5

(

**Comment by Vritra4** [comment]
i think it is keyring related. could you add keys again with `--keyring-backend file` and `--keyring-dir` ?

**Comment by barbem** [comment]
Hi, good, specifing keyring type fix the issue. It might be interesting to have a more explicit error message. I think that the problem come from my OS keyring configuration?
