### ISSUE TITLE
[BUG] Unable to sync full-node data

### ISSUE THREAD

**Issue by qlfgggggg** [terra-money/core#638]
I cannot sync full-node data.It's stuck here and won't move.
4:05PM INF starting ABCI with Tendermint
4:05PM INF Starting multiAppConn service impl=multiAppConn module=proxy
4:05PM INF Starting localClient service connection=query impl=localClient module=abci-client
4:05PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
4:05PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
4:05PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
4:05PM INF Starting EventBus service impl=EventBus module=events
4:05PM INF Starting PubSub service impl=PubSub module=pubsub
4:05PM INF Starting IndexerService service impl=IndexerService module=txindex
4:05PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.5.14
4:05PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
4:09PM INF asserting crisis invariants inv=0/11 module=x/crisis name=bank/nonnegative-outstanding
4:09PM INF asserting crisis invariants inv=1/11 module=x/crisis name=bank/total-supply
4:09PM INF asserting crisis invariants inv=2/11 module=x/crisis name=gov/module-account
4:09PM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/nonnegative-outstanding
4:09PM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/can-withdraw

**Comment by Vritra4** [comment]
Automated audits of the genesis state can take 30-120 min using the crisis module.
This can be disabled by `terrad start --x-crisis-skip-assert-invariants`

**Comment by qlfgggggg** [comment]
thank you,it works




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Geoff ***@***.***&gt;; 
发送时间: 2021年12月25日(星期六) 下午5:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [terra-money/core] [BUG] Unable to sync full-node data (Issue #638)





 
Automated audits of the genesis state can take 30-120 min using the crisis module.
 This can be disabled by terrad start --x-crisis-skip-assert-invariants
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
