### ISSUE TITLE
[BUG] Error: accepts between 2 and 3 arg(s), received 7

### ISSUE THREAD

**Issue by A56SN7** [terra-money/core#639]
I'm trying to send a swap tx with terraswaps contracts through the terracli but I keep getting this error "Error: accepts between 2 and 3 arg(s), received 7"

I sent this in the cli with the appropriate contracts added of course, and with my wallet that i've connected to the cli

Sent:
terrad tx wasm execute <token-sending-contract> {"send": {"contract": "<swap-pair-contract>","amount": "1000000","msg": "eyJzd2FwIjp7fX0="}} uusd --from <my-wallet-address>

received this back:
Error: accepts between 2 and 3 arg(s), received 7
Usage: terrad tx wasm execute [contract-addr-bech32] [json-encoded-args] [coins] [flags]

Using the public terra node 

Anybody know how to fix this?
Let me know if more info is needed, and if this is the wrong place to ask please direct me to a better place to get help

Thanks

**Comment by Vritra4** [comment]
set contract address, wrap json-encoded-arg with single quotation mark. and i don't think 3rd param(coins) is valid.
please see [swap by using cli](https://docs.terraswap.io/docs/howto/swap/#swap-by-using-cli).

**Comment by A56SN7** [comment]
The single quotation marks worked but now it says "Error: Invalid decimal coin expression: uusd" as you pointed out

So what is meant to be in that parameter?

Thanks for fixing the original issue!!

**Comment by A56SN7** [comment]
ok so now i'm getting some sort of insufficient fees issue

sent:

terrad tx wasm execute sendingtokencontract '{"send": {"contract": "paircontract","amount": "1000000","msg": "eyJzd2FwIjp7fX0="}}' 1000000uusd --from mywallet --chain-id columbus-5


receiving:

confirm transaction before signing and broadcasting [y/N]: y
code: 13
codespace: sdk
data: ""
events: []
gas_used: "0"
gas_wanted: "0"
height: "0"
info: ""
logs: []
raw_log: 'insufficient fees; got: "1946uusd", required: "105421uaud,96383ucad,69449uchf,491128ucny,480555udkk,64622ueur,55349ugbp,590169uhkd,1090000000uidr,5617131uinr,8337594ujpy,88703066ukrw,2640uluna,212335117umnt,662833unok,3800000uphp,53482usdr,662833usek,102915usgd,2516361uthb,77946uusd"
  = "105421uaud,96383ucad,69449uchf,491128ucny,480555udkk,64622ueur,55349ugbp,590169uhkd,1090000000uidr,5617131uinr,8337594ujpy,88703066ukrw,2640uluna,212335117umnt,662833unok,3800000uphp,53482usdr,662833usek,102915usgd,2516361uthb,76000uusd"(gas)
  +"1946uusd"(stability): insufficient fee'
timestamp: ""
tx: null

**Comment by Vritra4** [comment]
you have to fee directly or set params for calculation.
please see  [setting fees](https://docs.terra.money/Reference/terrad/#setting-fees)

**Comment by A56SN7** [comment]
I thought the coins parameter was for setting the fee, whats the number in front of the uusd then?

Sorry for all the stupid questions... I'm new to all this

Anyway i set the fee with --fees=1000000uusd and tx actually got to the blockchain!
but ran out of gas "out of gas in location: Contract Execution; gasWanted: 200000, gasUsed: 75520: out of gas"

I assume configuring the gas settings slightly differently will stop this?

**Comment by Vritra4** [comment]
3rd param is optional message that can be used in case you are sending native tokens along with the message. :)
