### ISSUE TITLE
[BUG] Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 1848, got 1847: incorrect account sequence: invalid request

### ISSUE THREAD

**Issue by A56SN7** [terra-money/core#643]
I’ve been doing swap txes through the cli but suddenly I’m getting this error:

Error: rpc error: code = InvalidArgument desc = account sequence mismatch, expected 1848, got 1847: incorrect account sequence: invalid request

Can anybody help out or know how to fix this?

Thanks

**Comment by YunSuk-Yeo** [comment]
If you want to make tx faster than block generation speed, you have to specify sequence number manually when you execute cmd.
