### ISSUE TITLE
I am having trouble synchronizing data

### ISSUE THREAD

**Issue by qlfgggggg** [terra-money/core#644]
I am currently using columbus-5.  I have synchronized 400,000 heigtht. I have used a hard disk with a size of 477G and synced an average of 100,000 pieces of data per day. I still have 700,000 pieces of data that have not been synchronized.Is it normal?

**Comment by qlfgggggg** [comment]
![image](https://user-images.githubusercontent.com/43543840/147622869-55b4cbe7-7698-4a5d-ad0f-821515ead418.png)

**Comment by masayil** [comment]
![image](https://user-images.githubusercontent.com/65291464/147647229-9ecf72a5-3cd3-4d0d-b5d7-b45a73416975.png)
I think it is normal

**Comment by hanjukim** [comment]
> I mean if this takes up too much hard drive or is too slow

It's both. Did you configure your node to `pruning = "nothing"`?

**Comment by qlfgggggg** [comment]
i havenot

**Comment by qlfgggggg** [comment]
everything: all saved states will be deleted, storing only the current state; pruning at 10 block intervals
custom: allow pruning options to be manually specified through 'pruning-keep-recent', 'pruning-keep-every', and 'pruning-interval'
are them ok?

**Comment by qlfgggggg** [comment]
pruning-keep-recent or pruning-keep-every ?

**Comment by qlfgggggg** [comment]
> 

this is only 400000 height. i have 700000 height still.

**Comment by qlfgggggg** [comment]
![image](https://user-images.githubusercontent.com/43543840/147652141-9fb96f85-1cee-446c-a3cf-830df420a33e.png)
It only takes up a small space.it is not main reason

**Comment by YunSuk-Yeo** [comment]
If you don't need historical data, you can use pruning everyting option. 
It save your DB, plus you can decrease tx_index.db size by restricting event index.

```
# IndexEvents defines the set of events in the form {eventType}.{attributeKey},
# which informs Tendermint what to index. If empty, all events will be indexed.
#
# Example:
# ["message.sender", "message.recipient"]
index-events = []
```

this part.

**Comment by YunSuk-Yeo** [comment]
If you just want to sync fast, you can use quick sync.

http://terra.quicksync.io
