### ISSUE TITLE
Why is `/txs/{hash}` deprecated?

### ISSUE THREAD

**Issue by boogerlad** [terra-money/core#646]
![image](https://user-images.githubusercontent.com/1903750/147710811-f4048c8c-8f08-406f-9e4a-efd10867c83b.png)
https://lcd.terra.dev/swagger/

this functionality is provided by the fcd, but it will be deprecated. https://github.com/terra-money/fcd/issues/150

I see it's present here, but deprecated as well. I `git blame`d and saw it was done here: https://github.com/terra-money/core/pull/468
but no comment about it.

am I supposed to use `/cosmos/tx/v1beta1/txs/{hash}`?

**Comment by Vritra4** [comment]
yes, you can use `/cosmos/tx/v1beta1/txs/{hash}`.

**Comment by boogerlad** [comment]
thanks. feel free to close if no work / documentation is needed.

**Comment by kjessec** [comment]
1. `/txs/{hash}` is __NOT__ provided by fcd. It is part of the native LCD stack.
2. cosmos-sdk dropped support for Amino codec and `/txs/{hash}` is using amino codec -- hence the deprecation. It will still work, but certain txs with Msgs that aren't serializable with Amino won't even load -- example https://lcd.terra.dev/txs/0FF55C82AB2F99EAE59CEAD16F6849ADFAF54973F00D889E6113A99F08082F1C
3. Likewise, all other endpoints that are amino-based are deprecated.
