### ISSUE TITLE
Description of error codes

### ISSUE THREAD

**Issue by boogerlad** [terra-money/core#647]
https://lcd.terra.dev/cosmos/tx/v1beta1/txs/675AF9010AA4B790B9644452B8C0ADDC09E833656E6EAF0A8B75BFE18FC3665B

`tx_response.code` is 11

https://lcd.terra.dev/cosmos/tx/v1beta1/txs/6F68AD70AA31E34A02B6E4D350934D5E863F2529BEF511275A239BB167D21B64

`tx_response.code` is 0. is that a success?

Is there any documentation on all the error codes?

**Comment by boogerlad** [comment]
ah, it is here: https://github.com/cosmos/cosmos-sdk/blob/master/types/errors/errors.go

**Comment by slashramin** [comment]
so 0 is success?
what is 1?
because errors start from 2 to 40
