### ISSUE TITLE
[BUG] terrad cli rpc.pprof_laddr parameter error

### ISSUE THREAD

**Issue by btfdip** [terra-money/core#650]
**Describe the bug**

![image](https://user-images.githubusercontent.com/96004784/147931304-364f8bcf-eab6-4097-b886-272a4d3fec73.png)

**To Reproduce**

terrad start --rpc.pprof_laddr tcp://127.0.0.1:36657 --address tcp://0.0.0.0:36658 --p2p.laddr tcp://0.0.0.0:36656

**Context & versions**

**0.5.14**

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by Vritra4** [comment]
remove `tcp://` for pprof_laddr. like`--rpc.pprof_laddr tcp://127.0.0.1:36657`
