### ISSUE TITLE
[BUG]: x/oracle integer overflow

### ISSUE THREAD

**Issue by alexanderbez** [terra-money/core#667]
**Describe the bug**

Validators may send large exchange rates, crashing other nodes via a panic due an integer overflow when performing ballot arithemetic via `sdk.Dec` types..

https://github.com/terra-money/core/blob/0909bd43523fe9a77009fc4526e093b5bb0fecd8/x/oracle/types/ballot.go#L144-L147

While there is overflow bound checks that exist on individual exchange rate votes, there isn't overflow checks on the computation performed above.

This probably isn't a real issue in practice, but I imagine there should probably be some safe guard checks around any sort of `sdk.Dec` or `sdk.Int` arithmetic where values are provided externally, i.e. exchange rate votes.

Original issue discovered by ToB during the audit of Umee's `x/oracle` fork.

**Comment by toteki** [comment]
`ApproxSqrt` method of `sdk.Dec` should be immune to overflow, and avoid the current parsing of `sdk.Dec`->`string`->`float64` in the `ExchangeRateBallot.StandardDeviation` method which can overflow on the last step.
