### ISSUE TITLE
[FEATURE] authz fine-grained control

### ISSUE THREAD

**Issue by Philipp-Sc** [terra-money/core#669]
**Problem definition**

I want to:
1) Create a new wallet for the user's bot.
2) Use Authz to authorize the user's bot wallet to only do what it is supposed to do.

if I understand this correctly: currently it is possible to authorize "wasm/MsgExecuteContract" (=MsgTypeURL) as GenericAuthorization, this is a little overkill. Other options are "gov/MsgVote", "market/MsgSwap", and it gives unrestricted permissions..

**Feature specification**
 I want only certain messages to be allowed (claim, repay_stable, deposit_stable, borrow_stable).
Also one can not set a single account to which MsgSend will be granted to send to. Currently a granted SendAuthorization gives the grantee the rights to send the coins to any account.

https://docs.terra.money/docs/develop/module-specifications/spec-authz.html
https://docs.cosmos.network/master/modules/authz/01_concepts.html#Authorization-and-Grant

**SendAuthorization**
Add an optional whitelist of accounts to SendAuthorization. If specified the coins can only be send to those accounts.

**GenericAuthorization**
Add an optional whitelist of execute_msg templates. E.g. claim, repay_stable, deposit_stable, borrow_stable.
If the execute_msg matches a whitelisted template it is passes the security check.

In combination with the above a whitelisted contract address is needed as well (e.g anchor mmMarket).

**Additional context**
I work on a terra-rust-bot, for open source to flurish there needs a good amount of trust, this authz extension would add a layer of security, even in cases of hacks the funds would be reasonably safe. 

Thank you for considering this, if I got it wrong and the feature is already there please let me know.

Best regards,
Philipp

**Comment by YunSuk-Yeo** [comment]
Yea it would be possible make `WasmAuthroization` type of message, but wasm has capability to implement authz with contract. 

so we can create authz contract which register authorization and do execute only when the permission is checked.

**Comment by Philipp-Sc** [comment]
Thank you for your reply.
Does this mean there is or will be a authz contract I can register the grants to and as a result all MsgExecuteContract broadcasts will automatically be checked if they are allowed?

Or do I need to create a contract myself, I am not sure how this works.

**Comment by YunSuk-Yeo** [comment]
Sorry for delayed response.
As I know, there is no authz contract yet, so you need to implement it.

**Comment by Philipp-Sc** [comment]
I see, thank you. I will consider doing that.

**Comment by Philipp-Sc** [comment]
I see, thank you. I will consider doing that.
