### ISSUE TITLE
[BUG] ballot winner reward is burnning

### ISSUE THREAD

**Issue by junbeomlee** [terra-money/core#675]
**Describe the bug**
```
// Mint seigniorage
func (k Keeper) SettleSeigniorage(ctx sdk.Context) {
  ...
  seigniorageCoin, _ := seigniorageDecCoin.TruncateDecimal()
  seigniorageCoins := sdk.NewCoins(seigniorageCoin)
  if seigniorageCoins.IsValid() {
    if err := k.bankKeeper.MintCoins(ctx, types.ModuleName, seigniorageCoins); err != nil {
	    panic(err)
    }
  }
  seigniorageAmt := seigniorageCoin.Amount
  
  // Send reward to oracle module
  burnAmt := rewardWeight.MulInt(seigniorageAmt).TruncateInt()
  burnCoins := sdk.NewCoins(sdk.NewCoin(core.MicroLunaDenom, burnAmt))
  if burnCoins.IsValid() {
    if err := k.bankKeeper.BurnCoins(ctx, types.ModuleName, burnCoins); err != nil {
	    panic(err)
    }
  }
  ...
}
```

**Comment by junbeomlee** [comment]
In the docs, it says that minted luna is sent to the ballot winner(oracle treasurey), but in the code, a part of minted luna is burned. Please explain this part.

**Comment by YunSuk-Yeo** [comment]
I think that part is `oracle`

https://github.com/terra-money/core/blob/293b023a3fb6871e3bb45a5a3f88919d12ce9200/x/oracle/keeper/reward.go#L15

**Comment by YunSuk-Yeo** [comment]
And we changed our logic to make oracle rewards from swap fee
https://github.com/terra-money/core/blob/293b023a3fb6871e3bb45a5a3f88919d12ce9200/x/market/keeper/msg_server.go#L118-L125

so, when user do swap, the swap spread will be sent to oracle module for oracle rewards

**Comment by YunSuk-Yeo** [comment]
references:
https://agora.terra.money/t/proposal-to-burn-all-seigniorage/438
https://agora.terra.money/t/adjusting-terra-seigniorage-distribution/410/14

"
After [Columbus-5 294](https://agora.terra.money/t/tfl-engr-priorities-for-q1-2021/388), additional logic will be introduced to route swap fees for stablecoins to the oracle reward pool instead of burning it - this will keep Luna staking attractive, while the narrative of burning all seigniorage and routing all fees to Luna staking will help the system become much easier to understand.
"

**Comment by junbeomlee** [comment]
Thank you for answer. Then let me ask you another questions. After columbus-5, it says that all seignoriage is burned which means reward_weight to be 1.

But in the code it updates rewardWeight with this equation `w(t+1) = w(t)*SB_target/SB_rolling(t)`
```
rewardWeight := k.UpdateRewardPolicy(ctx)
```
Please explain how the reward weight can be fixed at 1.

**Comment by YunSuk-Yeo** [comment]
@junbeomlee 

https://lcd.terra.dev/treasury/parameters
```json
{
"reward_policy": {
    "rate_min": "0.000000000000000000",
    "rate_max": "1.000000000000000000",
    "cap": {
      "denom": "unused",
      "amount": "0"
    },
    "change_rate_max": "0.000000000000000000"
  }
}
```

we changed reward weight to `0` with proposal and also changed reward policy params like above, so it should be fixed to `0` because `change_rate_max` == 0.
