### ISSUE TITLE
[BUG] Windows 10 WSL make error, contrib/devtools/Makefile:64: *** target pattern contains no '%'.  Stop.

### ISSUE THREAD

**Issue by raxuser100** [terra-money/core#676]
**Describe the bug**
executing terminal command `make install`, generates error:

`contrib/devtools/Makefile:64: *** target pattern contains no '%'.  Stop.`

**To Reproduce**
Windows 10, vanilla clone of repo, WSL2 installed (windows subsystem for Linux, using Ubuntu).
open command window in Admin mode, at root of terra_core directory
run `wsl`
at WSL Unix terminal prompt run:
`make install`

**I am running Windows 10 on a AMD Ryzen 7. All I need is the release binaries for terrad, please can anyone send me these?**

**Context & versions**
[v0.5.16] (https://github.com/terra-money/core/releases/tag/v0.5.16)

**(if applicable) suggested solution**
Not sure!

**Comment by YunSuk-Yeo** [comment]
windows not yet supported :(

https://github.com/cosmwasm/wasmvm
When we bump wasmer to latest, then we can support this.
