### ISSUE TITLE
[BUG] Terra servers do not handle the height parameter correctly

### ISSUE THREAD

**Issue by Green7** [terra-money/core#677]
I want to ask about the luna price for a given block.

So I'm sending a request with the height parameter:

`curl -v -X GET "https://lcd.terra.dev/terra/oracle/v1beta1/denoms/uusd/exchange_rate" -H "accept: application/json" -H "x-cosmos-block-height: 6183000" `

The answer is: 
`{
  "exchange_rate": "66.613907790920271024"
}`

Ok, but I'm sending this same request one more time, and the answer is different !
`{
  "exchange_rate": "55.521013575501721436"
}`

So I guess: one of the Terra servers is misconfigured and doesn't support the height parameter (or the problem is with the cloudflare configuration?).
The same problem also occurs on the testnet.

**The second thing related to this problem:**

In responses from Terra servers there is no header "Grpc-Metadata-X-Cosmos-Block-Height:" (as it is in localterra case)
For this reason, when we send a request with the height parameter, it is not possible to determine whether we received the right response. I think that should also be corrected ...

**Comment by YunSuk-Yeo** [comment]
our public infra https://lcd.terra.dev/ is using `mantle` to handle query, so maybe mantle need to support this feature.
Can you reopen this on https://github.com/terra-money/mantlemint

**Comment by YunSuk-Yeo** [comment]
Seems mantlemint is private yet, so will open this until mantlemint be public

**Comment by hanjukim** [comment]
The only solution at the moment is to run your own node for querying state with a specific height.

**Comment by kjessec** [comment]
@Green7 we've rolled out fully archival mode to all our networks.

**Comment by Green7** [comment]
@kjessec I checked and nothing has changed. I keep getting mixed results - exactly as before.
Also please set 'grpc-metadata-x-cosmos-block-height' header - without this I can't be sure that result is correct.

**Comment by josh-burton** [comment]
So if this is supported can you please detail how to specify a block height for a rest or mantle query?

**Comment by Green7** [comment]
As I wrote above:
```
curl -X GET "https://lcd.terra.dev/terra/oracle/v1beta1/denoms/uusd/exchange_rate" -H "accept: application/json" -H "x-cosmos-block-height: 6183000"
{
  "exchange_rate": "66.613907790920271024"
}

curl -X GET "https://lcd.terra.dev/terra/oracle/v1beta1/denoms/uusd/exchange_rate" -H "accept: application/json" -H "x-cosmos-block-height: 6183000"
{
  "exchange_rate": "98.297266063136446293"
}
```

Send this query several times and you will see that you will get different results as in the example above.
