### ISSUE TITLE
wrong Block.Header.LastResultsHash.  Expected A48C0818A191697E7E31819C3593C096637339E4B90C117790FDEAAEF6671DB2, got 3B010C74970DC920DAD8A0532F11D2546831CF321875A5F3F6FAA6553213637C

### ISSUE THREAD

**Issue by qlfgggggg** [terra-money/core#679]
5:04PM INF Starting IndexerService service impl=IndexerService module=txindex
5:04PM INF ABCI Handshake App Info hash="W�\x158}k��\x10\x06�\x18\x19ްhz�ա�;@B{\x0e\\鳹�u" height=6470000 module=consensus protocol-version=0 software-version=0.5.14
5:04PM INF ABCI Replay Blocks appHeight=6470000 module=consensus stateHeight=6470000 storeHeight=6470001
5:04PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected A48C0818A191697E7E31819C3593C096637339E4B90C117790FDEAAEF6671DB2, got 3B010C74970DC920DAD8A0532F11D2546831CF321875A5F3F6FAA6553213637C

**Comment by YunSuk-Yeo** [comment]
Seems you missed softfork.
You need to resync data or use quicksync.

**Comment by qlfgggggg** [comment]
can i rollback 6470000 ? and how rollback ?

**Comment by qlfgggggg** [comment]
> Seems you missed softfork. You need to resync data or use quicksync.
> 
> https://github.com/terra-money/core/releases/tag/v0.5.16

i do not want to resync data or use quicksync

**Comment by AlexZhenWang** [comment]
Hi @YunSuk-Yeo we just get the same issue, may I ask the root cause of this issue and is there any way we can fix the nodes without resyncing the node? Thanks!

**Comment by zukamedia** [comment]
@YunSuk-Yeo is the re-sync mandatory to fix, please clarify clearly before closing the issue.
