### ISSUE TITLE
Missing terra_2.1.1_Darwin_x86_64.tar.gz

### ISSUE THREAD

**Issue by vedova** [terra-money/core#68]
Missing [terra_2.1.1_Darwin_x86_64.tar.gz](https://github.com/terra-money/core/releases/download/v2.1.1/terra_2.1.1_Darwin_x86_64.tar.gz for MacOS Intel/Apple

@YunSuk-Yeo Any plan to make it available?

terra_2.1.0_Darwin_x86_64.tar.gz is the last available

**Comment by Vritra4** [comment]
done! you can get [v2.1.1 for darwin x86_64](https://github.com/terra-money/core/releases/download/v2.1.1/terra_2.1.1_Darwin_x86_64.tar.gz).
