### ISSUE TITLE
[BUG] LCD fails to catch certain MsgSend tx

### ISSUE THREAD

**Issue by LCyson** [terra-money/core#682]
Sme of the MsgSend txs (by Cosmos bank module) are not returned when we query the endpoint:
```
http://<our-lcd-endpoint>/cosmos/tx/v1beta1/txs?events=message.sender%3D'terra1669gafqx9wv0cjahdkyqz0ehh5793t4rxvnvw3'&order_by=ORDER_BY_UNSPECIFIED
```
for example, for account terra1669gafqx9wv0cjahdkyqz0ehh5793t4rxvnvw3, [this](https://finder.terra.money/mainnet/tx/A0B316CCA48052534B6CBA8A29B21A1BE24E78FC6EE2E668EFA8656C59F104C0 ) MsgSend tx is not returned

**Comment by YunSuk-Yeo** [comment]
I think that is due to `terra1669gafqx9wv0cjahdkyqz0ehh5793t4rxvnvw3` address is recipient not sender.
can you try with `message.recipient`?

**Comment by BranfordSWBF** [comment]
That didn't seem to fix it

curl -X 'GET' "http://44.234.57.250:1317/cosmos/tx/v1beta1/txs?events=message.recipient%3D'terra1669gafqx9wv0cjahdkyqz0ehh5793t4rxvnvw3'&order_by=ORDER_BY_UNSPECIFIED" -H "accept: application/json" {
  "txs": [
  ],
  "tx_responses": [
  ],
  "pagination": {
    "next_key": null,
    "total": "0"
  }
}

**Comment by BranfordSWBF** [comment]
@YunSuk-Yeo

**Comment by Vritra4** [comment]
first one is partially encoded(').
try this:
`curl http://{LCD_IP}/cosmos/tx/v1beta1/txs\?events\=message.sender%3D%27terra1669gafqx9wv0cjahdkyqz0ehh5793t4rxvnvw3%27`

**Comment by BranfordSWBF** [comment]
the tx linked is still missing

**Comment by hanjukim** [comment]
curl -X GET "http://localhost:1317/cosmos/tx/v1beta1/txs?events=message.sender%3D'terra1mpueafs7jf8thn9hkcu6rt2upv0tk5463zspf3'&order_by=ORDER_BY_UNSPECIFIED" -H "accept: application/json"

Works fine
