### ISSUE TITLE
Wasmer Issue Tracking

### ISSUE THREAD

**Issue by YunSuk-Yeo** [terra-money/core#683]
## Memory leak

Reusing wamser's `module` is definitely causing memory leak but this adoption comes from performance improvement. 

- https://github.com/wasmerio/wasmer/issues/2780
- https://github.com/wasmerio/wasmer/issues/1933
- https://github.com/CosmWasm/cosmwasm/issues/603

When we rollback cosmwasm cache to store serialized `artifact`, memory leak is gone.
https://github.com/terra-money/cosmwasm/commit/16eae76a2573a7af2f9dcdd02ac0a37cf45ec35e

## Frame error (aka. Poison error)

- https://github.com/wasmerio/wasmer/issues/2434#issuecomment-1032435928

## Wasmer bump related issues 

The file cache created from `wasmer@v2.0.0` cannot be used from `wasmer@v2.1.x` or `wasmer@v2.2.x`.
- https://github.com/wasmerio/wasmer/issues/2781

**Comment by YunSuk-Yeo** [comment]
When we revert `CosmWasm` cache to use serialization again, the performance degradation seems huge

```shell
Cache/instantiate from fs                                                                            
                        time:   [3.8578 ms 4.0083 ms 4.1232 ms]
                        change: [-33.227% -30.126% -27.424%] (p = 0.00 < 0.05)
                        Performance has improved.
Cache/instantiate from memory                                                                            
                        time:   [2.5783 ms 2.6381 ms 2.6863 ms]
                        change: [+3559.6% +3718.3% +3840.8%] (p = 0.00 < 0.05)
                        Performance has regressed.
Cache/instantiate from pinned memory                                                                            
                        time:   [2.5794 ms 2.6677 ms 2.7162 ms]
                        change: [+3755.9% +3851.0% +3920.2%] (p = 0.00 < 0.05)
                        Performance has regressed.
```

**Comment by YunSuk-Yeo** [comment]
To avoid performance degradation, changed cache strategy to cache both artifact and module and refresh cached module from a background thread with cached artifact - https://github.com/terra-money/cosmwasm/commit/78026fde265b6ebd3e841bf95c6ea6e12ccbecbe

- Load
If we have `refresh` background thread, then just return cached module.
If we don't have `refresh` background thread, then create `refresh` thread and return cached module.

`refresh` thread deserializes artifact into module and replace cached module.

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)
