### ISSUE TITLE
[BUG] Expected A48C0818A191697E7E31819C3593C096637339E4B90C117790FDEAAEF6671DB2, got 3B010C74970DC920DAD8A0532F11D2546831CF321875A5F3F6FAA6553213637C

### ISSUE THREAD

**Issue by intl-man** [terra-money/core#684]
**Describe the bug**
After missing the soft fork on the 14th, I downloaded the archive snapshot from QuickSync. Starting the daemon gives me:

```console
8:31AM INF starting ABCI with Tendermint
8:32AM INF Starting multiAppConn service impl=multiAppConn module=proxy
8:32AM INF Starting localClient service connection=query impl=localClient module=abci-client
8:32AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
8:32AM INF Starting localClient service connection=mempool impl=localClient module=abci-client
8:32AM INF Starting localClient service connection=consensus impl=localClient module=abci-client
8:32AM INF Starting EventBus service impl=EventBus module=events
8:32AM INF Starting PubSub service impl=PubSub module=pubsub
8:32AM INF Starting IndexerService service impl=IndexerService module=txindex
8:32AM INF ABCI Handshake App Info hash="W�\x158}k��\x10\x06�\x18\x19ްhz�ա�;@B{\x0e\\鳹�u" height=6470000 module=consensus protocol-version=0 software-version=0.5.16
8:32AM INF ABCI Replay Blocks appHeight=6470000 module=consensus stateHeight=6470000 storeHeight=6470001
8:32AM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected A48C0818A191697E7E31819C3593C096637339E4B90C117790FDEAAEF6671DB2, got 3B010C74970DC920DAD8A0532F11D2546831CF321875A5F3F6FAA6553213637C
```

**To Reproduce**
Download the latest quicksync.io [archive](https://dl2.quicksync.io/columbus-5-archive.20220214.1010.tar.lz4), restore and start `terrad`.

**Context & versions**
`terrad: v0.5.16`

**Comment by hanjukim** [comment]
Seems like Quicknode snapshot is broken as well.

**Comment by intl-man** [comment]
@hanjukim Yeah, it seems that's the case. Are there any other archive snapshots available?

**Comment by hanjukim** [comment]
We are making one now. It will be available in a few days. Please follow up @Vritra4

**Comment by intl-man** [comment]
> We are making one now. It will be available in a few days. Please follow up @Vritra4

Great. Many thanks @hanjukim @Vritra4.

**Comment by intl-man** [comment]
@Vritra4 - any update on this?

**Comment by Vritra4** [comment]
@intl-man almost done. :) i'll share you a link asap.

**Comment by intl-man** [comment]
@Vritra4 - just pinging you on the above again. Thanks.

**Comment by Vritra4** [comment]
@intl-man done! https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/pruneless.220225.tar.lz4

**Comment by zukamedia** [comment]
@intl-man did the new snapshot work for you, I have the same issue. Thanks.

**Comment by intl-man** [comment]
> @intl-man did the new snapshot work for you, I have the same issue. Thanks.

Still downloading. Will let you know.

**Comment by clement-fischer** [comment]
The new snapshot seem to be missing some data, some transactions can't be queried.

One example is transaction FA77A0B2C0C2EF1BAEAD14277D0EE779F5CF4BF53244A777759755C9001ED64B. The transaction is included in block #5616798, but the TxResult for the transaction cannot be retrieved (from Tendermint I believe), and so it is not possible to know if the transaction was reverted or not.

I used the following download link: https://getsin.quicksync.io/columbus-5-default.20220225.0310.tar.lz4

I tried using the gRPC endpoint and with CLI, got the same result:
```
$ curl localhost:1317/txs/FA77A0B2C0C2EF1BAEAD14277D0EE779F5CF4BF53244A777759755C9001ED64B
{"error":"tx (FA77A0B2C0C2EF1BAEAD14277D0EE779F5CF4BF53244A777759755C9001ED64B) not found"}
```

**Comment by Vritra4** [comment]
@clement-fischer 'default' means historical data is pruned by policy of quicksync's node. if you need whole txs, try archived one like https://columbus-genesis.s3.ap-northeast-1.amazonaws.com/pruneless.220225.tar.lz4

**Comment by clement-fischer** [comment]
@Vritra4 thank you! I couldn't find a link to an archive snapshot on Terra docs for Colombus-5. Quicksync only has `default` and `pruned`. It would be useful if the docs included some links to archival snapshots.

I'm curious though, I was able to process pretty much all transactions since Colombus-5 genesis, except for a few transactions (<50 for the whole history), so I thought the `default` snapshot did contain all the data that I want, and the exceptions were the result of a bug (such as this one: https://github.com/tendermint/tendermint/issues/5851). Isn't this correct?

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)

**Comment by intl-man** [comment]
@Vritra4 - this could probably be closed, as the original issue has actually been resolved.
