### ISSUE TITLE
[BUG] panic: SetIndex requires index to not be set

### ISSUE THREAD

**Issue by scrawld** [terra-money/core#691]
[root@bc-gcp-sg-test-node02 config]# terrad start --home /data/luna_data
5:04PM INF starting ABCI with Tendermint
5:04PM INF Starting multiAppConn service impl=multiAppConn module=proxy
5:04PM INF Starting localClient service connection=query impl=localClient module=abci-client
5:04PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client
5:04PM INF Starting localClient service connection=mempool impl=localClient module=abci-client
5:04PM INF Starting localClient service connection=consensus impl=localClient module=abci-client
5:04PM INF Starting EventBus service impl=EventBus module=events
5:04PM INF Starting PubSub service impl=PubSub module=pubsub
5:04PM INF Starting IndexerService service impl=IndexerService module=txindex
5:04PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 software-version=0.5.17
5:04PM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=4724001
panic: SetIndex requires index to not be set

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/capability/keeper.Keeper.InitializeIndex({{_, _}, {_, _}, {_, _}, _, _, _}, {{0x2944be8, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/capability/keeper/keeper.go:155 +0x1e5
github.com/cosmos/cosmos-sdk/x/capability.InitGenesis({{0x2944be8, 0xc000134020}, {0x2972c40, 0xc000cf0380}, {{0x0, 0x0}, {0xc0010ea140, 0xa}, 0x481521, {0x0, ...}, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/capability/genesis.go:12 +0xf8
github.com/cosmos/cosmos-sdk/x/capability.AppModule.InitGenesis({{{0x2979178, 0xc001087f90}}, {{0x296d778, 0xc001087f90}, {0x290fa50, 0xc000ccb830}, {0x290fa78, 0xc000ccb8d0}, 0xc0011e0c30, 0xc0011e0c60, ...}}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/x/capability/module.go:130 +0x17c
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2944be8, 0xc000134020}, {0x2972c40, 0xc000cf0380}, {{0x0, 0x0}, {0xc0010ea140, 0xa}, 0x481521, ...}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/types/module/module.go:307 +0x29d
github.com/terra-money/core/app.(*TerraApp).InitChainer(_, {{0x2944be8, 0xc000134020}, {0x2972c40, 0xc000cf0380}, {{0x0, 0x0}, {0xc0010ea140, 0xa}, 0x481521, ...}, ...}, ...)
        github.com/terra-money/core/app/app.go:602 +0x129
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0011ea820, {{0x0, 0xed8e781c9, 0x0}, {0xc0010ea140, 0xa}, 0xc000d0c860, {0xc00014f900, 0x82, 0x82}, ...})
        github.com/cosmos/cosmos-sdk@v0.44.5/baseapp/abci.go:62 +0x475
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc001042ea0, {{0x0, 0xed8e781c9, 0x0}, {0xc0010ea140, 0xa}, 0xc000d0c860, {0xc00014f900, 0x82, 0x82}, ...})
        github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0xb3, {{0x0, 0xed8e781c9, 0x0}, {0xc0010ea140, 0xa}, 0xc000d0c860, {0xc00014f900, 0x82, 0x82}, ...})
        github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0001344d0, 0x7}}, {0xc0001344f0, 0xa}, 0x481521, 0x0, {{0x0, ...}, ...}, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000d1be50, {0x29740a0, 0xc000114270})
        github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0001344d0, 0x7}}, {0xc0001344f0, 0xa}, 0x481521, 0x0, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0010f8c80, {0x291e810, 0xc0011e5a40}, 0xc00116e720, {0x2900fa0, 0xc00126c0d8}, 0x0, 0x0, 0xc00116e910, {0x2945908, ...}, ...)
        github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2985a58, 0xc0011e14d0}, {0x0, 0x0}, {0x294e210, 0xc001087f90}, ...}, ...)
        github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:269 +0x765
github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc001129180, {0xc0011474a0, 0x0, 0x2})
        github.com/cosmos/cosmos-sdk@v0.44.5/server/start.go:133 +0x193
github.com/spf13/cobra.(*Command).execute(0xc001129180, {0xc001147480, 0x2, 0x2})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc0010fc000)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        github.com/spf13/cobra@v1.2.1/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc001021950, 0xc})
        github.com/cosmos/cosmos-sdk@v0.44.5/server/cmd/execute.go:36 +0x1eb
main.main()
        github.com/terra-money/core/cmd/terrad/main.go:15 +0x2c

**Comment by YunSuk-Yeo** [comment]
hmm which genesis did you use?
