### ISSUE TITLE
[BUG] Someone keep spamming the network

### ISSUE THREAD

**Issue by ivanfong01** [terra-money/core#692]
**Describe the bug**
I keep monitoring the mempool of Terra recently, and found a address "terra13av2nsaswaltuzrjra48akw7vx3xp08qjl7v7g" constantly issuing Tx that never pass CheckTx() but keep broadcasting in the network, seems due to some poor bot implementation

**To Reproduce**
just go check the mempool

**Context & versions**
not related to any version

**(if applicable) suggested solution**
should we implement any measures to block nodes that keep broadcasting invalid Tx?

**Comment by lopezj19** [comment]
> **Describe the bug** I keep monitoring the mempool of Terra recently, and found a address "terra13av2nsaswaltuzrjra48akw7vx3xp08qjl7v7g" constantly issuing Tx that never pass CheckTx() but keep broadcasting in the network, seems due to some poor bot implementation
> 
> **To Reproduce** just go check the mempool
> 
> **Context & versions** not related to any version
> 
> **(if applicable) suggested solution** should we implement any measures to block nodes that keep broadcasting invalid Tx?

Hello, A support ticket has been opened for you with Support ticket number TM1939. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by hanjukim** [comment]
This is not a bug.
