### ISSUE TITLE
[BUG] Parallel query support for gRPC

### ISSUE THREAD

**Issue by connorwstein** [terra-money/core#694]
**Problem definition**
I'm observing the same issue described here https://github.com/cosmos/cosmos-sdk/issues/10859 when querying a terra node version v0.5.17, gRPC queries are not able to run in parallel against the node (nor are RPC queries). This is causing scalability problems: we experience high latency and our nodes fall behind on blocks if we query too much. 

**Feature specification**
Is there a way we can support parallel queries?

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)

**Comment by hanjukim** [comment]
We've tried to remove locks here and there, but the sdk was not designed to be friendly with the parallelism. https://github.com/terra-money/mantlemint is your best shot. In fact, we redirect almost all queries (including wasm) to mantlemint cluster in our public infrastructure.
