### ISSUE TITLE
Does CI's simulation test work?

### ISSUE THREAD

**Issue by hea9549** [terra-money/core#695]
I think some test in `.github/workflows/sims.yml` like   `test-sim-import-export` is not work.

`make test-sim-import-export` checks `TestAppImportExport` using below make file
```
test-sim-import-export: runsim
	@echo "Running application import/export simulation. This may take several minutes..."
	@$(BINDIR)/runsim -Jobs=4 -SimAppPkg=$(SIMAPP) -ExitOnFail 50 5 TestAppImportExport
```

but terra-money SimAppPackage(./app) test file does not contain `TestAppImportExport` function.

so test is started in CI but stdOut probably print below message.
```
testing: warning: no tests to run
PASS
```

Please let me know if I'm wrong.

**Comment by DevElliett** [comment]
Hello A support ticket has been opened for you. Talk to a Terra Network Dev on the [Live support page](https://terrasupport.org/)so that your issue can be looked into. [CLICK HERE](https://terrasupport.org/)

**Comment by DevElliett** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support [CLICK HERE](https://terrasupport.org/)

**Comment by YunSuk-Yeo** [comment]
@hea9549 Thanks for checking.

The `TestAppImportExport` is in cosmos side [sim_test.go](https://github.com/cosmos/cosmos-sdk/blob/master/simapp/sim_test.go) and also checked ci is working well :)
