### ISSUE TITLE
Can't sync historical data from older chains

### ISSUE THREAD

**Issue by HussienAbdelaal** [terra-money/core#697]
**Describe the bug**
I'm working on an enterprise version blockchain explorer. I'm currently running an archival full node and its successfully syncing with Columbus-5 network.
However, I'm unable to sync with the previous networks (Columbus 1,2,3 or 4) to fetch their data: the first 4,724,000 blocks

**To Reproduce**
I followed the steps mentioned in [Columbus-4 upgrade instructions](https://github.com/terra-money/mainnet/wiki/Columbus-4-Upgrade-Instructions) trying to sync with Columbus-4 network but it got stuck at `INF starting ABCI with Tendermint` for a long time (about 24 hours). so couldn't get it to start.

**Context & versions**
I'm using an ubuntu 20 instance which successfully runs Columbus-5 network with core version 0.5.17
When trying to run Columbus-4 network I used the same ubuntu instance with core version 0.4.6

**(if applicable) suggested solution**

**Comment by TonyCrypto** [comment]
I'm interested in the same issue, which is how can I get the data for the first 4,724,000 blocks from the network itself?

**Comment by YunSuk-Yeo** [comment]
To be synced, we need other full node which have whole block data.

**Comment by TonyCrypto** [comment]
> To be synced, we need other full node which have whole block data.

How can one `get other full node which have whole block data`. The answer provided doesn't solve the issue. Is there any ` full node which have whole block data` that's avaialble to get snapshot from, like on AWS or other cloud storage, or maybe even through some scp?
