### ISSUE TITLE
[BUG] Terrad can't be installed on Mac | Deprecated dependencies

### ISSUE THREAD

**Issue by vvllxxdd** [terra-money/core#698]
<img width="1304" alt="Screenshot 2022-03-25 at 14 31 44" src="https://user-images.githubusercontent.com/54439346/160121295-25738c50-d14c-4ee2-a758-8349aa8403c1.png">
**Describe the bug**
I tried everything I found on all issues, all terra forums about installing terrad, but I keep getting the errors from the the attached screenshot in the terminal.

**To Reproduce**
Follow the install instructions from https://docs.terra.money/docs/develop/how-to/terrad/install-terrad.html on a Mac

**Context & versions**
Latest and about 10 versions earlier tried, none of them work.

Solutions that are NOT useful: "Use LocalTerra". I need access to the mainnet, if I would've wanted a localnet I wouldn't be here.

**Comment by Annie4556** [comment]
Hello @vvllxxdd  This is a mainnet related issue, for swift solution. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA DEVELOPERS LIVE CHAT](https://agora.terras.live/) To help you sort this out right away

**Comment by vvllxxdd** [comment]
> Hello @vvllxxdd This is a mainnet related issue, for swift solution. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the Forum ——>> [TERRA DEVELOPERS LIVE CHAT](https://agora.terras.live/) To help you sort this out right away

Nice try, scammer. For anyone looking for an answer this is not it, this 1-month-old account posted a fake link to terra's agora

**Comment by Vritra4** [comment]
they are just warnings.. you can find terrad in your $GOBIN or $GOPATH/bin

**Comment by vvllxxdd** [comment]
> they are just warnings.. you can find terrad in your $GOBIN or $GOPATH/bin

Unfortunately I can't. 
`terrad --version` prints "command not found" and I have the feeling this is a known but ignored issue

**Comment by Tumhen** [comment]
Terra Network Live Support.
We received your request kindly visit the official website to chat With a live support [CLICK HERE] (https://terrasupports.org/)

**Comment by lopezj19** [comment]
> > they are just warnings.. you can find terrad in your $GOBIN or $GOPATH/bin
> 
> Unfortunately I can't. `terrad --version` prints "command not found" and I have the feeling this is a known but ignored issue

Hello, A support ticket has been opened for you with Support ticket number TM1738. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by YunSuk-Yeo** [comment]
Will consider this issue resolved due to inactivity - let us know if otherwise
