### ISSUE TITLE
[BUG] Unable active Rosetta API with Pruned Snapshot

### ISSUE THREAD

**Issue by joslee7410** [terra-money/core#699]
Good day Terrad,

TERRAD VERSION: `0.5.17`
NETWORK: `mainnet`

Trying to build a Pruned node and running with Rosetta.
But it failed and having `502 Bad Gateway Rosetta` error.

Able to run with `default snapshot` / `archive snapshot`

**Comment by Vritra4** [comment]
you can build it from `feature/rosetta` branch.
current cosmos-sdk has a problem with timeout.  that branch uses forked/fixed cosmos-sdk.

**Comment by joslee7410** [comment]
> you can build it from `feature/rosetta` branch. current cosmos-sdk has a problem with timeout. that branch uses forked/fixed cosmos-sdk.

So this only will affect `pruned snapshot` right? Just wondering is my building steps problem or bug.

**Comment by Vritra4** [comment]
no, default cosmos-sdk won't work with any type of snapshots i guess. 
rosetta is a part of cosmos-sdk and it has timeout to load genesis blocks and states. but snapshots are too large to load in time :(
[fix](https://github.com/cosmos/cosmos-sdk/pull/10766) is not merged yet so i suggested the branch.

**Comment by Tumhen** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support for further assistance Click Here

**Comment by lopezj19** [comment]
> Good day Terrad,
> 
> TERRAD VERSION: `0.5.17` NETWORK: `mainnet`
> 
> Trying to build a Pruned node and running with Rosetta. But it failed and having `502 Bad Gateway Rosetta` error.
> 
> Able to run with `default snapshot` / `archive snapshot`

Hello, A support ticket has been opened for you with Support ticket number TM1739. You should talk to a Terra-money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by YunSuk-Yeo** [comment]
Will consider this issue resolved due to inactivity - let us know if otherwise
