### ISSUE TITLE
[BUG] out of gas: invalid request

### ISSUE THREAD

**Issue by roccomuso** [terra-money/core#700]
any hint about this error?

"out of gas in location: Loading CosmWasm module: query; gasWanted: 0, gasUsed: 40070: out of gas: invalid request"

How to fix this? what is causing this? any clue?

**Comment by Annie4556** [comment]
Hi @roccomuso This is a mainnet related issue, for swift solution. I will suggest you contact Terra support and talk with a Developer from Terra through their live chat Developers forum. Click on the  Forum ——>> [TERRA DEVELOPERS LIVE CHAT ](https://agora.terras.live/) To help you sort this out right away
