### ISSUE TITLE
Installation Help

### ISSUE THREAD

**Issue by RylandCapital** [terra-money/core#701]
No bug, but looking for some general help with installation. I have been using fcd.terra.dev and lcd.terra.dev but wanted to run my own node locally to make queries. I have installed terrad on linux.

info ->
Ubuntu 18.04 
name: terra
server_name: terrad
version: 0.5.17
commit: a6b93b72a7d4fabbbb85fb89e685426f5d07cac1
build_tags: netgo muslc,
go: go version go1.17.7 linux/amd64
build_deps:
[then lists a long list of dependencies]

Steps to reproduce (i used quicklaunch)-> 
1)  ./terrad init nodename
2)  pulled genesis.json
3) ./terrad start 

I ended terrad and edited the app.toml file to endable LCD and REST API. then ran ./terrad start again. looks like this ->
![image](https://user-images.githubusercontent.com/16804873/160721993-072db2b2-eb2e-4626-8a54-cee75a199d13.png)

1. Simply does that look right, is that running on col-5 (get kind of lost in docs after quickstart)?
2. I am trying to make this call "https://lcd.terra.dev/node_info" but on my node just see if its working. if it is working, would I call https://localhost:1317/node_info ?

anything helps. sorry to bother you with this.

**Comment by robiso50** [comment]
Hello @RylandCapital  , A support ticket has been opened for you with Support ticket number TB78326HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)

**Comment by Vritra4** [comment]
1.  you should add addrbook to find other peers. see: https://github.com/terra-money/mainnet
2. set `api.enable` to true in `config/app.toml`

**Comment by RylandCapital** [comment]
@Vritra4 thank you so much!

1. looks like I am connected (the node_info call works atleast).
2. Now I just want to be connected to mainnet which I am guessing is the addrbook and the link you provided. trying now. 

thanks again for your time

![image](https://user-images.githubusercontent.com/16804873/160807149-54d2fae1-214e-4a48-9d51-627b5c5a1c89.png)

**Comment by Vritra4** [comment]
@RylandCapital 
`/node_info` works even you are not connected and 'No addresses to dial' means you are not connected.
run `curl https://network.terra.dev/addrbook.json > ~/.terra/config/addrbook.json` and restart terrad please. :)
you can see blocks commited with `/blocks/latest`

**Comment by RylandCapital** [comment]
@Vritra4 BOOM . thank you sir. looks like its indexing old blocks and catching up?
![image](https://user-images.githubusercontent.com/16804873/160889241-0c14f412-dc20-4824-8469-006882f30491.png)

**Comment by RylandCapital** [comment]
@Vritra4 do you have a terrastation wallet I can send some UST to for you time?

**Comment by Vritra4** [comment]
@RylandCapital yes, but you should wait 2~3weeks to catch up. :(
you can use snapshots: it's much faster than sync from genesis : https://quicksync.io/networks/terra.html would be helpful.

**Comment by RylandCapital** [comment]
haha I was just doing the math in my head, and I was like wow this going to take a while lol. I will look into quicksync!

**Comment by Tumhen** [comment]
Terra Network Live Support.
We received your complain kindly visit the official website to chat With a live support for further assistance [Click Here](https://terrasupports.org/)

**Comment by YunSuk-Yeo** [comment]
> Sorry to intrude but I'm having trouble setting up terra's cli as well. I swear Terra has the worst docs and dev support of all blockchains. After weeks of searching how to solve terrad's installation problems, I'm now stuck on configuring it to actually interact with the mainnet. Did everything I found on github, docs and forums, but can't seem to figure it out. I can't even recall all the steps and configurations i did anymore. What I currently struggle with, but i'm sure it will not be the last thing i don't find in docs, is how to connect to a node to actually query the mainnet. `terrad status` prints this:
> 
> ```
> Error: post failed: Post "http://localhost:26657": dial tcp [::1]:26657: connect: connection refused
> Usage:
> ```
> 
> Tried editing config.toml, app.toml but nothing from the docs seems to work.
> 
> All I wanted, coming from EVM's and Solana was to install terrad, create a JSON wallet and interact with the blockchain. But 3 weeks and countless docs and articles read, here I am, barely installed it. Is there anywhere a step-by-step guide on how to do this? Because the Terra docs seem written by someone that forgot he/she needs to explains things to people who are not actually full-time terra developers.
> 
> Regarding the wallet itself, at some point, i did `terrad keys add ...` and received an address, but I can't find anywhere it's mnemonic key or private in order to actually use on the blockchain

Sorry for your inconvenience. 
Can you make suggestion here https://github.com/terra-money/docs? They can reflect your suggestion.

**Comment by abbatepabloo** [comment]
@vvllxxdd Did you solve the 'connection refused' error? I'm facing the same issue, but in my case, I'm using a docker container.
