### ISSUE TITLE
[BUG] events: nil pointer dereference

### ISSUE THREAD

**Issue by mr-pricklepants** [terra-money/core#704]
**Describe the bug**

In smart contracts if the developer uses `Event::new("")` without an attribute the node will panic (recoverable) due to a nil pointer dereference. 

https://github.com/terra-money/core/blame/main/x/wasm/types/connector.go#L39
https://github.com/terra-money/core/blame/main/x/wasm/types/connector.go#L49

**To Reproduce**

Deploy a smart contract to bombay-12 with `Ok(Response::new().add_event(Event::new("something"))` or `Ok(Response::default().add_event(Event::new("something")))` and then when you call the message it will panic with a nil pointer dereference. 

**Context & versions**
latest
tested on bombay-12

**(if applicable) suggested solution**

check if attributes are nil before dereferencing

**Comment by YunSuk-Yeo** [comment]
Thanks for finding, we will apply fix in the next hard fork.
