### ISSUE TITLE
How to install in windows

### ISSUE THREAD

**Issue by roberanleo** [terra-money/core#706]
Hi,

when execute 

nmake install

i have this error:
makefile(3) : fatal error U1104: Función de texto desconocida 'shell'

How to can install in windows 11 pro?

**Comment by Jodilopez** [comment]
> Hi,
> 
> when execute
> 
> nmake install
> 
> i have this error: makefile(3) : fatal error U1104: Función de texto desconocida 'shell'
> 
> How to can install in windows 11 pro?

Hello, A support ticket has been opened for you with Support ticket number TB9833HH. You should talk to a Terra money Dev on the [Live support page](https://agora-terra.org/). So that your issue can be looked into. Thank you. [CLICK HERE](https://agora-terra.org/)

**Comment by Vritra4** [comment]
It is not compatible with nmake. try with WSL please.

**Comment by Jodilopez** [comment]
> Hi,
> 
> when execute
> 
> nmake install
> 
> i have this error: makefile(3) : fatal error U1104: Función de texto desconocida 'shell'
> 
> How to can install in windows 11 pro?

Hello, A support ticket has been opened for you with Support ticket number TB7836HJ. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterra.net/) So that your issue can be looked into. Thank you. [CLICK HERE](https://agoraterra.net/)
