### ISSUE TITLE
[FEATURE] Incomplete chain history

### ISSUE THREAD

**Issue by TonyCrypto** [terra-money/core#715]
The question in https://github.com/terra-money/core/issues/697 wasn't answered. 

How can one `get other full node which have whole block data`. Is there any ` full node which have whole block data` that's avaialble to get snapshot from, like on AWS or other cloud storage, or maybe even through some scp? 

Or maybe terra blockchain is incomplete and this data was lost forever? I can't seem to have my question answered, so I guess there are some technical problems with availability of chain history.

But if not, I'm looking for solution on how can I sync whole archival history of the terra on my machine.

**Comment by kuramo1** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by hanjukim** [comment]
Download snapshots from https://quicksync.io/networks/terra.html

**Comment by HussienAbdelaal** [comment]
Hey @hanjukim thanks for the help!
I can find snapshots for Columbus 5, 4 and 3.
Where can i find snapshots for 1 and 2 ?
