### ISSUE TITLE
Error while executing "make install"

### ISSUE THREAD

**Issue by manuscommits** [terra-money/core#716]
I want to install terrad on windows but i got the following error while executing "make install":

Makefile:27: *** gcc.exe not installed for ledger support, please install or set LEDGER_ENABLED=false. Stop.

I installed gcc just to get another  error:
cgo-builtin-prolog:1:10: fatal error: stddef.h: No such file or directory
compilation terminated.
make: *** [Makefile:132: install] Error 2

Can anyone help me with this problem?

**Comment by Charlotte61** [comment]
> I want to install terrad on windows but i got the following error while executing "make install":
> 
> Makefile:27: *** gcc.exe not installed for ledger support, please install or set LEDGER_ENABLED=false. Stop.
> 
> I installed gcc just to get another error: cgo-builtin-prolog:1:10: fatal error: stddef.h: No such file or directory compilation terminated. make: *** [Makefile:132: install] Error 2
> 
> Can anyone help me with this problem?

Hello, A support ticket has been opened for you with Support ticket number TB8836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by Charlotte61** [comment]
> I want to install terrad on windows but i got the following error while executing "make install":
> 
> Makefile:27: *** gcc.exe not installed for ledger support, please install or set LEDGER_ENABLED=false. Stop.
> 
> I installed gcc just to get another error: cgo-builtin-prolog:1:10: fatal error: stddef.h: No such file or directory compilation terminated. make: *** [Makefile:132: install] Error 2
> 
> Can anyone help me with this problem?

Hello, A support ticket has been opened for you with Support ticket number TB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by hanjukim** [comment]
You will need mingw for compiling ledger and wasmer

**Comment by manuscommits** [comment]
I installed mingw and I got another error:

process_begin: CreateProcess(NULL, which docker, ...) failed.
Makefile:11: pipe: Bad file descriptor
process_begin: CreateProcess(NULL, dirname D:/programming/terra/core/contrib/devtools/Makefile, ...) failed.
contrib/devtools/Makefile:32: pipe: Bad file descriptor
contrib/devtools/Makefile:76: warning: overriding recipe for target 'D:\Program'
contrib/devtools/Makefile:66: warning: ignoring old recipe for target 'D:\Program'
go install -mod=readonly -tags "netgo ledger" -ldflags '-X github.com/cosmos/cosmos-sdk/version.Name=terra -X github.com/cosmos/cosmos-sdk/version.AppName=terrad -X github.com/cosmos/cosmos-sdk/version.Version=0.5.17-10-g13bb7ef -X github.com/cosmos/cosmos-sdk/version.Commit=13bb7ef790a8c4aca9067f81fd89ef9251980bc2 -X "github.com/cosmos/cosmos-sdk/version.BuildTags=netgo ledger," -w -s' -trimpath ./cmd/terrad
# github.com/CosmWasm/wasmvm/api
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_analyze_code':
/tmp/go-build/cgo-gcc-prolog:56: undefined reference to `analyze_code'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_execute':
/tmp/go-build/cgo-gcc-prolog:90: undefined reference to `execute'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_get_metrics':
/tmp/go-build/cgo-gcc-prolog:113: undefined reference to `get_metrics'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_ibc_channel_close':
/tmp/go-build/cgo-gcc-prolog:146: undefined reference to `ibc_channel_close'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_ibc_channel_connect':
/tmp/go-build/cgo-gcc-prolog:179: undefined reference to `ibc_channel_connect'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_ibc_channel_open':
/tmp/go-build/cgo-gcc-prolog:212: undefined reference to `ibc_channel_open'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_ibc_packet_ack':
/tmp/go-build/cgo-gcc-prolog:245: undefined reference to `ibc_packet_ack'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_ibc_packet_receive':
/tmp/go-build/cgo-gcc-prolog:278: undefined reference to `ibc_packet_receive'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_ibc_packet_timeout':
/tmp/go-build/cgo-gcc-prolog:311: undefined reference to `ibc_packet_timeout'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_init_cache':
/tmp/go-build/cgo-gcc-prolog:337: undefined reference to `init_cache'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_instantiate':
/tmp/go-build/cgo-gcc-prolog:371: undefined reference to `instantiate'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_load_wasm':
/tmp/go-build/cgo-gcc-prolog:395: undefined reference to `load_wasm'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_migrate':
/tmp/go-build/cgo-gcc-prolog:428: undefined reference to `migrate'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_pin':
/tmp/go-build/cgo-gcc-prolog:449: undefined reference to `pin'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_query':
/tmp/go-build/cgo-gcc-prolog:479: undefined reference to `query'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_reply':
/tmp/go-build/cgo-gcc-prolog:512: undefined reference to `reply'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_save_wasm':
/tmp/go-build/cgo-gcc-prolog:536: undefined reference to `save_wasm'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_sudo':
/tmp/go-build/cgo-gcc-prolog:569: undefined reference to `sudo'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_C2func_unpin':
/tmp/go-build/cgo-gcc-prolog:590: undefined reference to `unpin'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_analyze_code':
/tmp/go-build/cgo-gcc-prolog:609: undefined reference to `analyze_code'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_execute':
/tmp/go-build/cgo-gcc-prolog:639: undefined reference to `execute'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_get_metrics':
/tmp/go-build/cgo-gcc-prolog:658: undefined reference to `get_metrics'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_ibc_channel_close':
/tmp/go-build/cgo-gcc-prolog:687: undefined reference to `ibc_channel_close'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_ibc_channel_connect':
/tmp/go-build/cgo-gcc-prolog:716: undefined reference to `ibc_channel_connect'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_ibc_channel_open':
/tmp/go-build/cgo-gcc-prolog:745: undefined reference to `ibc_channel_open'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_ibc_packet_ack':
/tmp/go-build/cgo-gcc-prolog:774: undefined reference to `ibc_packet_ack'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_ibc_packet_receive':
/tmp/go-build/cgo-gcc-prolog:803: undefined reference to `ibc_packet_receive'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_ibc_packet_timeout':
/tmp/go-build/cgo-gcc-prolog:832: undefined reference to `ibc_packet_timeout'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_init_cache':
/tmp/go-build/cgo-gcc-prolog:854: undefined reference to `init_cache'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_instantiate':
/tmp/go-build/cgo-gcc-prolog:884: undefined reference to `instantiate'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_load_wasm':
/tmp/go-build/cgo-gcc-prolog:904: undefined reference to `load_wasm'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_migrate':
/tmp/go-build/cgo-gcc-prolog:933: undefined reference to `migrate'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_pin':
/tmp/go-build/cgo-gcc-prolog:950: undefined reference to `pin'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_query':
/tmp/go-build/cgo-gcc-prolog:976: undefined reference to `query'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_reply':
/tmp/go-build/cgo-gcc-prolog:1017: undefined reference to `reply'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_save_wasm':
/tmp/go-build/cgo-gcc-prolog:1037: undefined reference to `save_wasm'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_sudo':
/tmp/go-build/cgo-gcc-prolog:1066: undefined reference to `sudo'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_unpin':
/tmp/go-build/cgo-gcc-prolog:1083: undefined reference to `unpin'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x004.o: in function `_cgo_d3f6466c8ed4_Cfunc_release_cache':
/tmp/go-build/cgo-gcc-prolog:991: undefined reference to `release_cache'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x005.o: in function `_cgo_d3f6466c8ed4_Cfunc_destroy_unmanaged_vector':
/tmp/go-build/cgo-gcc-prolog:49: undefined reference to `destroy_unmanaged_vector'
c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: $WORK\b807\_x005.o: in function `_cgo_d3f6466c8ed4_Cfunc_new_unmanaged_vector':
/tmp/go-build/cgo-gcc-prolog:67: undefined reference to `new_unmanaged_vector'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:132: install] Error 2


Is it generally encouraged to use a linux setup?  I also get an error while executing the "optimizing your build with docker"-command. It seems like nothing is wirking on my computer :(
