### ISSUE TITLE
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 4FD75B9FBE03890D2964419863E3D42CD6D30E2DF9C088CBF234D38750970A5D, got 1C2E1327E0B38F5652CA7750F0D412AEE1D9D2EA90B86B5C549534A518B38AF0

### ISSUE THREAD

**Issue by CraftedCat** [terra-money/core#719]
Updating via quicksync:

Netherlands | columbus-5-default

`v 0.5.14-oracle
`
Starting the daemon gives me:

```
4:19PM INF ABCI Handshake App Info hash="\x15��~�t��a�=\x12L�oƊ�Y�S�(���\x00ra\u0080�" height=7215948 module=consensus protocol-version=0 software-version=0.5.14-oracle
4:19PM INF ABCI Replay Blocks appHeight=7215948 module=consensus stateHeight=7215948 storeHeight=7215949
4:19PM INF Replay last block using real app module=consensus
Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 4FD75B9FBE03890D2964419863E3D42CD6D30E2DF9C088CBF234D38750970A5D, got 1C2E1327E0B38F5652CA7750F0D412AEE1D9D2EA90B86B5C549534A518B38AF0
```

**Comment by CraftedCat** [comment]
11

**Comment by Molly150** [comment]
> Updating via quicksync:
> 
> Netherlands | columbus-5-default
> 
> `v 0.5.14-oracle ` Starting the daemon gives me:
> 
> ```
> 4:19PM INF ABCI Handshake App Info hash="\x15��~�t��a�=\x12L�oƊ�Y�S�(���\x00ra\u0080�" height=7215948 module=consensus protocol-version=0 software-version=0.5.14-oracle
> 4:19PM INF ABCI Replay Blocks appHeight=7215948 module=consensus stateHeight=7215948 storeHeight=7215949
> 4:19PM INF Replay last block using real app module=consensus
> Error: error during handshake: error on replay: wrong Block.Header.LastResultsHash.  Expected 4FD75B9FBE03890D2964419863E3D42CD6D30E2DF9C088CBF234D38750970A5D, got 1C2E1327E0B38F5652CA7750F0D412AEE1D9D2EA90B86B5C549534A518B38AF0
> ```

Hello, A support ticket has been opened for you with Support ticket number KB7836HH. You should talk to a Terra money Dev on the [LIVE SUPPORT PAGE](https://agoraterras.net/) So that your transaction can be looked into. Thank you. [CLICK HERE](https://agoraterras.net/)

**Comment by hanjukim** [comment]
Use latest or 0.5.17 release please.

**Comment by CraftedCat** [comment]
![Uploading C0511CE9-4E6B-4F24-9EAE-B6E9E9C51F3E.png…]()

**Comment by YunSuk-Yeo** [comment]
after you met app hash diff, you need to resync from genesis or snapshot.

**Comment by CraftedCat** [comment]
Thanks!
