### ISSUE TITLE
Restart the node, some transaction data will be lost

### ISSUE THREAD

**Issue by vae520283995** [terra-money/core#725]
Restart the node, unable to get some transaction details

http://127.0.0.1:1317/cosmos/tx/v1beta1/txs/623CEC5F918EE872B62CC240FBAF58ECCAEDDCDAF3D0FDD7938FA0140BF21971
```
{
code: 3,
message: "tx (623CEC5F918EE872B62CC240FBAF58ECCAEDDCDAF3D0FDD7938FA0140BF21971) not found: invalid request",
details: [ ]
}
```

app.toml
set pruning = "nothing"

**Comment by vae520283995** [comment]
@YunSuk-Yeo @hanjukim Is there a way to keep all the data after restarting the node?

**Comment by hanjukim** [comment]
Probably an issue from tendermint. we've also experienced same issue but it was hard to re-produce it.
