### ISSUE TITLE
Error: error during handshake: error on replay: wrong Block.Header.AppHash.

### ISSUE THREAD

**Issue by prathmeshgotoadmins** [terra-money/core#74]
Hi
I am using latest terrad binary (v2.1.1), but it is failing with below error.

Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 80C0AE8EE0C541309E23201A8E7A51DF007949E6655BACA5C6EF89D960D2F59E, got FAD24DA1C86E3D6476C1951C34C35956F9B365202BF7A4F8602C4B7F113438A2

Please guide me, what I can do next?

**Comment by hg9679** [comment]
I think you can switch to v2.0.0-rc.1 and  terrad init

**Comment by lcgogo** [comment]
same issue, should I use v2.0.0-rc.1 instead? @hg9679

**Comment by prathmeshgotoadmins** [comment]
Updated terrad binary and resynced, It has resolved the issue, Thanks @hg9679  @lcgogo
