### ISSUE TITLE
'Terrad keys add' overflows swap and ram after numerous runs in a row

### ISSUE THREAD

**Issue by younicoin** [terra-money/core#77]
Hello, dear developers and users! I try to find beautiful (vanity) addresses on Terra blockchain, and I use terrad for generate new account and check address fit for me. But numerous run of terrad causes the error on inodes.

I made bash script that runs
terrad keys add 1 --dry-run 2>&1
and then checks if address has word I want to find. And script puts the address and pass phrase to my file terra.log
Watching terra.log after some time (2 minutes) I see this error:

tail -f terra.log 
tail: inotify cannot be used, reverting to polling: Too many open files

If I keep run terrad again and again for 15-30 minutes, terrad falls and do not work with error like 'couldnt start, and some strings from memory'. So it breaks my swap memory and breaks my inodes.

Could you advise me something?
Here it is a script I wrote: https://pastebin.com/mdUkrd9h

**Comment by younicoin** [comment]
for example now, after my script worked 15 minutes, I got my memory is almost full:

```
free -m
               total        used        free      shared  buff/cache   available
Mem:           23863       14245        7859         466        1757        8760
Swap:            976           0         976
```

I do not know how to clean memory after terrad.

**Comment by younicoin** [comment]
Hello! I typed this script on Python3 https://gitgud.io/youni/terra-beautiful-address-generator-on-python/
I use Terra-SDK for generate mnemonic and address https://pypi.org/project/terra-sdk/
It works slowly but it does not fail. And I run 5 processes in parallel.

**Comment by gregnuj** [comment]
Could not reproduce
