### ISSUE TITLE
LUNC as payment method

### ISSUE THREAD

**Issue by mehranrezaei** [terra-money/core#81]
I am working in a software development team that is implementing a very large project similar to Udemy. We plan to accept ```LUNC``` as a payment method. 
Can anyone advise where I should start to implement this payment method? 
Our development technology is ASP.NET. But if there is guidance in other technologies, it can be helpful.

**Comment by shackra** [comment]
@mehranrezaei better head over the Terra Rebels' Discord https://github.com/terra-rebels
