### ISSUE TITLE
terrad wrong text ("Enter your bip39 mnemonic") when recovering key, since default is BIP44

### ISSUE THREAD

**Issue by taitruong** [terra-money/core#89]
```sh
$ terrad keys add test --recover
> Enter your bip39 mnemonic
```
Text should be depending on hd-path. in this case it should be ("Enter your bip44 mnemonic").

Read more on Terra discord about the problem: https://discord.com/channels/983359798059892766/983359798521266211/1052676219549794304

For bip39 (coin type 118) command is the following: `terrad keys add test --recover --hd-path "m/44'/118'/0'/0/0"`
whereas for bip44 (coin type 330) it is `--hd-path "m/44'/330'/0'/0/0"` (default).

**Comment by emidev98** [comment]
Hey @taitruong, 

When it prompts [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki) it's referring to the words not to the standard ([BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)) used to calculate the keys on a deterministic way. 

As you can see [in the following code](https://github.com/terra-money/cosmos-sdk/blob/release/v0.45.x/client/keys/add.go#L221) further validations are done to the user input to see if it matches the BIP39 standard.

Thanks for submitting the issue, feel free to keep contributing in the future!
