### ISSUE TITLE
About v2.0 client and v0.5.20 client

### ISSUE THREAD

**Issue by masayil** [terra-money/core#9]
Hi. Can 2.0 client be upgraded directly on the previous chain(version:v0.5.20)? Or need to regenesis?

**Comment by hanjukim** [comment]
@masayil you need to regenesis.

**Comment by masayil** [comment]
> @masayil you need to regenesis.

Get it. thanks. By the way, Will Terra split into 2 chains(Terra and Terra classic) later?

**Comment by masayil** [comment]
Terra 2.0 should not be online yet. Right?

**Comment by airstring** [comment]
> Terra 2.0 **mainnet** should not be online yet. Right? Genesis file: https://cloudflare-ipfs.com/ipfs/QmZAMcdu85Qr8saFuNpL9VaxVqqLGWNAs72RVFhchL9jWs ![image](https://user-images.githubusercontent.com/65291464/169795315-9f29f4ab-6b51-47f3-a217-d8fdf614abb0.png) log panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount
> 
> goroutine 1 [running]: github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x3e6aa48, {0xc181a90000, 0x0, 0x0}, {0x2ce0f90, 0xc00027e100}) github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45 github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis({{}, {{0x2cdb148, 0xc0013fc4d0}, {0x2d36de8, 0xc00127e3d0}, {{0x2d36de8, 0xc00127e3d0}, 0xc00059ac58, {0x2cdb148, 0xc0013fc540}, ...}, ...}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/x/auth/module.go:143 +0xa2 github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2d0f228, 0xc000052050}, {0x2d3c5a0, 0xc00024dac0}, {{0x0, 0x0}, {0xc000fb21b0, 0xa}, 0x481521, ...}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d github.com/terra-money/core/v2/app.(*TerraApp).InitChainer(_, {{0x2d0f228, 0xc000052050}, {0x2d3c5a0, 0xc00024dac0}, {{0x0, 0x0}, {0xc000fb21b0, 0xa}, 0x481521, ...}, ...}, ...) github.com/terra-money/core/v2/app/app.go:700 +0x209 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000603ba0, {{0x0, 0xed8e781c9, 0x0}, {0xc000fb21b0, 0xa}, 0xc00057ed00, {0xc000033900, 0x82, 0x82}, ...}) github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x475 github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00059ff20, {{0x0, 0xed8e781c9, 0x0}, {0xc000fb21b0, 0xa}, 0xc00057ed00, {0xc000033900, 0x82, 0x82}, ...}) github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118 github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3, {{0x0, 0xed8e781c9, 0x0}, {0xc000fb21b0, 0xa}, 0xc00057ed00, {0xc000033900, 0x82, 0x82}, ...}) github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55 github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2ca9ca0, 0x10}}, {0xc000fb21b0, 0xa}, 0x481521, 0x0, {{0x0, ...}, ...}, ...}, ...) github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd98 github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc04bd75fe0, {0x2d3da80, 0xc000202820}) github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8 github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2ca9ca0, 0x10}}, {0xc000fb21b0, 0xa}, 0x481521, 0x0, ...}, ...) github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8 github.com/tendermint/tendermint/node.NewNode(0xc0012fca00, {0x2ceb430, 0xc000131220}, 0xc000205860, {0x2ccc4c0, 0xc0001e3938}, 0x0, 0x0, 0xc000205aa0, {0x2d10220, ...}, ...) github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578 github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2d4ed58, 0xc00141a9f0}, {0x0, 0x0}, {0x2d18a48, 0xc00127e3d0}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7e5 github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00130ec80, {0xc0012e7ce0, 0x0, 0x2}) github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169 github.com/spf13/cobra.(*Command).execute(0xc00130ec80, {0xc0012e7cc0, 0x2, 0x2}) github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc0012da280) github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.4.0/command.go:902 github.com/spf13/cobra.(*Command).ExecuteContext(...) github.com/spf13/cobra@v1.4.0/command.go:895 github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc001029068, 0x17}) github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb main.main() github.com/terra-money/core/v2/cmd/terrad/main.go:15 +0x2c

Have you taken care of it? How is it solved？

**Comment by oneusdt** [comment]
I want to run Terra classic network.Same problem

**Comment by masayil** [comment]
> I want to run Terra classic network.Same problem

How about start from a snapshot?
https://quicksync.io/networks/terra.html

**Comment by masayil** [comment]
> > Terra 2.0 **mainnet** should not be online yet. Right? Genesis file: https://cloudflare-ipfs.com/ipfs/QmZAMcdu85Qr8saFuNpL9VaxVqqLGWNAs72RVFhchL9jWs ![image](https://user-images.githubusercontent.com/65291464/169795315-9f29f4ab-6b51-47f3-a217-d8fdf614abb0.png) log panic: unable to resolve type URL /terra.vesting.v1beta1.LazyGradedVestingAccount
> > goroutine 1 [running]: github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x3e6aa48, {0xc181a90000, 0x0, 0x0}, {0x2ce0f90, 0xc00027e100}) github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45 github.com/cosmos/cosmos-sdk/x/auth.AppModule.InitGenesis({{}, {{0x2cdb148, 0xc0013fc4d0}, {0x2d36de8, 0xc00127e3d0}, {{0x2d36de8, 0xc00127e3d0}, 0xc00059ac58, {0x2cdb148, 0xc0013fc540}, ...}, ...}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/x/auth/module.go:143 +0xa2 github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2d0f228, 0xc000052050}, {0x2d3c5a0, 0xc00024dac0}, {{0x0, 0x0}, {0xc000fb21b0, 0xa}, 0x481521, ...}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d github.com/terra-money/core/v2/app.(*TerraApp).InitChainer(_, {{0x2d0f228, 0xc000052050}, {0x2d3c5a0, 0xc00024dac0}, {{0x0, 0x0}, {0xc000fb21b0, 0xa}, 0x481521, ...}, ...}, ...) github.com/terra-money/core/v2/app/app.go:700 +0x209 github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc000603ba0, {{0x0, 0xed8e781c9, 0x0}, {0xc000fb21b0, 0xa}, 0xc00057ed00, {0xc000033900, 0x82, 0x82}, ...}) github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x475 github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00059ff20, {{0x0, 0xed8e781c9, 0x0}, {0xc000fb21b0, 0xa}, 0xc00057ed00, {0xc000033900, 0x82, 0x82}, ...}) github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118 github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3, {{0x0, 0xed8e781c9, 0x0}, {0xc000fb21b0, 0xa}, 0xc00057ed00, {0xc000033900, 0x82, 0x82}, ...}) github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55 github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x2ca9ca0, 0x10}}, {0xc000fb21b0, 0xa}, 0x481521, 0x0, {{0x0, ...}, ...}, ...}, ...) github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd98 github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc04bd75fe0, {0x2d3da80, 0xc000202820}) github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8 github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x2ca9ca0, 0x10}}, {0xc000fb21b0, 0xa}, 0x481521, 0x0, ...}, ...) github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8 github.com/tendermint/tendermint/node.NewNode(0xc0012fca00, {0x2ceb430, 0xc000131220}, 0xc000205860, {0x2ccc4c0, 0xc0001e3938}, 0x0, 0x0, 0xc000205aa0, {0x2d10220, ...}, ...) github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578 github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2d4ed58, 0xc00141a9f0}, {0x0, 0x0}, {0x2d18a48, 0xc00127e3d0}, ...}, ...) github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:272 +0x7e5 github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc00130ec80, {0xc0012e7ce0, 0x0, 0x2}) github.com/cosmos/cosmos-sdk@v0.45.4/server/start.go:126 +0x169 github.com/spf13/cobra.(*Command).execute(0xc00130ec80, {0xc0012e7cc0, 0x2, 0x2}) github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e github.com/spf13/cobra.(*Command).ExecuteC(0xc0012da280) github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc github.com/spf13/cobra.(*Command).Execute(...) github.com/spf13/cobra@v1.4.0/command.go:902 github.com/spf13/cobra.(*Command).ExecuteContext(...) github.com/spf13/cobra@v1.4.0/command.go:895 github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc001029068, 0x17}) github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb main.main() github.com/terra-money/core/v2/cmd/terrad/main.go:15 +0x2c
> 
> Have you taken care of it? How is it solved？

Hi.It is recommended that you create a new issue.The mainnet was not yet online at May.23 I also currently do not continue to run a Terra 2.0 node.
