### ISSUE TITLE
An error occurs when updating to v2.2.0

### ISSUE THREAD

**Issue by timurgum** [terra-money/core#90]
panic: runtime error: invalid memory address or nil pointer dereference

**Comment by agj-jump** [comment]
Any resolution for this issue? Seeing similar error while bumping up version to v2.2.0.
`Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: panic: runtime error: invalid memory address or nil pointer dereference
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x169278d]
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: goroutine 1 [running]:
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0xc0001294e8, 0x12}, 0xc000d57620, {0x27a9128, 0xc0005a18a0}, {0x27c7f20, 0xc0005a0fa0}, 0xc000dc2e70, {0x0, 0x0}, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/cosmos/cosmos-sdk@v0.45.10/x/upgrade/abci.go:38 +0x100d
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/cosmos/cosmos-sdk@v0.45.10/x/upgrade/module.go:130
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x27bc638, 0xc0001a6020}, {0x27c9820, 0xc00e2f5800}, {{0xb, 0x0}, {0xc00e25e860, 0x9}, 0x2d44f8, ...}, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/cosmos/cosmos-sdk@v0.45.10/types/module/module.go:491 +0x3bb
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/terra-money/core/v2/app.(*TerraApp).BeginBlocker(_, {{0x27bc638, 0xc0001a6020}, {0x27c9820, 0xc00e2f5800}, {{0xb, 0x0}, {0xc00e25e860, 0x9}, 0x2d44f8, ...}, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/terra-money/core/v2/app/app.go:671 +0x85
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc00e2ef380, 0x20, 0x20}, {{0xb, 0x0}, {0xc00e25e860, 0x9}, 0x2d44f8, {0x20e6b46e, ...}, ...}, ...})
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/cosmos/cosmos-sdk@v0.45.10/baseapp/abci.go:177 +0x97c
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc00e2ef380, 0x20, 0x20}, {{0xb, 0x0}, {0xc00e25e860, 0x9}, 0x2d44f8, {0x20e6b46e, ...}, ...}, ...})
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/abci/client/local_client.go:280 +0x118
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc00e2ef380, 0x20, 0x20}, {{0xb, 0x0}, {0xc00e25e860, 0x9}, 0x2d44f8, {0x20e6b46e, ...}, ...}, ...})
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/proxy/app_conn.go:81 +0x55
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x27bd710?, 0xc0005386c0}, {0x27c2cc0, 0xc00110ad50}, 0xc0000005a0, {0x27c90a8, 0xc00019c480}, 0x2d44f7?)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/state/execution.go:307 +0x3dd
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc00dbec1d0, 0x10}}, {0xc00dbec1e0, 0x9}, 0x1, 0x2d44f7, {{0xc00dc596e0, ...}, ...}, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/state/execution.go:140 +0x171
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc00dbec1d0, 0x10}}, {0xc00dbec1e0, 0x9}, 0x1, 0x2d44f7, {{0xc00dc596e0, ...}, ...}, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:503 +0x23c
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc00dbec1d0, 0x10}}, {0xc00dbec1e0, 0x9}, 0x1, 0x2d44f7, {{0xc00dc596e0, ...}, ...}, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:416 +0x7ae
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00e30fdf0, {0x27c9f68, 0xc000dfc000})
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/consensus/replay.go:268 +0x3c8
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc00dbec1d0, 0x10}}, {0xc00dbec1e0, 0x9}, 0x1, 0x2d44f7, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/node/node.go:330 +0x1b8
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/tendermint/tendermint/node.NewNode(0xc000ed6dc0, {0x27b93d0, 0xc00050cd20}, 0xc00105d420, {0x27a4340, 0xc000f31ce0}, 0x0?, 0x0?, 0xc00105d630, {0x27bd710, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/tendermint/tendermint@v0.34.22/node/node.go:778 +0x597
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x27d08f8, 0xc000def0b0}, {0x0, 0x0}, {0x27c0a60, 0xc0005a0fa0}, ...}, ...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:280 +0x7db
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/cosmos/cosmos-sdk/server.StartCmd.func2(0xc0001b2c80?, {0xc000dc1e80?, 0x0?, 0x1?})
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/cosmos/cosmos-sdk@v0.45.10/server/start.go:128 +0x169
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/spf13/cobra.(*Command).execute(0xc0001b2c80, {0xc000dc1e70, 0x1, 0x1})
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/spf13/cobra@v1.5.0/command.go:872 +0x694
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/spf13/cobra.(*Command).ExecuteC(0xc00050f900)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/spf13/cobra.(*Command).Execute(...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/spf13/cobra@v1.5.0/command.go:918
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/spf13/cobra@v1.5.0/command.go:911
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0?, {0xc0001294e8, 0x12})
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/cosmos/cosmos-sdk@v0.45.10/server/cmd/execute.go:36 +0x1eb
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]: main.main()
Dec 20 21:07:59 geuw3a-ccn-terra-phoenix-api1.jumpisolated.com terrad[3247758]:         github.com/terra-money/core/v2/cmd/terrad/main.go:15 +0x2c`

**Comment by gregnuj** [comment]
Close due to inactivity, please let us know if you are still experiencing the issue
