### ISSUE TITLE
Bring up to date

### ISSUE THREAD

**Issue by faddat** [terra-money/core#97]
* #96

...but actionable, and with action

At minimum, terra should use:

* iavl 0.19.4
* tendermint v0.34.x <-tip of branch
*  go 1.19
* wasmd v0.30.0
* ibc-go v4.2.0
* cosmos-sdk v0.45.11
* wasmvm v1.1.1

My preference is to be a bit more bold:

* iavl v0.19.4
* tendermint v0.34.x <- tip of branch
* go 1.19
* ibc-go v6.1.0
* cosmos-sdk v0.46.7
* wasmvm v1.1.1
* wasmd v0.30.0+46 

## Note

I'll begin with the first of the two routes.  Will make PR's into the needed forked repos. 

## Related external PR's

* https://github.com/terra-money/wasmd/pull/1
* https://github.com/terra-money/cosmos-sdk/pull/165
* https://github.com/terra-money/tendermint/pull/118
* https://github.com/terra-money/tm-db/pull/5

**Comment by gregnuj** [comment]
resolved in release/v2.3
